### ISSUE TITLE
Single point of configuration for global tolerations and node selector

### ISSUE THREAD

**Issue by sjmiller609** [kubecost/cost-analyzer-helm-chart#109]
**What problem are you trying to solve?**

We at Astronomer (astronomer.io) use node taints in combination with node-affinity and tolerations to organize components in node pools. In our case, this is because we want multi-tenant components on separate node pool(s) from our platform components. We hope to use Kubecost in our platform components.

When I say 'node selector', I am actually referring to nodeAffinity + nodeSelectorTerms, which is the 'new and improved' way of doing node selectors.

**Describe the solution you'd like**

I would like for there to be a global configuration at the top-level values.yaml
example, node selectors:
```
global:
  nodeSelectors:
    "astronomer.io/multi-tenant": "false"
    "astronomer.io/another-one": "ok"
```
I want this to end up on the containers using affinity.
```
# in the container spec
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: "astronomer.io/multi-tenant"
              operator: In
              values:
              - "false"
          - matchExpressions:
            - key: "astronomer.io/another-one"
              operator: In
              values:
              - "ok"
```
example, tolerations:
values.yaml
```
global:
      tolerations:
      - key: "platform"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
```
outcome:
```
# (output of kubectl describe pod command on any component)
Tolerations:     
                 platform=true:NoSchedule
```

**Describe alternatives you've considered**

I have noticed some configurations like this exist in the subcharts. I will try to do it by configuring each sub-chart appropriately by passing the values from the top-level chart to the subcharts.

**How would users interact with this feature?**

helm values.
