### ISSUE TITLE
basic auth support for switch cluster view

### ISSUE THREAD

**Issue by kbrwn** [kubecost/cost-analyzer-helm-chart#1091]
**What problem are you trying to solve?**
If you enable basic auth on ingress fronting kubecost there is no way to add the cluster to switch view 

**Describe the solution you'd like**
Support for passing basic auth creds in the values.yaml for clusters in switch view 

**Describe alternatives you've considered**

passing the credentials in the url like `http://username:password@kubecost.example.xyz` but this does not work

**How would users interact with this feature?**

Editing the values.yaml
<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/866'>Zendesk ticket #866</a>)<br>gz#866</i>

**Comment by kbrwn** [comment]
fetch the creds from "/clusters" and attach them as headers to the requests made on that page

**Comment by deepshah93** [comment]
Hi team, any updates on this issue? Let me know if I could be of any help.

**Comment by AjayTripathy** [comment]
Hi @deepshah93 thanks for pinging this issue-- it should be fixed as of v1.88.0 https://github.com/kubecost/cost-analyzer-helm-chart/releases/tag/v1.88.0

**Comment by cookandy** [comment]
Hello,

I am using `1.88.1` and still see this issue. My config
  
```
  kubecostProductConfigs:
    clusterName: "dev"
    clusters:
     - name: "us"
       address: https://costs-us.mydomain.com
       auth:
         type: basic
         user: myuser
         pass: xxx
     - name: "eu"
       address: https://costs-eu.mydomain.com
       auth:
         type: basic
         user: myuser
         pass: xxx
```

When i open the web interface on the "dev" cluster, I can see the remote clusters listed, but there’s no info about the cluster – it just spins. Looking at the browser console, I can see a 401 trying to connect to the remote clusters 

```
GET https://https://costs-us.mydomain.com/model/clusterInfo?req=799635 401
GET https://https://costs-us.mydomain.com/api/allNodes 401
GET https://https://costs-us.mydomain.com/model/assets?window=7d&aggregate=type&accumulate=true 401
GET https://https://costs-us.mydomain.com/model/clusterInfo 401
GET https://https://costs-eu.mydomain.com/model/clusterInfo?req=409991 401
GET https://https://costs-eu.mydomain.com/model/getConfigs?req=149367 401
Error: no model config found
GET https://https://costs-eu.mydomain.com/api/allNodes 401
GET https://https://costs-eu.mydomain.com/model/assets?window=7d&aggregate=type&accumulate=true 401
GET https://https://costs-eu.mydomain.com/model/clusterInfo 401
GET https://https://costs-eu.mydomain.com/model/clusterInfo 401
connected to https://costs-eu.mydomain.com/api
```


If i expand the errors I can confirm it’s the nginx unauthorized page. Similarly, I experience 401s when trying to use the "switch cluster" feature.

Here is the output of `/model/clusters`.

```
{"code":200,"status":"success","data":[{"id":"us","name":"us","address":"https://costs-us.mydomain.com","details":{"auth":"xxx=="}},{"id":"eu","name":"eu","address":"https://costs-eu.mydomain.com","details":{"auth":"xxxx=="}}]}
```

Please let me know if you need any more info.

**Comment by AjayTripathy** [comment]
Hi @cookandy do those GET requests have associated headers for basic auth attached?

**Comment by cookandy** [comment]
Hi @AjayTripathy. Yes, they appear to have the `Authorization` header present

Example request

```
GET /model/clusterInfo?req=279722 HTTP/2
Host: costs-eu.mydomain.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:95.0) Gecko/20100101 Firefox/95.0
Accept: application/json
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Content-Type: application/json
Authorization: Basic xxx==
Origin: https://costs-dev.mydomain.com
DNT: 1
Connection: keep-alive
Referer: https://costs-dev.mydomain.com/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
TE: trailers
```

And the response

```
HTTP/2 401 Unauthorized
date: Thu, 06 Jan 2022 22:23:35 GMT
content-type: text/html
content-length: 172
www-authenticate: Basic realm=""
strict-transport-security: max-age=15724800; includeSubDomains
access-control-allow-origin: https://costs-dev.mydomain.com
access-control-allow-credentials: true
access-control-allow-methods: GET, PUT, POST, DELETE, PATCH, OPTIONS
access-control-allow-headers: DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization
access-control-max-age: 1728000
X-Firefox-Spdy: h2
```

**Comment by AjayTripathy** [comment]
How does the authentication information in the header compare with your expectations of what the username and password should be? We'd expect that to be a base64 encoded version of what you supplied in the helm values file-- can you confirm that base64Decode(xxx==) is different from "USERNAME:PASSWORD" supplied in helm?

**Comment by cookandy** [comment]
I confirmed that the base64 decoded `Authorization` header matches the `user:password` value I have stored in the K8s secret. 

For the password, I have tried a straight `user:password` value, as well as using a password created by `htpasswd`.

**Comment by AjayTripathy** [comment]
That header looks correct, so something else is going on here. How was basic auth set up on the remote clusters?

**Comment by cookandy** [comment]
@AjayTripathy basic auth was configured using the [Nginx ingress](https://kubernetes.github.io/ingress-nginx/examples/auth/basic/) with the following annotations

```yaml
    nginx.ingress.kubernetes.io/auth-secret: kubecost-basic-auth
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/cors-allow-origin: https://costs-dev.mydomain.com
    nginx.ingress.kubernetes.io/enable-cors: "true"
```

And the secret is just the `user:pass` created by `htpasswd`. Something like `user:$apr1$IHbR10Of$J7L959.rmUm2b8lJv5DZJ1`

```yaml
apiVersion: v1
data:
  auth: dXNlcjokYXByMSRJSGJSMTBPZiRKN0w5NTkucm1VbTJiOGxKdjVEWkoxCg==
kind: Secret
metadata:
  name: kubecost-basic-auth
```

I can confirm basic auth works via the browser when going to the webpage directly. 

Just to clarify, when using `  kubecostProductConfigs.clusters.auth.secretName` in the Helm chart, is it expecting a direct `user:pass`? Or the `htpasswd` version of the password?
