### ISSUE TITLE
kubecost on helm charts update with resource limits defined. PVC error: Forbidden: spec is immutable after creation except resources.requests for bound claims site:stackoverflow.com

### ISSUE THREAD

**Issue by doonto** [kubecost/cost-analyzer-helm-chart#1103]
**Describe the bug**
Hello,
We've installed kubecost using the helm charts on Azure.

```
trigger:
  branches:
    include:
      - none

resources:
  # Pipeline templates
  repositories:
    - repository: templates
      type: git
      name: build/azure-pipeline-templates
      ref: refs/heads/main

variables:
  kubernetesNamespace: kubecost

parameters:
- name: enabledStages
  type: object
  default: [ 'auea_npr' ] # References build/azure-pipeline-templates/_stages
- name: validationOnly
  type: boolean
  default: false

stages:
- template: _templates/build-publish-repo.yml@templates
- ${{ each stage in parameters.enabledStages }}:
  - stage: ${{ stage }}
    variables:
    - template: _stages/${{ stage }}.yml@templates
    dependsOn: ${{ variables.dependsOn }}
    displayName: '${{ variables.spokeName }}'
    condition: |
      or(
        and( 
          eq(variables['build.sourceBranch'], 'refs/heads/main'),
          contains('${{ variables.spokeName }}', 'prd')
        ),
        contains('${{ variables.spokeName }}', 'npr'),
        eq('${{ parameters.validationOnly }}', true)
      )
    jobs:
    - job: Validation
      displayName: 'Validation'
      steps:
      - download: current
        displayName: 'Download Pipeline Artifact'
      - task: HelmDeploy@0
        displayName: 'Add Repo'
        inputs:
          connectionType: Azure Resource Manager
          azureSubscriptionEndpoint: platform-${{ variables.spokeName }}-kubernetes
          azureResourceGroup: platform-${{ variables.spokeName }}-aks-rg
          kubernetesCluster: ${{ variables.spokeName }}-aks
          command: repo
          arguments: add kubecost https://kubecost.github.io/cost-analyzer
      - task: HelmDeploy@0
        displayName: Helm Upgrade Chart
        inputs:
          connectionType: Azure Resource Manager
          azureSubscriptionEndpoint: platform-${{ variables.spokeName }}-kubernetes
          azureResourceGroup: platform-${{ variables.spokeName }}-aks-rg
          kubernetesCluster: ${{ variables.spokeName }}-aks
          namespace: ${{ variables.kubernetesNamespace }}
          command: upgrade
          useClusterAdmin: true
          waitForExecution: false
          chartName: kubecost/cost-analyzer
          releaseName: kubecost
          arguments: --debug --dry-run --force --cleanup-on-fail  --values $(Pipeline.Workspace)/drop/values/${{ variables.spokeName }}-values.yaml
    - deployment: Deploy
      displayName: 'Deployment'
      dependsOn: Validation
      condition: and(succeeded(), eq('${{ parameters.validationOnly }}', false))
      environment: '${{ variables.devopsEnvironmentBaseName }}-${{ variables.kubernetesNamespace }}'
      strategy:
        runOnce:
          deploy:
            steps:
            - download: current
              displayName: 'Download Pipeline Artifact'
            - task: HelmDeploy@0
              displayName: 'Add Repo'
              inputs:
                connectionType: Azure Resource Manager
                azureSubscriptionEndpoint: platform-${{ variables.spokeName }}-kubernetes
                azureResourceGroup: platform-${{ variables.spokeName }}-aks-rg
                kubernetesCluster: ${{ variables.spokeName }}-aks
                command: repo
                arguments: add kubecost https://kubecost.github.io/cost-analyzer
            - task: HelmDeploy@0
              displayName: Helm Upgrade Chart
              inputs:
                connectionType: Azure Resource Manager
                azureSubscriptionEndpoint: platform-${{ variables.spokeName }}-kubernetes
                azureResourceGroup: platform-${{ variables.spokeName }}-aks-rg
                kubernetesCluster: ${{ variables.spokeName }}-aks
                namespace: ${{ variables.kubernetesNamespace }}
                command: upgrade
                useClusterAdmin: true
                waitForExecution: false
                install: true
                force: true
                chartName: kubecost/cost-analyzer
                releaseName: kubecost
                arguments: --cleanup-on-fail --values $(Pipeline.Workspace)/drop/values/${{ variables.spokeName }}-values.yaml
```

But we've also restricted the pod of running without resource limits to be defined. So, we had to configure the limits in the values.yaml:

```
persistentVolume:
  storageClass: azure-disk-standard
  size: 8Gi
  dbSize: 8Gi
prometheus:
  server:
    persistentVolume:
      size: 8Gi
      storageClass: azure-disk-standard
    resources:
      limits:
        cpu: "160m"
        memory: "1600Mi"
      requests:
         cpu: "150m"
         memory: "1512Mi"
  configmapReload:
    prometheus:
      resources:
        limits:
          cpu: "30m"
          memory: "140Mi"
        requests:
          cpu: "20m"
          memory: "128Mi"
  kube-state-metrics:
    resources:
      limits:
        cpu: "30m"
        memory: "256Mi"
      requests:
        cpu: "20m"
        memory: "228Mi"
  nodeExporter:
    resources:
      limits:
        cpu: "160m"
        memory: "268Mi"
      requests:
        cpu: "150m"
        memory: "256Mi"
grafana:
  resources:
    limits:
      cpu: "60m"
      memory: "524Mi"
    requests:
       cpu: "50m"
       memory: "512Mi"
  sidecar:
    resources:
      limits:
        cpu: "110m"
        memory: "268Mi"
      requests:
        cpu: "100m"
        memory: "256Mi"
kubecostFrontend:
  resources:
    limits:
      cpu: "30m"
      memory: "76Mi"
    requests:
       cpu: "20m"
       memory: "55Mi"
kubecost:
  resources:
    limits:
      cpu: "110m"
      memory: "524Mi"
    requests:
       cpu: "100m"
       memory: "512Mi"
kubecostModel:
  resources:
    limits:
      cpu: "110m"
      memory: "524Mi"
    requests:
       cpu: "100m"
       memory: "512Mi"

nodeSelector: {
    agentpool: "platform"
 }

tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
    effect: NoSchedule
```

**To Reproduce**

The problem is following:
whenever we try to change anything in the values.yaml, not even connected to the PV - we get an error on deployment:

```
failed to replace object: PersistentVolumeClaim "kubecost-prometheus-server" is invalid: spec: Forbidden: spec is immutable after creation except resources.requests for bound claims
  core.PersistentVolumeClaimSpec{
  	AccessModes:      {"ReadWriteOnce"},
  	Selector:         nil,
  	Resources:        {Requests: {s"storage": {i: {...}, Format: "BinarySI"}}},
- 	VolumeName:       "",
+ 	VolumeName:       "pvc-6b6922e3-ce66-4360-b9b7-57a7e6104da6",
  	StorageClassName: &"azure-disk-standard",
  	VolumeMode:       &"Filesystem",
  	DataSource:       nil,
```

```
failed to replace object: PersistentVolumeClaim "kubecost-cost-analyzer" is invalid: spec: Forbidden: spec is immutable after creation except resources.requests for bound claims
  core.PersistentVolumeClaimSpec{
  	AccessModes:      {"ReadWriteOnce"},
  	Selector:         nil,
  	Resources:        {Requests: {s"storage": {i: {...}, Format: "BinarySI"}}},
- 	VolumeName:       "",
+ 	VolumeName:       "pvc-7059127c-6189-478f-b8b8-c82460749f3a",
  	StorageClassName: &"azure-disk-standard",
  	VolumeMode:       &"Filesystem",
  	DataSource:       nil,
  }
```

**Expected behavior**
Wanted to get specs updated.

My thinking is that we need to define the PV differently in the values.yaml, so the size will come not in the immutable `spec` section, rather than is the resources.requests. But what specification is supported?

Can it be a bug to documentation? I wasted lots of time, picking dependent kubecost resources to define the resource limits for them, not all is mentioned in the initial help.

gz#917
