### ISSUE TITLE
document about manage productKey as secret is unclear 

### ISSUE THREAD

**Issue by ozbillwang** [kubecost/cost-analyzer-helm-chart#1139]
the document or values.yml doesn't give enough detail on how the secret file looks lik

```
kubecostProductConfigs:
  productKey: # apply business or enterprise product license
    enabled: true
    secretname: productkeysecret # create a secret out of a file named productkey.json of format { "key": "kc-b1325234" }
```

the comments in `values.yaml` is terrible. 

```
# create a secret out of a file named productkey.json of format { "key": "kc-b1325234" }
```
What's the meaning?

Finally I got what it need

```
$ cat productkey.json
{ "key": "kc-b1325234" }

$ kubectl create secret generic productkeysecret -n kubecost --from-literal "productkey.json=$(cat productkey.json)"
```

Please confirm if this is proper way to set it
