### ISSUE TITLE
4 years old image is used in this chart

### ISSUE THREAD

**Issue by ozbillwang** [kubecost/cost-analyzer-helm-chart#1156]
**What problem are you trying to solve?**

4 years old image is used in this chart

```
downloadDashboardsImage:
  repository: appropriate/curl
  tag: latest
  pullPolicy: IfNotPresent
```
the image's base image is alpine:3.7, its curl version is old as well, recommend to upgrade to 3.14 or 3.15, so we can use the latest version of curl as well.

![image](https://user-images.githubusercontent.com/8954908/144769492-ae96ce3f-ca4e-43a8-b36f-1213abd3956c.png)

its upstream repo is in achived (read-only) status.

![image](https://user-images.githubusercontent.com/8954908/144821254-e3726a38-3da9-4e5f-9cfd-43b92ec95174.png)

**Describe the solution you'd like**
Image is too old and not maintaince any more.

**Describe alternatives you've considered**

consider to switch to active project which keep updating the image. 

**How would users interact with this feature?**

gz#1115
