### ISSUE TITLE
Feature request - Customize Cluster Health Thresholds

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#1206]
**What problem are you trying to solve?**
Customization of the threshold for how alerts evaluate Cluster Health

**Describe the solution you'd like**
When setting the Cluster Health alert type, you can only customize the threshold for when the overall score changes. I want to be able to customize the values that trigger these alerts. For example, customizing the 80% value used for "Low Cluster CPU."

**Describe alternatives you've considered**
Currently, if you are running a cluster that is constantly above the threshold, you will get a lot of alerts. An alternative might be to filter the alerts after they've come from Kubecost but disabling the alerts altogether prevents alert messages from building up and is the likely alternative.

**How would users interact with this feature?**
More configuration options when configuring the alert YAML

```
        # Health Score Alert 
        - type: health              # Alerts when health score changes by a threshold
          window: 10m
          threshold: 5              # Send Alert if health scores changes by 5 or more
          configuration:
            lowCPU: .80
            ...
```

There should also be an option in the Alerts UI/UX to customize these thresholds.

gz#1247<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/1247'>Zendesk ticket #1247</a>)</i>

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-59) by [Unito](https://www.unito.io)
