### ISSUE TITLE
Make it easy to configure service discovery of prom scrapes to just the release namespace of Kubecost

### ISSUE THREAD

**Issue by AjayTripathy** [kubecost/cost-analyzer-helm-chart#1242]
**What problem are you trying to solve?**
Some users deploy multiple KSMs or other metric emitters that kubecost's prometheus scrapes. Let's create documentation or examples on how to configure it to just kubecost's namespaces

**Describe the solution you'd like**
The suggestion is to use optional namespace discovery to get the services:

```
# Optional namespace discovery. If omitted, all namespaces are used.
namespaces:
  own_namespace: <bool>
  names:
    [ - <string> ]
```

**Describe alternatives you've considered**
Hardcode the servicename to just KSM won't work since we want to scrape the network-cost daemonsets automatically

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-66) by [Unito](https://www.unito.io)
