### ISSUE TITLE
Garbage at the end of grafana ini file (broken datasource provisioning)

### ISSUE THREAD

**Issue by skillcoder** [kubecost/cost-analyzer-helm-chart#1270]
**Describe the bug**
This part of helm chart caused unexpected behaviour
https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/charts/grafana/templates/configmap.yaml#L23-L41

```
# k exec kubecost-grafana-6578775bc6-dmxsd -c grafana -it -- bash
$ cat /etc/grafana/grafana.ini
[analytics]
check_for_updates = true
[auth.anonymous]
enabled = true
org_name = Main Org.
org_role = Editor
[grafana_net]
url = https://grafana.net
[log]
mode = console
[paths]
data = /var/lib/grafana/data
logs = /var/log/grafana
plugins = /var/lib/grafana/plugins
provisioning = /etc/grafana/provisioning
[server]
root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana
- access: proxy
  isDefault: true
  name: Prometheus
  type: prometheus
  url: http://kubecost-prometheus-server.kubecost.svc
```

It is not suppose to be here:

```
- access: proxy
  isDefault: true
  name: Prometheus
  type: prometheus
  url: http://kubecost-prometheus-server.kubecost.svc
```

Part of grafana heml values file puts in /etc/grafana/grafana.ini if grafana.datasources are empty.
Seems this garbage in main configuration ini file may also cause to broke datasource provisioning.

**To Reproduce**

1. Just install kubecost from helm chart v1.90.1
1. Got to kubecost-grafana in grafana container and check /etc/grafana/grafana.ini
1. See garbage at the and on ini file.

**Expected behavior**
Do not put garbage at the end of grafana ini file
Let user to disable default datasource completely in favor of provisioning datasorces.

gz#1436

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-71) by [Unito](https://www.unito.io)

**Comment by kbrwn** [comment]
@skillcoder Thanks for reporting this and providing a workaround. We will work on getting this fixed.

**Comment by michaelmdresser** [comment]
Hi @skillcoder, are you experiencing an error when accessing grafana because of what you've described in this report? It will help us prioritize this behavior.

## My repro steps so far

Here's a basic setup for reproducing the behavior described in the issue. I'm currently having some trouble with my dev environment that is preventing me from getting an install going to see if an error is occurring.

### Templating on 1.90.1

```bash
helm template \
    'kubecost/cost-analyzer' \
    --version '1.90.1' \
    -s 'charts/grafana/templates/configmap.yaml'
```

```yaml
---
# Source: cost-analyzer/charts/grafana/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: RELEASE-NAME-grafana
  labels:
    app: grafana
    chart: grafana-1.17.2
    release: RELEASE-NAME
    heritage: Helm
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [auth.anonymous]
    enabled = true
    org_name = Main Org.
    org_role = Editor
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/data
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [server]
    root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana
    - access: proxy
      isDefault: true
      name: Prometheus
      type: prometheus
      url: http://RELEASE-NAME-prometheus-server.default.svc
```

### Templating on 1.90.1 with @skillcoder's workaround

```bash
helm template \
    'kubecost/cost-analyzer' \
    --version '1.90.1' \
    -s 'charts/grafana/templates/configmap.yaml' \
    -f - <<EOF
grafana:
  sidecar:
    datasources:
      enabled: false
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: prometheus-kubecost
          type: prometheus
          url: http://kubecost-prometheus-server.kubecost.svc.cluster.local
          access: proxy
          isDefault: false
EOF
```

```yaml
---
# Source: cost-analyzer/charts/grafana/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: RELEASE-NAME-grafana
  labels:
    app: grafana
    chart: grafana-1.17.2
    release: RELEASE-NAME
    heritage: Helm
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [auth.anonymous]
    enabled = true
    org_name = Main Org.
    org_role = Editor
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/data
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [server]
    root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - access: proxy
      isDefault: false
      name: prometheus-kubecost
      type: prometheus
      url: http://kubecost-prometheus-server.kubecost.svc.cluster.local
    - access: proxy
      isDefault: true
      name: Prometheus
      type: prometheus
      url: http://RELEASE-NAME-prometheus-server.default.svc

```
