### ISSUE TITLE
Allow users to customize Thanos deployment strategy types

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#1328]
**What problem are you trying to solve?**
On specific clusters, a RollingUpdate deployment strategy does not work for Thanos. 

**Describe the solution you'd like**
I want a way to customize this value to better support these clusters.

**Describe alternatives you've considered**
Right now, you can manually delete the deployment and then run the upgrade.

**How would users interact with this feature?**
Customizing the values:
```yaml
thanos:
  store:
    deploymentStrategy: Recreate
  query:
    deploymentStrategy: Recreate
  query-frontend:
    deploymentStrategy: Recreate
  compact:
    deploymentStrategy: Recreate
```

gz#1576<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/1576'>Zendesk ticket #1576</a>)</i>
