### ISSUE TITLE
Better support for air-gapped environments

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#1356]
**What problem are you trying to solve?**
Currently, there are options to customize all of the images pulled via the chart; however, this can be tedious, and not all of them provide the best options. Most will give a configuration option similar to this... https://github.com/kubecost/cost-analyzer-helm-chart/blob/c98f4856bc96d50c5a8a775547ac8ce539e7037b/cost-analyzer/values.yaml#L188-L189

However, some options hard-code the image tag... https://github.com/kubecost/cost-analyzer-helm-chart/blob/036171b35a04c5e534643330d030bb971646d866/cost-analyzer/charts/grafana/values.yaml#L257-L258

While the Thanos sidecar doesn't provide any easy way to customize without manually updating the values.yaml... https://github.com/kubecost/cost-analyzer-helm-chart/blob/036171b35a04c5e534643330d030bb971646d866/cost-analyzer/values-thanos.yaml#L30-L31

**Describe the solution you'd like**
All images should be customizable with a hard-coded repository while not modifying the image tag. This way, air-gapped users can provide a custom repository and expect version upgrades to happen as they would if they were not air-gapped. Afterward, it might also be helpful to give a top-level Docker registry so that users don't have to modify each field individually.

**Describe alternatives you've considered**
Manually modifying the values.yaml on every upgrade

**How would users interact with this feature?**
`.values.airGappedRegistry: custom-docker-repo.xyz` that sets the docker repository for every image pulled by the chart.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-83) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
@keithhand awesome report, thanks for sharing! Is it fair to generalize this and say this applies to all custom image repos? I've seen certain users require even we not airgapped. 

Is there an intermediate step which is a sample values file? Seems like we could create that quickly and that it would be helpful. Let me know what you think.

**Comment by keithhand** [comment]
@dwbrown2 that sounds like a fair to generalize. Anyone trying to use custom repositories for their Docker images could utilize this better. I made a sample file here:

```yaml
kubecostModel:
  image: custom-docker-repo.xyz/cost-model
kubecostFrontend:
  image: custom-docker-repo.xyz/kubecost/frontend
kubecost:
  image: custom-docker-repo.xyzkubecost/server
grafana:
  image:
    repository: custom-docker-repo.xyz/grafana
  sidecar:
    image: custom-docker-repo.xyz/k8s-sidecar:1.15.4
prometheus:
  server:
    image:
      repository: custom-docker-repo.xyz/prometheus
  alertmanager:
    image:
      repository: custom-docker-repo.xyz/prometheus
  pushgateway:
    image:
      repository: custom-docker-repo.xyz/prometheus
  configmapReload:
    prometheus:
      image:
        repository: custom-docker-repo.xyz/configmap-reload
  kube-state-metrics:
    image:
      repository: custom-docker-repo.xyz/kube-state-metrics
  nodeExporter:
    image:
      repository: custom-docker-repo.xyz/node-exporter
thanos:
  image:
    repository: custom-docker-repo.xyz/thanos
```

Good to note that `grafana.sidecar.image` still needs to have the tag manually updated. Also, because of the Thanos sidecar implementation, I can't seem to get that specific value to override via the values.yaml file. Using `--set prometheus.server.sidecarContainers[0].image=custom-docker-repo.xyz/thanos:v0.24.0` works and I found this [SO comment](https://stackoverflow.com/a/63834059) which suggests that using one as the first index in the values should work, but it doesn't seem to template correctly for me.

**Comment by dwbrown2** [comment]
I feel like this is a great start. What do you think about referencing a sample values file from our docs site? https://guide.kubecost.com/hc/en-us/articles/4407601795863-Installing-in-Air-gapped-Environments

We may consider marking each as required vs optional?

cc @AjayTripathy about further helm chart changes

**Comment by jessegoodier** [comment]
We have this, which has worked for some customers. We should link to it after we do some more validation.
https://github.com/kubecost/poc-common-configurations/blob/main/private-registry-helm-values/values-private-container-registry.yaml

note the imageVersion line that is commented, probably should not be commented

**Comment by keithhand** [comment]
Recently I had this brought back up, specifically regarding upgrading air-gapped environments and the dependencies that come with them. Some dependency charts (NetworkCosts and ClusterController were directly mentioned) only set the `image` value, making it difficult to ensure those components get upgraded per version.

```
networkCosts:
  image: image: gcr.io/kubecost1/kubecost-network-costs:v0.16.6
clusterController:
  image: gcr.io/kubecost1/cluster-controller:v0.6.2
```

requires more manual work (need to watch for the parent chart to upgrade these versions) and is much harder to maintain than:

```
networkCosts:
  repo: gcr.io/kubecost1/kubecost-network-costs
  #tag: v0.16.6
clusterController:
  repo: gcr.io/kubecost1/cluster-controller
  #tag: v0.6.2
```

Important to also note that if this is updated, we need to maintain backward compatibility for old users using the `${container}.image` tag. I believe using a different tag like `repo` might help here.

**Comment by abdennour** [comment]
or better like Bitnami Helm Charts:

```yaml
image:
   registry: some.registry.com
   repo: kubecost/frontend
   tag: v1.2.3
```
And better and better, use global registry variable:

```yaml
global:
  registry: some.registry.com
```
