### ISSUE TITLE
Nightly: refreshing allocations.html increases monthly cost (under certain conditions?)

### ISSUE THREAD

**Issue by michaelmdresser** [kubecost/cost-analyzer-helm-chart#1391]
**Describe the bug**

I have a cluster with namespace `over-request` which has two CronJobs in it [1]. I'm running nightly with the following images:

```
gcr.io/kubecost1/cost-model-nightly:CM-1ac8ea3_KCM-169f8d0 
gcr.io/kubecost1/frontend-nightly:f8f77df 
```

If relevant, this version of nightly is before https://github.com/kubecost/cost-model/pull/1179 has been approved/merged.

I have allocations.html loaded with the following settings:
<img width="317" alt="image" src="https://user-images.githubusercontent.com/17585786/165589350-c48c6888-f833-4648-ab0d-df66d87db8c7.png">

I see these costs:
<img width="924" alt="image" src="https://user-images.githubusercontent.com/17585786/165589409-203713ae-a00f-485a-b609-d4277401d765.png">

When I refresh the page, the costs go up:
<img width="906" alt="image" src="https://user-images.githubusercontent.com/17585786/165589478-e9c0dec7-68fd-4f60-9606-e38b455c9d52.png">

If I refresh the page again, they go up again:
<img width="904" alt="image" src="https://user-images.githubusercontent.com/17585786/165589520-971c044f-4e57-4ec0-ad11-0c7ab3ebcfeb.png">

After some duration, the costs go back down when I refresh again. @mbolt35 and/or @nikovacevic this looks sort of like a caching situation, could it be related to your recent work? 

I see some of this log:
```
I0427 17:58:13.115517       1 log.go:32] [Warning] SummaryAllocation: detected invalid sharing coefficient for cluster-one/gke-michael-dev-pool-5-1acb2061-mv8q/over-request/cpu-request-every-other-hour-27517920-vzsd4/hello: 0
```

### 1: CronJobs in cluster

```yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cpu-request-every-other-hour
  namespace: over-request
spec:
  schedule: "0 */2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; sleep 60m
            resources:
              requests:
                cpu: 1000m
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cpu-request-hourly-overlapping
  namespace: over-request
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; sleep 90m
            resources:
              requests:
                cpu: 1000m
          restartPolicy: OnFailure
```

**To Reproduce**
See CronJobs and image version.

**Expected behavior**
Total cost stays the same on refresh.

**Screenshots**
Shown earlier.
