### ISSUE TITLE
Add ability to customize the pod security context and use readOnlyRootFilesystem

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#1403]
**What problem are you trying to solve?**
After patching the cost-analyzer pod's security context to have the value `readOnlyRootFilesystem: true`, the `cost-analyzer-frontend` pod will fail with the following error:

```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: can not modify /etc/nginx/conf.d/default.conf (read-only file system?)
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2022/05/03 14:18:54 [warn] 1#1: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:2
nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:2
2022/05/03 14:18:54 [emerg] 1#1: mkdir() "/var/cache/nginx/client_temp" failed (30: Read-only file system)
```

**Describe the solution you'd like**
Successful deployment with a custom security context. It would also be nice to modify this value via the helm chart, rather than patching the deployment.

**Describe alternatives you've considered**
Use the default securityContext options supplied with the chart.

**How would users interact with this feature?**

```yaml
securityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  runAsUser: 1001
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
```

gz#1760<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/1760'>Zendesk ticket #1760</a>)</i>

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-92) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
@AjayTripathy would you be able to add initial review?

**Comment by AjayTripathy** [comment]
@keithhand happy to take a look, were you able to repro this?

**Comment by keithhand** [comment]
@AjayTripathy, yes, I was. I had to patch the `kubecost-cost-analyzer` deployment manually with these security context options attached at the container level.

**Comment by keithhand** [comment]
@AjayTripathy, I was able to reproduce the main issue (readOnlyFileSystem breaks) using this yaml patch file...

```yaml
spec:
  template:
    spec:
      containers:
        - name: cost-analyzer-frontend
          securityContext:
            readOnlyRootFilesystem: true
        - name: cost-model
          securityContext:
            readOnlyRootFilesystem: true
```

... followed by this command `kubectl patch deploy/kubecost-cost-analyzer -n kubecost --patch-file securityContext.yaml`.
