### ISSUE TITLE
Azure cloud integration config ignores kubecostProductConfigs

### ISSUE THREAD

**Issue by doonto** [kubecost/cost-analyzer-helm-chart#1430]
**Describe the bug**
Azure cloud integration config ignores the helm values under kubecostProductConfigs.
Discussion and details are also available in https://kubecost.slack.com/archives/CLFV60Y90/p1652801061615549

**To Reproduce**
Install kubecost 1.90 (to see the azure config in the frontend) or 1.93.1 (latest at the moment), follow https://guide.kubecost.com/hc/en-us/articles/4407595934871-Azure-Config. I tried on both versions.

```
#setup your variables in the azure libraries before, use exact names, as in the helm step
variables:
  - group: azure-kubecost

####
                    - task: HelmDeploy@0
                      displayName: Helm upgrade install
                      inputs:
                        connectionType: Azure Resource Manager
                        azureSubscriptionEndpoint: platform-${{ variables.spokeName }}-kubernetes
                        azureResourceGroup: platform-${{ variables.spokeName }}-aks-rg
                        kubernetesCluster: mcs-${{ variables.spokeName }}-aks
                        namespace: ${{ variables.kubernetesNamespace }}
                        command: upgrade
                        useClusterAdmin: true
                        waitForExecution: false
                        chartName: ${{ variables.chartDir }}
                        releaseName: kubecost
                        arguments: -i --create-namespace -f ${{ variables.valuesDir }}/values.yaml -f ${{ variables.valuesDir }}/${{ variables.spokeName }}-values.yaml --set azureStorageAccessKey=$(azureStorageAccessKey) --set kubecostProductConfigs.azureSubscriptionID=22222222-2222-2222-2222-2222222222 --set kubecostProductConfigs.azureClientID=11111111-1111-1111-1111-111111111111 --set kubecostProductConfigs.azureTenantID=00000000-0000-0000-0000-000000000000  --set kubecostProductConfigs.azureClientPassword=$(azServiceKeyPassword) --set kubecostProductConfigs.createServiceKeySecret=true

```

**Expected behavior**
Kubecost reads the helm values and configures Azure integration attributes. In reality is ignores the azure integration attributes fron the helm values.yaml

**Screenshots**
![image](https://user-images.githubusercontent.com/32912561/169264669-729eb9e9-9482-4fab-99a7-01dcf47ffeaf.png)
![image](https://user-images.githubusercontent.com/32912561/169264712-77bfcfa4-7c24-4c7b-bb72-696f03274cca.png)

**Collect logs (please complete the following information):**

 - Run `helm ls` and paste the output here:
```
 helm ls -n kubecost
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
kubecost        kubecost        18              2022-05-19 09:25:40.148755546 +0000 UTC deployed        kubecost-1.0.0
```

 - Run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-analyzer-server` and paste the output here:
2022/05/19 09:27:04 Thanos is disabled for the API endpoints.
2022/05/19 09:27:04 Server is ready.
(For the 1.9.0 version)
 - Run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-model` and paste the output here:
 - Run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-analyzer-frontend` and paste the output here:

[kubecost-cost-analyzer-7cb8b6dd7c-wm2f6.log](https://github.com/kubecost/cost-analyzer-helm-chart/files/8727994/kubecost-cost-analyzer-7cb8b6dd7c-wm2f6.log)
[kubecost-cost-analyzer-frontend-7cb8b6dd7c-wm2f6.log](https://github.com/kubecost/cost-analyzer-helm-chart/files/8727997/kubecost-cost-analyzer-frontend-7cb8b6dd7c-wm2f6.log)

The bug report:
[kubecost-bug-report-1652884064842.txt](https://github.com/kubecost/cost-analyzer-helm-chart/files/8728010/kubecost-bug-report-1652884064842.txt)

gz#1845<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/1845'>Zendesk ticket #1845</a>)</i>
