### ISSUE TITLE
Problems to connect the kube-prometheus stack and kubecost

### ISSUE THREAD

**Issue by junoriosity** [kubecost/cost-analyzer-helm-chart#1510]
I was trying to connect kubecost with my own kube-prometheus stack like [here](https://guide.kubecost.com/hc/en-us/articles/4407595941015-Custom-Prometheus).

I did the following in terraform 

```

resource "helm_release" "prometheus" {
  name             = "prometheus"
  namespace        = "monitoring"
  create_namespace = true
  repository       = "https://prometheus-community.github.io/helm-charts"
  chart            = "kube-prometheus-stack"

  version = "36.2.0"

  values = [
    "${file("${path.module}/yaml_files/kube_prometheus/additional_config.yaml")}"
  ]
}


resource "helm_release" "kubecost" {
  name = "kubecost"
  namespace = "kubecost"
  create_namespace = true
  repository = "https://kubecost.github.io/cost-analyzer"
  chart = "cost-analyzer"

  version = "1.94.3"

  set {
    name = "global.prometheus.enabled"
    value = false
  }

  set {
    name = "global.prometheus.fqdn"
    value = "http://prometheus-kube-prometheus-prometheus.monitoring.svc"
  }

  depends_on = [ helm_release.prometheus ]
}
```

where the `additional_config.yaml` is 

```
prometheus:
  prometheusSpec:
    additionalScrapeConfigs: |
      - job_name: kubecost
        honor_labels: true
        scrape_interval: 1m
        scrape_timeout: 10s
        metrics_path: /metrics
        scheme: http
        dns_sd_configs:
        - names:
          - kubecost-cost-analyzer.kubecost.svc
          type: 'A'
          port: 9003
```

Now I can see the target in Prometheus as in the aforementioned link.

However, when trying to reach the frontend of kubecost via port-forward I obtain

<img width="773" alt="kubecost_connect" src="https://user-images.githubusercontent.com/5286536/176787202-45171694-3d86-4f53-9a09-9cdf40964cd4.png">

Do you know what I have to do to fix it? I also tried "http://prometheus-kube-prometheus-prometheus.monitoring.svc:9090" as kubecost helm parameter, but with the same result.

gz#2077<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2077'>Zendesk ticket #2077</a>)</i>
