### ISSUE TITLE
401 error cause basic auth popup to show multiple times

### ISSUE THREAD

**Issue by marco-giovannini-73team** [kubecost/cost-analyzer-helm-chart#1515]
**Describe the bug**

I am using gcr.io/kubecost1/cost-model:prod-1.94.3

When using an nginx ingress with basic authentication and a different path then the / to expose kubecost authentication popup keep showing.

**To Reproduce**

1. Expose Kubecost UI using an nginx ingress with basic authentication on a different path:

Example

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    kubernetes.io/ingress.class: xxx-nginx
    meta.helm.sh/release-name: logmon
    meta.helm.sh/release-namespace: xxx-logmon
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^(/kubecost)$ $1/ permanent;
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  labels:
    app: cost-analyzer
    app.kubernetes.io/instance: logmon
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cost-analyzer
    helm.sh/chart: cost-analyzer-1.94.3
  name: logmon-cost-analyzer
  namespace: xxx-logmon
spec:
  rules:
  - host: xxx.eastus.cloudapp.azure.com
    http:
      paths:
      - backend:
          service:
            name: logmon-cost-analyzer
            port:
              name: tcp-frontend
        path: /kubecost(/|$)(.*)
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - xxx.eastus.cloudapp.azure.com
    secretName: xxx-tls-secret
```

2. Login first time and navigate in another sections part of the applications. 
    The authentication popup will show over and over again.

**Expected behavior**
Login only once should be required

**Screenshots**

![Screenshot 2022-07-05 at 16 27 32](https://user-images.githubusercontent.com/95924236/177361404-a0b9af6d-f3b5-41a1-9d9b-664f13b721eb.png)

urls of favicon and azure_logo_square (in the diagnostic page) don't get rewritten properly causing 401 errors and causing the basic authentication popup again.

<img width="1210" alt="Screenshot 2022-07-05 at 14 48 09" src="https://user-images.githubusercontent.com/95924236/177361791-ab6fc932-51d8-4105-bcc8-1c2606603104.png">

![Screenshot 2022-07-05 at 16 45 40](https://user-images.githubusercontent.com/95924236/177362235-afa07901-744c-4e3d-96d5-4a5a8adbc41b.png)
![Screenshot 2022-07-05 at 16 46 11](https://user-images.githubusercontent.com/95924236/177362247-337ef236-eb2b-4e37-86d5-cc7671814983.png)

gz#2099<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2099'>Zendesk ticket #2099</a>)</i>
