### ISSUE TITLE
Enabled cluster controller generates duplicate app labels

### ISSUE THREAD

**Issue by mtb-xt** [kubecost/cost-analyzer-helm-chart#1542]
**Describe the bug**
If I enable cluster controller, helm will render it's resources with two 'app' labels, which make fluxcd error out (like in issues https://github.com/kubecost/cost-analyzer-helm-chart/issues/1322 and https://github.com/kubecost/cost-analyzer-helm-chart/issues/1150)

**To Reproduce**
1. Run `helm template test kubecost/cost-analyzer --set clusterController.enabled=true`
2. Inspect output and see duplicate labels:
```
# Source: cost-analyzer/templates/kubecost-cluster-controller-template.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-cluster-controller
  labels:
[...]
    app: cost-analyzer
    app: test-cluster-controller
```
4. See error in fluxcd:
```
 Message:               Helm install failed: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors:
  line 12: mapping key "app" already defined at line 11
```

**Expected behavior**
All labels should be unique

**Collect logs (please complete the following information):**
chart version 1.94.3

gz#2158<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2158'>Zendesk ticket #2158</a>)</i>
