### ISSUE TITLE
Disable Grafana by Default

### ISSUE THREAD

**Issue by teevans** [kubecost/cost-analyzer-helm-chart#1569]
Following up here on an email thread with AjayTripathy and nealormsbee.

Sounds like we're ready to make the switch to remove our shipped version of grafana by default. 

AjayTripathy / nealormsbee

* What are the steps to get this done? 

gz#2222<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2222'>Zendesk ticket #2222</a>)</i>

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-129) by [Unito](https://www.unito.io)

**Comment by nealormsbee** [comment]
@teevans I'll read through the Helm chart again to see if there are other considerations. Nominally, defaulting `grafana.enabled = false` in `values.yaml`.

That *might* be it, but there may be a little more. Broadcasting this change to users would also be good.

**Comment by dwbrown2** [comment]
@AjayTripathy can you share the broader gameplan here so we have context?

**Comment by AjayTripathy** [comment]
Note on implementation is you need to also set proxy=false

Here's my thoughts on broader plan. We should announce in patch notes that we're setting this to off but will continue to support byo grafana and community dashboards.  Then over the next few releases we should remove grafana entirely from our app and only support byo+an integration with our dashboards.

**Comment by LaikaN57** [comment]
Config snippet from a _mostly_ disabled `grafana` (for whatever it is worth in this discussion):

```yaml
# Configure how we interface with Grafana - we aren't running it ourselves in
# this stack, but instead we're leveraging the one in the observability
# platform.
grafana:
  # -- Create datasources in the [REDACTED] namespace
  namespace_datasources: [REDACTED]
  datasources:
    # -- No need to connect the datasources - its already setup to connect to Prometheus
    enabled: false
  sidecar:
    dashboards:
      enabled: false
    datasources:
      defaultDatasourceEnabled: false
global:
  # https://github.com/kubecost/docs/blob/master/custom-prom.md#custom-grafana
  #
  # Undocumented, but both "enabled" and "proxy" must be false in combination.
  grafana:
    # -- Disable management of our own internal Grafana service
    enabled: false
    # -- Disable creating the /grafana proxy url in the kubecost nginx
    # config, it must be disabled to tell Kubecost to use the grafanaURL we
    # give it.
    proxy: false
```
