### ISSUE TITLE
Cluster context switcher behavior on non-root cluster

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#1601]
**Describe the bug**
When you select a secondary cluster through the context switcher options and try to switch contexts again, the "0" cluster adjusts to the root and you lose the context options from the root. This can be confusing for users if they want to view multiple different clusters. For example, if you start at the Root cluster, and navigate to a secondary cluster, you need to return to the root cluster context to view any other context options. This can be more confusing if you set both clusters to have the cluster information, as the root cluster will appear as another option.

**To Reproduce**

1. Configure 2 clusters, each pointing to each other within the `kubecostProductConfigs.clusters[]` context.

`values-aws.yaml`

```yaml
kubecostProductConfigs:
  clusters:
    - name: "azure"
      address: "http://20.115.8.72:9090"
ingress:
  enabled: true
  hosts: ['']
```

`values-azure.yaml`

```yaml
kubecostProductConfigs:
  clusters:
    - name: "aws"
      address: "http://ae978d75d3497461d9b0b2768b0d8d7c-2094351192.us-west-2.elb.amazonaws.com"
service:
  type: "LoadBalancer"
```

1. Select "Switch context" on one of the clusters
1. See original cluster listed twice

**Expected behavior**
An easy way for users to swap between all of their configured contexts.

**Screenshots**
![image](https://user-images.githubusercontent.com/43491549/182265408-ce41bdd7-af16-49eb-82b8-8d0114566963.png)
![image](https://user-images.githubusercontent.com/43491549/182265423-49256ba3-6ff3-4806-934c-6d1612acff44.png)

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-145) by [Unito](https://www.unito.io)
