### ISSUE TITLE
Stuck with OIDC google auth (v1.98)

### ISSUE THREAD

**Issue by korjavin** [kubecost/cost-analyzer-helm-chart#1605]
Kubecost installed with official helm chart.

Values.yaml contains:

```
oidc:
  enabled: true
  clientID: " #real client id that works for another project
  clientSecret: "" # a real secret
  secretName: "kubecost-oidc-secret" # k8s secret where clientsecret will be stored   
  authURL: "https://accounts.google.com/o/oauth2/v2/auth" # endpoint for login to auth server-
  loginRedirectURL: "https://mydomain.com/model/oidc/authorize" # Kubecost url configured in provider for redirect after authentication
  discoveryURL: "https://accounts.google.com/.well-known/openid-configuration" # url for OIDC endpoint discovery
```

I checked that redirect URL included to “authorized” list on the Google site.

When I open kubecost front page I'm getting
```
Authorization Error
Error 400: invalid_request
Required parameter is missing: response_type
[Learn more](https://developers.google.com/identity/protocols/oauth2)
```

![image](https://user-images.githubusercontent.com/148765/182556862-539a3731-bd3d-440c-9c2b-3cc68fd4ba9a.png)

Is there anything I can do with this issue?

gz#2289<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2289'>Zendesk ticket #2289</a>)</i>

**Comment by Adam-Stack-PM** [comment]
@zorrobyte, Any update on this ticket? Is this a bug or support issue?

**Comment by kaelanspatel** [comment]
Hi @korjavin 

This should be made clearer, so we'll work on documentation here, but the AuthURL parameter in the helm chart needs to be the full URL required for login to the OIDC provider _including_ various query params (these are different based on which provider you use, and so are left user-configurable).

To resolve this specific error you'd need to specify at least:
```
 authURL:  "https://accounts.google.com/o/oauth2/v2/auth?response_type=code&client_id=<your client ID>"
```
On a cursory glance at [the docs](https://developers.google.com/identity/protocols/oauth2/web-server#sample-oauth-2.0-server-response) it looks like there may be more params required, so it may do to add these as well.

**Comment by korjavin** [comment]
It worked.

But how can I limit domain to mine.

**Comment by biancaburtoiu** [comment]
Hello @korjavin! Thanks for letting us know the `authURL` worked once you added the additional params. 

Could you explain a bit more what you are trying to achieve by limiting the domain?

**Comment by korjavin** [comment]
Interesting question.

I don't think that EVERYONE with google account should have access to my kubecost installation.

**Comment by korjavin** [comment]
Well, I don't think so. As far as I understand there is nothing I can configure with google about it.

What i've seen before, let's say for flask apps, looks like:
```
                "client_id": "5........7.apps.googleusercontent.com",
                "client_secret": os.environ.get("GOOGLE_SECRET"),
                "api_base_url": "https://www.googleapis.com/oauth2/v2/",
                "client_kwargs": {"scope": "email profile"},
                "request_token_url": None,
                "access_token_url": "https://accounts.google.com/o/oauth2/token",
                "authorize_url": "https://accounts.google.com/o/oauth2/auth",
                "authorize_params": {"hd": "mydomain.tld"}
            }
```
Where hd is some params of filtering.

There is more info: https://developers.google.com/identity/protocols/oauth2/openid-connect#hd-param

but, even there it says, app should check if domain fits the filter.

**Comment by kaelanspatel** [comment]
Hi @korjavin 

Looking into this, it appears you're right about the hd param. We'll look into it.

Unfortunately, as of now, Kubecost does not support this method. It expects authentication to be handled by the server. If Google's OAuth2 server authenticates every google user, then that's who will have access.

**Comment by sundeepghuman** [comment]
@korjavin are you indicating that in our current implementation, users from different Google domains are able to access your application?

**Comment by korjavin** [comment]
Yes

**Comment by AjayTripathy** [comment]
Thanks @korjavin . We'll expect to have a solution here in our v1.98 release.

**Comment by Adam-Stack-PM** [comment]
Fixed in v1.98

**Comment by yossicohn** [comment]
> Kubecost installed with official helm chart.
> 
> Values.yaml contains:
> 
> ```
> oidc:
>   enabled: true
>   clientID: " #real client id that works for another project
>   clientSecret: "" # a real secret
>   secretName: "kubecost-oidc-secret" # k8s secret where clientsecret will be stored   
>   authURL: "https://accounts.google.com/o/oauth2/v2/auth" # endpoint for login to auth server-
>   loginRedirectURL: "https://mydomain.com/model/oidc/authorize" # Kubecost url configured in provider for redirect after authentication
>   discoveryURL: "https://accounts.google.com/.well-known/openid-configuration" # url for OIDC endpoint discovery
> ```
> 
> I checked that redirect URL included to “authorized” list on the Google site.
> 
> When I open kubecost front page I'm getting
> 
> ```
> Authorization Error
> Error 400: invalid_request
> Required parameter is missing: response_type
> [Learn more](https://developers.google.com/identity/protocols/oauth2)
> ```
> 
> ![image](https://user-images.githubusercontent.com/148765/182556862-539a3731-bd3d-440c-9c2b-3cc68fd4ba9a.png)
> 
> Is there anything I can do with this issue?
> 
> gz#2289(related to [Zendesk ticket #2289](https://kubecost.zendesk.com/agent/tickets/2289))

@korjavin I have the exact issue with the Google OIDC SSO authentication
I have a similar configuration.
I pass all the flow of authentication.
I see I get the code response back.
But still, when I get the reply with the code I get 500 HTTP responses from the kubecost cost-analyzer.
 "error": "invalid_client".
it seems that the header does not contain any token.

Do you have any idea?

```
  oidc:
    enabled: false
    clientID: "my-client-id" # application/client client_id parameter obtained from provider, used to make requests to server
    client_secret: "my-client-secret" # k8s secret where clientsecret will be stored
    authURL: "https://accounts.google.com/o/oauth2/v2/auth?response_type=code&client_id=my-client-id&scope=openid email&redirect_uri=https://my-kubecost.example.com/model/oidc/authorize&prompt=select_account"
    loginRedirectURL: "https://my-kubecost.example.com.com/model/oidc/authorize" # Kubecost url configured in provider for redirect after authentication
    discoveryURL: "https://accounts.google.com/.well-known/openid-configuration" # url for OIDC endpoint discovery
```
