### ISSUE TITLE
Annotations not showing up in aggregations but labels are

### ISSUE THREAD

**Issue by sumanmukherjee03** [kubecost/cost-analyzer-helm-chart#1644]
**Describe the bug**
Controller objects with annotations not showing up in aggregations in the UI but one that are labeled are showing up

**To Reproduce**
I am using chart version 1.96.0.
I have this relevant config in my kustomize `values.yaml`

```
kubecostMetrics:
  emitPodAnnotations: true
  emitNamespaceAnnotations: true
  emitKsmV1Metrics: true
  emitKsmV1MetricsOnly: false
  exporter:
    enabled: false

...

kubecostProductConfigs:
  currencyCode: "USD"
  labelMappingConfigs:
    enabled: true
    owner_label: "example_com_project"
    team_label: "example_com_service_owner"
    product_label: "app_kubernetes_io_name"
    owner_external_label: "example_com_project"
    team_external_label: "example_com_service_owner"
    product_external_label: "app_kubernetes_io_name"
```

I have some statefulsets with owner label `example.com/project` and some other statefulsets with annotations  `example.com/project`. The pods in the statefulsets are also labeled and annotated accordingly, because I am using `commonLabels` and `commonAnnotations` in kustomize.

In the UI when i select aggregation by "Owner", I was expecting to see all the statefulsets which are labeled as well as annotated. However, I am only seeing the ones with the label. The ones with annotation are not showing up in the aggregate. Same behavior when I use filter in the UI. Also, this seems to be the case for aggregations other than just owner, ie, same behavior for product etc.

**Expected behavior**
I was expecting to see all the statefulsets which are labeled as well as annotated with `example.com/project`

gz#2435<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2435'>Zendesk ticket #2435</a>)</i>
