### ISSUE TITLE
PV cost is being reported wrong

### ISSUE THREAD

**Issue by sumanmukherjee03** [kubecost/cost-analyzer-helm-chart#1647]
**Describe the bug**
We are using quite a few statefulsets in EKS which ultimately via the ebs csi driver tie back to EBS volumes. However, in the kubecost reporting the cumulative cost of the PVs in statefulset controller objects seem to be wrong. To be more precise they seem to be almost always half of what they should be.

For example if I have a gp3 EBS volume of 100Gi for a statefulset pod, in 24 hours I expect the number to be ((100 * 0.08)/31) = 0.26 . But the reported cumulative cost of the storage attached to the pod is 0.13.

We already have AWS CUR integration set up. When i lookup by the EBS volume ID in Kubecost Assets UI, i can see the PVC referencing the correct EBS volume ID. But the cost attribution is half of what it should be.

Our EBS volumes are usually tagged with these AWS tags by the ebs csi driver.
```
kubernetes.io/created-for/pvc/name | datadir-foo-primary-0
kubernetes.io/created-for/pv/name | pvc-e3468bc0-badd-4ceb-bb90-50017b17b53b
kubernetes.io/created-for/pvc/namespace | app-microservices
ebs.csi.aws.com/cluster | true
CSIVolumeName | pvc-e3468bc0-badd-4ceb-bb90-50017b17b53b
```

My initial thought was that may be I need to add some more tags to the EBS volume for kubecost to get the correct numbers. So, I added these extra tags to a few EBS volumes attached to the statefulsets via PVCs. But that did not make any difference. It has been more than 24 hours since I have added these new tags.
```
kubernetes.io/created-for/pvc/name | datadir-foo-primary-0
kubernetes_namespace | app-microservices
kubernetes_cluster | test3
example_com_project | foo
example_com_service_owner | foobar
kubernetes.io/created-for/pv/name | pvc-e3468bc0-badd-4ceb-bb90-50017b17b53b
kubernetes.io/created-for/pvc/namespace | app-microservices
ebs.csi.aws.com/cluster | true
CSIVolumeName | pvc-e3468bc0-badd-4ceb-bb90-50017b17b53b
kubernetes_controller | statefulset:foo-primary
app_kubernetes_io_name | foobarbaz
```

Relevant kustomize `values.yaml` sections
```
kubecostMetrics:
  emitPodAnnotations: true
  emitNamespaceAnnotations: true
  emitKsmV1Metrics: true
  emitKsmV1MetricsOnly: false
  exporter:
    enabled: false

...

kubecostProductConfigs:
  currencyCode: "USD"
  labelMappingConfigs:
    enabled: true
    owner_label: "example_com_project"
    team_label: "example_com_service_owner"
    product_label: "app_kubernetes_io_name"
    owner_external_label: "example_com_project"
    team_external_label: "example_com_service_owner"
    product_external_label: "app_kubernetes_io_name"
  athenaBucketName: "s3://example-kubecost-athena-query-results"
  athenaDatabase: "athenacurcfn_example_kubecost_athena_cur"
  athenaProjectID: "<REDACTED>"
  athenaRegion: "us-west-1"
  athenaTable: "example_kubecost_athena_cur"
  masterPayerARN: "arn:aws:iam::<REDACTED>:role/kubecost-sub-account-role"
```

**Expected behavior**
The expectation is for kubecost to report the right number for PVCs

**Screenshots**
Screenshot of a statefulset
![Screen Shot 2022-08-19 at 11 15 08 AM](https://user-images.githubusercontent.com/90907/185682741-b284ce2e-be2d-494f-b6cd-7d3364f25330.png)

Screenshot of details of the statefulset pod
![Screen Shot 2022-08-19 at 11 14 51 AM](https://user-images.githubusercontent.com/90907/185682736-eea5dbe7-4c2b-4e45-a82f-af360b2de5c0.png)

Screenshot of PVC
![Screen Shot 2022-08-19 at 10 55 11 AM](https://user-images.githubusercontent.com/90907/185682718-1193fe5c-d2d9-4d5d-a7fa-406e3a55782a.png)

Screenshot of details of PVC. It seems like kubecost is unaware of the storage type of this volume.
![Screen Shot 2022-08-19 at 11 01 24 AM](https://user-images.githubusercontent.com/90907/185682730-3aac0ecc-5dba-48f7-bc5a-222580a1834e.png)

gz#2443<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2443'>Zendesk ticket #2443</a>)</i>
