### ISSUE TITLE
Link to Grafana is Not Working

### ISSUE THREAD

**Issue by dmitrii-didenko** [kubecost/cost-analyzer-helm-chart#1651]
**Describe the bug**
Links to Grafana is not available when using configuration with existing Grafana installation
<img width="772" alt="Screenshot 2022-08-22 at 11 40 03" src="https://user-images.githubusercontent.com/81171763/185878250-c90c9ba9-d477-4cc6-b099-5963098c7233.png">

Please note, everything was working fine in 1.94.3, the issue has started to be observed after 1.95.

**To Reproduce**
Deploy helm chart with the following config:
```yaml
readonly: true
global:
  prometheus:
    enabled: false
    fqdn: http://monitoring-prometheus-oper-prometheus.monitoring.svc:9090

  grafana:
    enabled: false
    proxy: false

grafana:
  sidecar:
    dashboards:
      enabled: false
    datasources:
      enabled: false

prometheus:
  nodeExporter:
    enabled: false
  kubeStateMetrics:
    enabled: false

persistentVolume:
  size: 1M
  storageClass: efs-operations-dynamic

# Kubecost settings
kubecostProductConfigs:
  clusterName: "[OUR CLUSTER NAME]"
  grafanaURL: "[URL FOR EXISTING GRAFANA]"
```

**Expected behavior**
Link to grafana should be working fine

As far as I understand, since 1.95 the new frontend was introduced. Should the helm config be change somehow to get links working as it was in 1.94.3?
