### ISSUE TITLE
Confusing custom label configuration

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#1665]
**Describe the bug**
When using custom aggregations (Product, Environment, Department), if you refer to a label containing a character Prometheus doesn't like ([more info](https://guide.kubecost.com/hc/en-us/articles/4407595916823-Allocation-API#allocation-schema-version-1-76)), the aggregation looks like it works, however, drilling down will fail. You can get around this by manually converting the label to use `_` characters.

**To Reproduce**
1. Configure Kubecost with the custom owner/team labels
```yaml
## Test label
global:
  additionalLabels: 
    kubecost.com/test-label: test-four # product

## Label configs
kubecostProductConfigs:
  labelMappingConfigs:
    enabled: true
    owner_label: "kubecost.com/test-label"
    team_label: "kubecost_com_test_label" # workaround
```
2. Check allocation report based on owner aggregation

![not-working-owner](https://user-images.githubusercontent.com/43491549/186783120-516f9d96-62a3-466b-877a-25a6fef341a4.gif)

**Expected behavior**
![working-team](https://user-images.githubusercontent.com/43491549/186783647-5e772a1a-d533-4a4e-9ba9-970c8a402653.gif)

gz#2461<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2461'>Zendesk ticket #2461</a>)</i>
