### ISSUE TITLE
Bug: discrepancy between PV amounts on AggCM API and Allocation API

### ISSUE THREAD

**Issue by praveenkumar0566** [kubecost/cost-analyzer-helm-chart#1690]
Thanks for your interest in Kubecost!  To ensure you get the help you need, please follow these guidelines:

- If you have questions about product functionality/usage or need assistance with product installation/configuration, please email support@kubecost.com, where our support engineering team will be happy to help!
- If you have a reproducible bug or a feature request, you're in the right place.  Please include the information requested below.

---
# For reproducible bugs, please provide the following

**Describe the bug**  

The old API comes with one GB (which is PVC) (which must be multiplied by 24 for a day) and the new API with 240 GB (a pod of one GB, scale of 10 and 24 hours)
There is some difference between 24 GB and 240 GB, the old one does not include scale, and the new one does. but the physical consumption is only 1 GB (which must be multiplied by 24 for a day).

 There is a difference in result between the 2 API? 1 GB / 240 GB

The output in old API
 **"ramEfficiency": 2,
  pvAllocationAverage": 2.5813333333333317,**

Output in New API
   **"pvBytes": 22548578304.0,
      "pvByteHours": 22548578304.0,**

**To Reproduce**  

New API
/model/allocation?window=yesterday&aggregate=label:field_cattle_io_projectId&filterNamespaces=NAMESPACE

Old API
/model/aggregatedCostModel?window=yesterday&aggregation=label&aggregationSubfield=<SUB_FIELD>'

**Expected behavior**  
The new API should show the exact size of PVC in the new allocation API

**Screenshots**  
Customer ticket - https://kubecost.zendesk.com/agent/tickets/2493

**Comment by dwbrown2** [comment]
@nikovacevic may know more context here, but I'm not able to follow the current report. @praveenkumar0566 would you able to share more info on the issue and how to reproduce?

**Comment by praveenkumar0566** [comment]
@dwbrown2 I have updated the API, A customer is using it and seeing the difference. I spoke to Niko regarding this issue.

**Comment by nikovacevic** [comment]
My plan here is to try to repro by seeing if we have any envs where PV costs do not match between the two APIs. Even if we do, I'm not sure what I'd say, other than "Use the new API, do not use the old deprecated one," as I'm pretty sure we're not going to dig in and try to support the old API any more.

We could offer something like "use the ETL adapter" which should guarantee the numbers match... because they'll be coming from the old API and reformatting. Is that deceptive? Maybe.

**Comment by nikovacevic** [comment]
But also, not sure this is a great use of my time FWIW.

**Comment by dwbrown2** [comment]
What is the actual size of the PV? Isn't 22548578304.0 = 22 gb?

**Comment by praveenkumar0566** [comment]
This is the deployment file is trying in his test cluster with sample PV with 1GB with KC version 1.96

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-tst04
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /var/nfs/xxxx/eh/tst04
    server: 192.168.1.100

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pv-tst04
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
```

The PV values in the issue description are in his prod, We asked to upgrade KC to the latest version. He has installed KC with the latest version in his test cluster and deployed PV with the above sample file.

**Comment by dwbrown2** [comment]
@praveenkumar0566 are you saying that this is a 1gb PV and we think it's a 22gb PV in our current APIs? I've never seen this issue and this would be very surprising.

**Comment by praveenkumar0566** [comment]
Apologies if I have created any confusion here, The PV is 1GiB and the customer claims that there is a difference in displaying data for the Old API and the new API between pvAllocationAverage and pvBytes and pvBytesHours.
However, I worked with the customer and took statistics of allocation API and I didn't find any issues and reported them the same.
Waiting for their feedback.

**Comment by praveenkumar0566** [comment]
@dwbrown2 Customer is asking  the same deployment and extractions are taken right after each other. In the old api, there is one record of 1 GB, while in the new API there are 240 records of 1 GB.
I am aware that the new api is per hour, but there should probably only be 24 records of 1 GB

**Here is the old api** 
 curl -kLs 'http://cost012.sit.govcloud.dk/model/aggregatedCostModel?window=yesterday&offset=0h&aggregation=label&aggregationSubfield=field.cattle.io/projectId'
 
 **new api**
      curl -kLs 'http://cost012.sit.govcloud.dk/model/allocation?window=yesterday&aggregate=pod&filterNamespaces=cu2109-cl012-afregn

He is using below deployment file to test


```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-tst04
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /var/nfs/xxxx/eh/tst04
    server: 192.168.1.100

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pv-tst04
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
```
