### ISSUE TITLE
Add Email support to Kubecost and cluster health alerts

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#1704]
**What problem are you trying to solve?**
I want to use the Kubecost and Cluster Health alerts through a solution other than Slack.

**Describe the solution you'd like**
Extend the current email support to those alert types.

**Describe alternatives you've considered**
Add a custom email integration with Slack to send emails based on the alerts Kubecost sends.

**How would users interact with this feature?**
Same as the current workflow

```yaml
# Kubecost Health Diagnostic
- type: diagnostic
  window: 10m
  ownerContact:
    - test@example.com
  diagnostics: 
    prometheusUp: true
    cAdvisor: true
    ksm: true
    kubecost: true 
    nodeExporter: true
    scrapeInterval: true
    cpuThrottling: true
    clusterJoinLeave: true
```

![image](https://user-images.githubusercontent.com/43491549/191140524-5c9b9f6e-f8bb-4887-8ee5-8503ddd5aa63.png)

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-179) by [Unito](https://www.unito.io)
