### ISSUE TITLE
Cloud External Costs not working with s3 CUR integration

### ISSUE THREAD

**Issue by mmurph3** [kubecost/cost-analyzer-helm-chart#1719]
**Describe the bug**  
External cloud costs are not showing up in the UI for s3 CUR integration

**To Reproduce**  
I tried exactly as follows with an already existing athena-results-query s3 bucket. Bucket has resource ID's checked.

1. Created a secret named cloudinit for cloud-integration.json with following values:
```
{
    "aws": [
        {
    	    "serviceKeyName": "<obfuscated>",
            "serviceKeySecret":"<obfuscated>",
            "athenaBucketName": "s3://<obfuscated>-athena-query-results-<obfuscated>",
            "athenaRegion": "<obfuscated>",
            "projectID": "<obfuscated>",
            "masterPayerARN": ""
}


]
}
```
`kubectl create secret generic cloudint --from-file=cloud-integration.json -n kubecost`

`helm upgrade kubecost -i kubecost/cost-analyzer --namespace kubecost --set kubecostToken="<obfuscated>" \--set kubecostProductConfigs.cloudIntegrationSecret="cloudint"`

Did not work

2. I then tried another method, passing a values.yml:

I created svckey secret for the following values which I took from cloud-integration.json file above This user had correct s3 permissions get object, list, etc:
```
{
"aws_access_key_id": "<obfuscated>",
"aws_secret_access_key":"<obfuscated>",
}
```
Ref:
https://github.com/kubecost/cost-analyzer-helm-chart/blob/c03e140da6574e01c2e4657cf72ea2a91f640b50/cost-analyzer/values.yaml#L792

```
cat values.yml
kubecostProductConfigs:
  athenaProjectID: "<obfuscated>" # The AWS AccountID where the Athena CUR is. Generally your masterpayer account
  athenaBucketName: "s3://<obfuscated>-athena-query-results-<obfuscated>"
  athenaRegion: "<obfuscated>"
  serviceKeySecretName: "svckey"
```

Then i ran the following:
`helm upgrade -i kubecost kubecost/cost-analyzer --namespace kubecost --set kubecostToken="<obfuscated>" -f values.yml`

Seeing this in the log:
```
2022-09-29T20:39:20.727231033Z INF ETL: Asset[1d]: Reconciliation[]: Starting Pipeline
2022-09-29T20:39:20.72724459Z INF ETL: Asset[1d]: Reconciliation[<obfuscated_accountID>/s3://<obfuscated>-athena-query-results-<obfuscated>: Starting Pipeline
2022-09-29T20:39:20.727742699Z ERR ETL: Asset[1d]: Reconciliation[]: Run[NTCPl]: error: no config was provided
2022-09-29T20:39:20.727794983Z ERR ETL: Asset[1d]: Reconciliation[]: Run[NTCPl]: AssetSetRange is empty for [2022-09-14T00:00:00+0000, 2022-09-21T00:00:00+0000)
2022-09-29T20:39:20.727821976Z ERR ETL: Asset[1d]: Reconciliation[]: Run[NTCPl]: error: no config was provided
2022-09-29T20:39:20.727865406Z ERR ETL: Asset[1d]: Reconciliation[]: Run[NTCPl]: AssetSetRange is empty for [2022-09-21T00:00:00+0000, 2022-09-28T00:00:00+0000)
```

**Expected behavior**  
I expect to see external cloud costs from CUR in s3 bucket

**Screenshots**  
This is expected since these two athena database and athena table are to not be configured per the pdf (attached)
<img width="1189" alt="image" src="https://user-images.githubusercontent.com/36980248/193150631-19f68471-a796-4378-b69b-e4eb5ec551ad.png">

<img width="846" alt="image" src="https://user-images.githubusercontent.com/36980248/193150995-09488cf2-640c-4652-8f36-d7026135cdb5.png">

<img width="657" alt="image" src="https://user-images.githubusercontent.com/36980248/193151191-d07f0ee7-0aed-44aa-a578-aa00c3f70bb1.png">

<img width="1308" alt="image" src="https://user-images.githubusercontent.com/36980248/193151292-0e3b2d9b-9ca8-4d57-91c3-06d1d21bb1e0.png">

[AWS S3 CUR Integration.pdf](https://github.com/kubecost/cost-analyzer-helm-chart/files/9679373/AWS.S3.CUR.Integration.pdf)

**Comment by mmurph3** [comment]
I used the wrong bucket. Will test again and provide an update.

**Comment by AjayTripathy** [comment]
Please let me know!

**Comment by AjayTripathy** [comment]
@mmurph3 were you able to fix permissions here and get this working? If so can we make a change in the documentation?

**Comment by mmurph3** [comment]
Issue fixed, I was missing createServiceKeySecret. Will update documentation. This is the correct config:

```
NAME: kubecost
kubecostProductConfigs:
  athenaProjectID: "<obfuscated>"
  athenaBucketName: "csv-cur"
  athenaRegion: "<obfuscated>"
  awsServiceKeyName: "<obfuscated>"
  awsServiceKeyPassword: "<obfuscated>"
  projectID: "<obfuscated>"
  createServiceKeySecret: "true"
```
