### ISSUE TITLE
Saved reports created via values.yaml ignored if not persistent volume

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#1729]
**Describe the bug**  
When enabing saved reports via your values.yaml, if you also set `persistentVolume.enabled=false` the reports will not be created in the UI.

**To Reproduce**  
1. Upgrade application with the following values.yaml

```yaml
global:
  savedReports:
    enabled: true
    reports:
      - accumulate: false
        aggregateBy: namespace
        filters:
          - property: cluster
            value: cluster-one,cluster*
          - property: namespace
            value: kubecost
        idle: separate
        sharedNamespaces:
          - monitoring
          - kube-system
        title: Example Saved Report 0 tweak
        window: today
persistentVolume:
  enabled: false
```

2. Port-forward with `kubectl port-forward service/kubecost-cost-analyzer 9090` and visit http://localhost:9090/reports to see the missing report.
3. Enable persistenVolume for proof that the report is configured correctly.

```yaml
global:
  savedReports:
    enabled: true
    reports:
      - accumulate: false
        aggregateBy: namespace
        filters:
          - property: cluster
            value: cluster-one,cluster*
          - property: namespace
            value: kubecost
        idle: separate
        sharedNamespaces:
          - monitoring
          - kube-system
        title: Example Saved Report 0 tweak
        window: today
persistentVolume:
  enabled: true
```

**Expected behavior**  
Reports are created regardless of the persistentVolume status

**Screenshots**  
<img width="1504" alt="image" src="https://user-images.githubusercontent.com/43491549/194136096-455abae4-2990-450d-ba3d-dbcc07bf78f1.png">
