### ISSUE TITLE
Allow use of `config.prefix` in `kubecostModel.etlBucketConfigSecret` secret by bumping to Thanos 0.27

### ISSUE THREAD

**Issue by LaikaN57** [kubecost/cost-analyzer-helm-chart#1758]
**What problem are you trying to solve?**

I am trying to have multiple clusters backup ETL data to the same S3 bucket using `kubecostModel.etlBucketConfigSecret`. However when using a secret like this:

```yaml
apiVersion: v1
kind: Secret
type: Opaque
stringData:
  object-store.yaml: |
    type: S3
    config:
      bucket: "my-bucket"
      prefix: "my-prefix"
      endpoint: "s3.amazonaws.com"
      region: "us-east-1"
      insecure: false
      signature_version2: false
      put_user_metadata:
        "X-Amz-Acl": "bucket-owner-full-control"
```

I get the following warning:

```log
0000-00-00T22:57:58.831642422Z WRN ETL: failed to create bucket storage: create S3 client: yaml: unmarshal errors:
  line 4: field prefix not found in type storage.S3Config
```

However if we look at similar documenation to the [doc referenced](https://guide.kubecost.com/hc/en-us/articles/4407601811095-ETL-Backup#:~:text=This%20configuration%20secret%20follows%20the%20same%20layout%20documented%20for%20Thanos%20here%3A%20https%3A//thanos.io/v0.21/thanos/storage.md), in these [similar docs](https://github.com/thanos-io/objstore#s3:~:text=The%20field%20prefix,which%20blocks%20came) we can see that a `config.prefix` key is mentioned. (NOTE: I think the documentation actually has an error and the `prefix` key should be under the `config` key.)

**Describe the solution you'd like**

Extend the unmarshalling functionality for the `storage.S3Config` type to be able to handle the `config.prefix` key. This may be as simple as just updating a dependency to a newer version (not sure).

**Describe alternatives you've considered**

None.

**How would users interact with this feature?**

Users would be able to include a `config.prefix` key in their `kubecostModel.etlBucketConfigSecret` secret to be able to select a custom prefix inside of a custom bucket.
