### ISSUE TITLE
Issue with OIDC authorisation for Azure setup

### ISSUE THREAD

**Issue by Dima-Diachenko-work** [kubecost/cost-analyzer-helm-chart#1770]
**Describe the bug**  

I spent maybe 4 hours but did not configure the OIDC authorization for Azure setup.
I found [this feature request ](https://github.com/kubecost/cost-analyzer-helm-chart/issues/1371) and it still is open. 
But also in the default values you have the OIDC section:
https://github.com/kubecost/cost-analyzer-helm-chart/blob/56b880ce2bd4c2092648a446ff6110c02ccf0592/cost-analyzer/values.yaml#L194
***Can I ask if it works for Azure?*** Did you had a chance to test it?

**To Reproduce**  

My config (I replaced sensitive info of course):
```
oidc:
  enabled: true
  clientID: "c8f8112c-2ee4-***************"
  clientSecret: "***************"
  secretName: "kubecost-oidc-secret"
  authURL: "https://login.microsoftonline.com/*********************/oauth2/authorize"
  loginRedirectURL: "https://kubecost-dev.emergemarket.dev/model/oidc/authorize"
  discoveryURL: "https://login.microsoftonline.com/***************************/v2.0/.well-known/openid-configuration"
```
Full config file - [values.yaml.txt](https://github.com/kubecost/cost-analyzer-helm-chart/files/9904940/values.yaml.txt)

**Expected behavior**  

I was supposed to log in using Azure authorization. This config works well for my other solutions (Hashicorp Vault, ArgoCD and etc - all self-hosted and all work correctly with OIDC). 

**Screenshots**  

But for Cost-analyzer I have got the next error:
<img width="715" alt="Screenshot 2022-10-31 at 11 59 15" src="https://user-images.githubusercontent.com/104848965/199108010-32bbb936-c258-4038-9c04-9518de6d931c.png">
The same result is for: 
- DNS with routing (outside) through Istio gateway + virtual service 
- With using local kubectl port-forward.

**Collect logs (please complete the following information):**

I deployed `cost-analyzer` Helm chart version `1.97.0`, installed via ArgoCD.
Nothing special was added to the config (see config file above), almost the default setup. 
Logs from `cost-analyzer-frontend` pod:
```
10.11.31.34 - - [28/Oct/2022:11:23:16 +0000] "GET / HTTP/1.1" 303 114 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" "176.37.60.245,10.11.14.4"
10.11.9.236 - - [28/Oct/2022:11:33:21 +0000] "GET / HTTP/1.1" 303 114 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" "176.37.60.245,10.11.36.170"
10.11.17.121 - - [28/Oct/2022:11:39:26 +0000] "GET / HTTP/1.1" 303 114 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" "212.59.67.196,10.11.20.119"
127.0.0.1 - - [31/Oct/2022:09:59:00 +0000] "GET / HTTP/1.1" 303 114 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" "-"
127.0.0.1 - - [31/Oct/2022:20:55:24 +0000] "GET / HTTP/1.1" 303 114 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" "-"
127.0.0.1 - - [31/Oct/2022:20:56:41 +0000] "GET / HTTP/1.1" 303 114 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" "-"
```

**What problem are you trying to solve?**  

I can swear I tried all combinations of configs for OIDC:
-  v1 and v2 API versions
- change endpoints 
- try different variants of how to declare `authURL` and `loginRedirectURL` + change authentication config for Azure Application (aka Service Principal)

**Describe the solution you'd like**  

Help me please, how to make it works? I don't have any more ideas what to do with it.
