### ISSUE TITLE
Add the ability to set request-sizing profile default values in the helm chart

### ISSUE THREAD

**Issue by jcharcalla** [kubecost/cost-analyzer-helm-chart#1785]
**What problem are you trying to solve?**
This request came from speaking with a customer. While we have added a ["custom"](https://github.com/kubecost/cost-analyzer-frontend/pull/906) profile which allows users to create a custom CPU and Mem range, they would like the ability to set the defaults for the `high-availability`, `production`, and `development` profiles. Preferably this would be done via helm values.

Screenshot of the `request-sizing` page for context.
![](https://user-images.githubusercontent.com/17748044/200010309-37e2bb0c-74a2-4a8c-9213-3834610374b9.png)

**Describe the solution you'd like**
These profiles are currently hardcoded [here](https://github.com/kubecost/cost-analyzer-frontend/blob/v1.98.0/src/pages/RequestSizing/profiles.ts). The desired solution would be to set these via the helm [values.yaml](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/values.yaml) similar to this. (Note: might need to set the `p` value as well.)

```
requestSizing:
  profile:
    highAvailibility:
      cpu: “0.5”
      ram: “0.5”
    production:
      cpu: “0.65”
      ram: “0.65”
    development:
      cpu: “0.8”
      ram: “0.8”
```

Additionally this could add the ability to define additional customized profiles. It may also be worth adding similar functionality to the `cluster-sizing` page.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-208) by [Unito](https://www.unito.io)
