### ISSUE TITLE
Transition to new configs for Azure Cloud Billing Integration

### ISSUE THREAD

**Issue by thomasvn** [kubecost/cost-analyzer-helm-chart#1854]
## What problem are you trying to solve?

This is a follow-up of the below issue:

- https://github.com/kubecost/cost-analyzer-helm-chart/issues/1430

I would like to finish transitioning this repo’s usage of these old helm configs:

```yaml
kubecostProductConfigs:
  # Option 1 (this was previously already deprecated)
  azureStorageAccount: <STORAGE_ACCOUNT_NAME>
  azureStorageAccessKey: <STORE_ACCESS_KEY>
  azureStorageContainer: <REPORT_CONTAINER_NAME>
  azureStorageCreateSecret: true

  # Option 2 (this needs to be deprecated)
  azureStorageSecretName: "azure-storage-config" # Name of Kubernetes Secret where Azure Storage Configuration is stored
```

To the new multi-cloud helm configs:

```yaml
kubecostProductConfigs:
  cloudIntegrationSecret: "cloud-integration"
```

For additional context, this was already partially deprecated in [PR #1161](https://github.com/kubecost/cost-analyzer-helm-chart/pull/1161). Additionally, [here is an old commit of the Azure Cloud Integration doc](https://github.com/kubecost/docs/blob/5f623882a434bf770658c483732df76756f241e2/azure-out-of-cluster.md) describing how to set up the old configs.

## Describe the solution you'd like

- Deprecate the old configs from all example `values.yaml` filess
- Deprecate the Helm templates which implement these configs. Do research to ensure this would not be a breaking change for users who are potentially still leveraging the old config then upgrading to the new Helm chart.
- When safe, deprecate the corresponding backend code in kubecost’s cost-model container image. If not fully deprecating this code, at least fix the cost-model errors being thrown about `/var/configs/azure-storage-config.json file missing`, even though the user has set up cloud integration via `cloud-integration.json`.

## Describe alternatives you've considered

None

## How would users interact with this feature?

Users who are setting up their Azure Cloud Integration should be presented solely with information on how to set this value `.Values.kubecostProductConfigs.cloudIntegrationSecret`.
