### ISSUE TITLE
Cluster Nodes and Pods count wrong on Main Page

### ISSUE THREAD

**Issue by roee-landesman** [kubecost/cost-analyzer-helm-chart#1878]
**Describe the bug**  
The main screen is showing an incorrect node and pod count.

<img width="684" alt="Screenshot 2022-12-14 at 1 41 35 PM" src="https://user-images.githubusercontent.com/100310202/207725694-0d763752-4003-455d-8e0b-ed58105441c6.png">

<img width="715" alt="Screenshot 2022-12-14 at 1 41 27 PM" src="https://user-images.githubusercontent.com/100310202/207725702-726df000-9df0-4434-8913-cecaa10f8187.png">

(Blurred out sensitive information, but you can see that the pod count in my cluster does not equal the pod count in the `Cluster breakdown` section of the main page).

**To Reproduce**  

```yaml
    kubecostFrontend:
      image: public.ecr.aws/kubecost/frontend
    kubecostModel:
      image: public.ecr.aws/kubecost/cost-model
      warmCache: true
      warmSavingsCache: true
      etl: true
      etlStoreDurationDays: 120
      maxQueryConcurrency: 5
      resources:
        requests:
          cpu: "200m"
          memory: "55Mi"
    kubecostProductConfigs:
      athenaProjectID: "${local.environments[var.environment].aws-account-number}"
      athenaBucketName: s3://aws-athena-query-results-${lower(local.environments[var.environment].cluster_name)}/
      athenaRegion: ${local.environments[var.environment].region}
      athenaDatabase: athenacurcfn_opencost_daily_report_${var.environment}
      athenaTable: opencost_daily_report_${var.environment}
      awsSpotDataRegion: ${local.environments[var.environment].region}
      awsSpotDataBucket: spot-feed-bucket-${var.environment}
      projectID: "${local.environments[var.environment].aws-account-number}"
      spotLabel: node.kubernetes.io/lifecycle
      spotLabelValue: spot
    prometheus:
      nodeExporter:
        enabled: false
      serviceAccounts:
        nodeExporter:
          create: false
      server:
        global:
          external_labels:
            cluster_id: ${local.environments[var.environment].cluster_name}
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::${local.environments[var.environment].aws-account-number}:role/${aws_iam_role.kubecost_role.name}
    global:
      configmap.reloader.stakater.com/reload: opencost-rbac-cm
    readonly: true
    serviceMonitor:
      enabled: true
      networkCosts:
        enabled: true
```

Installed helm chart version `1.98.0`, EKS 1.22.

**Expected behavior**  
Number of nodes and pods active in cluster are represented in the main page.

**Collect logs (please complete the following information):**
<img width="1242" alt="Screenshot 2022-12-14 at 2 10 58 PM" src="https://user-images.githubusercontent.com/100310202/207726056-33235eee-2416-4dc1-8e83-4b700bf53a5c.png">

Opencost Prometheus has correct metric count of active nodes in the cluster which makes me think this is a cumulative metric over the past 7 days (in which case this UI is confusing, I don't really care about how many nodes/pods have existed in the past 7 days since they are ephemeral by nature)

<img width="1976" alt="Screenshot 2022-12-14 at 2 12 37 PM" src="https://user-images.githubusercontent.com/100310202/207726364-de259d38-f0e0-4c20-913a-c86be03bf59c.png">
