### ISSUE TITLE
AWS Cloud Integration "no reservation data available in Athena"

### ISSUE THREAD

**Issue by barddes** [kubecost/cost-analyzer-helm-chart#1901]
I'm trying to enable AWS Cloud integration (reservations, saving plans, etc)

I configured cloud integration through helm values:
```
kubecostProductConfigs:    
  ...
  athenaProjectID: "xxxxxxxxxxx"
  athenaBucketName: s3://aws-athena-query-results-xxxxxxxxxxx/
  athenaRegion: xxxxxxxx
  athenaDatabase: athenacurcfn_kubecost_report
  athenaTable: kubecost_report
```
Kubecost deploys fine, but the diagnostics page shows that something is still missing/wrong in my setup:
![image](https://user-images.githubusercontent.com/18225848/212310814-f5af8f36-91a7-44f6-8e8e-76883d5215b2.png)

Reading through logs, I can find only this single error message, but no clues to why this is happening (even within debug logs)

```
ERR Failed to lookup reserved instance data: no reservation data available in Athena
```

Am I missing something? How could I debug this issue?
