### ISSUE TITLE
Licensing requirements for federated setup

### ISSUE THREAD

**Issue by passionInfinite** [kubecost/cost-analyzer-helm-chart#1909]
In the federated kubecost setup do we require to have licenses on the secondary cluster as well?

The docs are clear about the minimal deployment for the kubecost on the secondary clusters but docs doesn't say anything about licensing requirements for the secondary cluster. 

Will secondary cluster be able to support long term metrics retention if thanos-sidecar is deployed with our own prometheus setup?

**Comment by passionInfinite** [comment]
@AjayTripathy Sorry this is not a bug but a question.

**Comment by thomasvn** [comment]
Hi @passionInfinite, good questions!

The Kubecost secondary clusters do not require the `.Values.kubecostProductConfig.productKey` configuration. I've submitted a docs PR to help clarify this!

* https://github.com/kubecost/docs/pull/514

Additionally, could you clarify how you are deploying your thanos-sidecar and Prometheus? At a high level, the Kubecost multi-cluster setup should work if your secondary cluster is writing its metrics to a central Thanos object store from which the primary cluster can read.

**Comment by passionInfinite** [comment]
@thomasvn Thank you for your response!

I have a confusion about the `/metrics` endpoint that prometheus scrapes from the kubecost. What is the purpose of scraping that endpoint using prometheus? 

Regarding Prometheus: We use official prometheus and prometheus-operator deployment and then we connect that prometheus service with kubecost using the configuration as below:

```
prometheus:
    enabled: false
    fqdn: http://promstack-kube-prometheus-prometheus.svc.cluster.local:9090
```
For enabling the `thanos-sidecar` we use the thanos config spec under the prometheus config spec: 

```
thanos:
    image: quay.io/thanos/thanos:v0.28.1
    objectStorageConfig:
      key: thanos.yaml
      name: thanos-objstore-config
```

Now to disable the prometheus do we require any paid or enterprise plan for it?

**Comment by thomasvn** [comment]
@passionInfinite In addition to consuming Prometheus metrics, Kubecost also emits metrics to be stored back into Prometheus (metrics listed [here](https://docs.kubecost.com/general/user-metrics))! It's important for Kubecost's metrics to be in Prometheus, as Kubecost's ETL caches are built from the data within Prometheus.

Using your own Prometheus doesn't require a Business or Enterprise plan! To clarify though, a federated setup where you have secondary Kubecost clusters will require a Business/Enterprise `productKey` to be set on the primary Kubecost cluster. You can view a comparison of  Standard/Business/Enterprise features [here](https://docs.kubecost.com/install-and-configure/install).

**Comment by passionInfinite** [comment]
Again @thomasvn Thank you for the response!

So basically if we have scrapping of `/metrics` is setup using prometheus service monitor to monitor the `/metrics` endpoint of cost-analyzer pod like below manifest.

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prometheus
  name: kubecost-monitor
  namespace: analytics
spec:
  endpoints:
  - honorLabels: true
    interval: 1m
    path: /metrics
    port: tcp-model
  selector:
    matchLabels:
      app.kubernetes.io/name: cost-analyzer
```

I expect the ETL works perfectly fine in this case?
