### ISSUE TITLE
Removing custom kubecostProductConfigs doesn't reset to default state

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#1921]
**Describe the bug**

If you customize and remove options in kubecostProductConfigs, they aren't reverted to the default, empty state. This was brought up regarding setting `kubecostProductConfigs.sharedNamespaces=""`, but I also tested `kubecostProductConfigs.sharedOverhead=""` and it has the same effect. I noticed that the helm chart doesn't set values in the configmap if these are null or empty. However, if I manually set the data point `sharedNamespaces=""`, the application would load correctly, with an empty configuration.

**To Reproduce**

1. Deploy with a shared namespace: `helm upgrade kubecost kubecost/cost-analyzer --set kubecostProductConfigs.sharedNamespaces="test"`
1. Check `/settings` to confirm the shared namespace was set.
1. Upgrade with an empty shared namespace: `helm upgrade kubecost kubecost/cost-analyzer --set kubecostProductConfigs.sharedNamespaces=""`
1. Check `/settings` and see the old `test` namespace listed.

**Expected behavior**

After resetting values in `kubecostProductConfigs` they should revert to empty in the application.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-14) by [Unito](https://www.unito.io)

**Comment by teevans** [comment]
@nikovacevic - Is this just requiring a pod update? Or would you think we have a bad helm configuration?

**Comment by nikovacevic** [comment]
No clue. I'll have to investigate.

**Comment by keithhand** [comment]
Another thing to add here is if you manually update the front end after emptying the value on the Helm side and restart the application, the configuration will save and load back fine.

**Comment by dr460neye** [comment]
I see quite a relation to my feature suggestion
https://github.com/kubecost/cost-analyzer-helm-chart/issues/2009

**Comment by mmurph3** [comment]
Any update on this?

**Comment by teevans** [comment]
@nikovacevic - Friendly Ping here

**Comment by mmurph3** [comment]
@teevans could we have anyone else from the team look into this by chance while niko's out? Thanks.

**Comment by teevans** [comment]
@michaelmdresser or @Sean-Holcomb can either of you two take a look here and see what the lift would be?

**Comment by michaelmdresser** [comment]
The `sharedNamespaces` Helm value gets templated into the `pricing-configs` ConfigMap here: https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/templates/cost-analyzer-pricing-configmap.yaml#L80

 I believe the problematic behavior is happening because rather than setting the value of the ConfigMap var to empty string, it is instead unset. Observe:

```
→ helm template ./cost-analyzer --set kubecostProductConfigs.sharedNamespaces=true | grep -i 'pricing-configmap.yaml' -A 16
# Source: cost-analyzer/templates/cost-analyzer-pricing-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: pricing-configs
  namespace: default
data:
    sharedNamespaces: "true"
---
```

```
→ helm template ./cost-analyzer --set kubecostProductConfigs.sharedNamespaces="" | grep -i 'pricing-configmap.yaml' -A 16
# Source: cost-analyzer/templates/cost-analyzer-pricing-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: pricing-configs
  namespace: default
data:
---
```

I believe this is happening because Helm isn't actually taking the `""` as input -- those are being stripped out by the shell, making the command the equivalent of `helm template ./cost-analyzer --set kubecostProductConfigs.sharedNamespaces=`.

I can try to force an "empty string" into the Helm args like so:
```
→ helm template ./cost-analyzer --set kubecostProductConfigs.sharedNamespaces="''" | grep -i 'pricing-configmap.yaml' -A 16
# Source: cost-analyzer/templates/cost-analyzer-pricing-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: pricing-configs
  namespace: default
data:
    sharedNamespaces: "''"
---
```

This doesn't work as you'd expect, however, because our Helm template surrounds the `{{ .Values... }}` access with quotes (and also uses `| toString`), resulting in what you see above.

---

You would think that the empty `data:` section would imply that the existing ConfigMap would be overridden. Clearly from the observed behavior, this is not the case. I suspect this is due to how Helm handles "merges", some googling found references:
- https://github.com/helm/helm/issues/11520
- https://helm.sh/docs/faq/changes_since_helm2/#improved-upgrade-strategy-3-way-strategic-merge-patches

Kubecost could choose to always overwrite by defaulting all keys in the `data:` section of the ConfigMap to empty string if the corresponding Value is unset, but I suspect this would destroy configurations for users who change these settings in the `/settings` page of the product. Thus the idea is untenable.

The only workaround I can think of is to have some sort of special "value" we can use that forces the template to put in an empty string rather than omitting the key completely. This doesn't feel right. I'm not a Helm expert, so I can't think of anything else at the moment.

**Comment by michaelmdresser** [comment]
~For all that, I think I have a fix that works in https://github.com/kubecost/cost-analyzer-helm-chart/pull/2134:~

This PR doesn't actually work, because K8s demands that values in the `data` section are quoted. That PR will basically only work for the empty string case.

```
→ helm template ./cost-analyzer --set kubecostProductConfigs.sharedNamespaces='""' | grep -i 'pricing-configmap.yaml' -A 16
# Source: cost-analyzer/templates/cost-analyzer-pricing-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: pricing-configs
  namespace: default
  labels:
data:
    sharedNamespaces: ""
```

~@teevans I don't have time to finish this off (remove quotes on all values in this file) and fully test it (make sure that empty string values are treated as we would expect by the backend) but I think the above PR is heading in the right direction.~
