### ISSUE TITLE
Custom saved reports via Helm are not functional

### ISSUE THREAD

**Issue by rossfisherkc** [kubecost/cost-analyzer-helm-chart#2003]
**Describe the bug**  
Two different ones that may be related
ZD #2528

 I can see the `saved-report-configs` configmap is created with the report configurations, and I see the following log message on startup:
Found configmap saved-report-configs, watching...
But when I navigate to the reports page, the reports I configured don't show up.
/model/reports returns an empty array.

Also:

There is some odd stuff happening when creating via helm.
If you create an advanced report in helm it gets duplicated every time the pod restarts
![image](https://user-images.githubusercontent.com/113053906/221618924-41b73898-5332-419a-a6ad-787b7699117b.png)
Allocation reports also don’t come through
via @srpomeroy 

Report config for ZD case

```
savedReports:
  enabled: true
  reports:
    - title: "Daily spend by flow name for last week"
      window: "week"
      aggregateBy: "label:REDACTED"
      accumulate: false
      idle: hide
      filters:
        - property: "namespace"
          value: "REDACTED,REDACTED"
    - title: "Daily spend by flow name and flow run for last week"
      window: "week"
      aggregateBy: "label:REDACTED,label:REDACTED"
      accumulate: false
      idle: hide
      filters:
        - property: "namespace"
          value: "REDACTED,REDACTED"
    - title: "Daily spend by user for last week"
      window: "week"
      aggregateBy: "label:REDACTED"
      accumulate: false
      idle: hide
      filters:
        - property: "namespace"
          value: "REDACTED,REDACTED"
```
