### ISSUE TITLE
[Pricing Model] Mismatch between Helm Values & rendered Values in the Web Portal

### ISSUE THREAD

**Issue by abdennour** [kubecost/cost-analyzer-helm-chart#2058]
# For reproducible bugs, please provide the following

**Describe the bug**  
pushing the un
**To Reproduce**  
1. Go to 'values.yaml'
3. Put these values
```yaml
  kubecostProductConfigs:
    defaultModelPricing: # default monthly resource prices, used predominately for on-prem clusters
      CPU: 90.0
      spotCPU: 0.0
      RAM: 68.0
      spotRAM: 0.0
      GPU: 0.0
      spotGPU: 0.0
      storage: 0.0
      zoneNetworkEgress: 0.0
      regionNetworkEgress: 0.0
      internetNetworkEgress: 0.0
      enabled: true
```

5. See error in Web Portal (Settings page)
<img width="243" alt="image" src="https://user-images.githubusercontent.com/1788384/225437693-994c908c-14af-4859-93bf-c7d540874e17.png">

**Expected behavior**  
Keep unit price same 

**Screenshots**  
Already atached
**Collect logs (please complete the following information):**
-N/A

Kubecost version : 1.200.1
Promethues Embedded: Yes
Kubernetes Version: 1.24.x
