### ISSUE TITLE
Kubecost and its Frontend not working with google managed prometheus (gmp)

### ISSUE THREAD

**Issue by funkymcb** [kubecost/cost-analyzer-helm-chart#2067]
**Describe the bug**  
Hello there. I am trying to apply the kubecost and its frontend to our cluster which runs a google managed prometheus (gmp).
However many metrics are missing and the "Overview" page does not load properly (just a blank white screen).

After running the kubecost/diagnostics, the prometheus health check stated the following error message:
"404: The requested URL `/v1/projects/PROJECT_ID/location/global/prometheus/api/v1/targets` was not found on this server."

Due to this exception the frontend fails to load properly and missing metrics cant't be scraped.
The issue is, that kubecost tries to query the `targets` endpoint.
Unfortunately GMP only provides the following endpoints:
- `/api/v1/query`
- `/api/v1/query_range`
- `/api/v1/metadata`
- `/api/v1/labels`

Is there any possibility to alter the prometheus health check to not query the `api/v1/targets` endpoint?
Or is the only solution to go back to kubecosts own prometheus setup?

**To Reproduce**  
1. Deploy kubecost on a cluster with GMP
2. Disable kubecost prometheus and configure gmp
3. run /kubecost/diagnostics in the frontend

**Expected behavior**  
Prometheus healthcheck succeeds and frontend works properly

**our kubecost helm values.yaml**
```yaml
global:
  thanos:
    enabled: false
  grafana:
    enabled: false
    domainName: grafana.monitoring
    proxy: false # If true, the kubecost frontend will route to your grafana through its service endpoint
  prometheus:
    enabled: false
    fqdn: http://prometheus-server-proxy.monitoring.svc:9090
  additionalLabels:
    unit: peng
prometheus:
  nodeExporter:
    enabled: false
grafana:
  sidecar:
    dashboards:
      enabled: true
    datasources:
      enabled: false
kubecostMetrics:
  emitPodAnnotations: true
  emitNamespaceAnnotations: true
kubecostProductConfigs:
  clusterProfile: "${kubecost_cluster_profile}"
  currencyCode: "EUR"
  grafanaURL: "[...]"
  sharedNamespaces: "kube-system, […]"
  labelMappingConfigs:
    team_label: "unit"
  shareTenancyCosts: true
serviceAccount:
  annotations:
    iam.gke.io/gcp-service-account: "[...]"
nodeSelector:
  unit: peng
```
