### ISSUE TITLE
pricing-configs cm not injecting values into kcm pv

### ISSUE THREAD

**Issue by mmurph3** [kubecost/cost-analyzer-helm-chart#2090]
**Describe the bug**  
When updating helm values.yaml with kubecostProductConfigs.defaultModelPricing , the cm is not injecting the values in /var/configs/default.json

**To Reproduce**  
1. Update helm values.yml with custom pricing:
```
kubecostProductConfigs:
  currencyCode: "SAR"
  defaultModelPricing: # default monthly resource prices, used predominately for on-prem clusters
    CPU: 90.0
    spotCPU: 0.0
    RAM: 68.0
    spotRAM: 0.0
    GPU: 5.0
    spotGPU: 0.0
    storage: 0.0
    zoneNetworkEgress: 0.0
    regionNetworkEgress: 0.0
    internetNetworkEgress: 0.0
    enabled: true
  customPricesEnabled: true
```
2. Apply the changes:
`helm upgrade -i kubecost kubecost/cost-analyzer --create-namespace --namespace kubecost -f values.yml`

3. Check the pricing-configs cm. You'll see the values are updated to reflect the changes made in values.yaml
```
k describe cm pricing-configs -n kubecost                                                            
Name:         pricing-configs
Namespace:    kubecost
Labels:       app=cost-analyzer
              app.kubernetes.io/instance=kubecost
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=cost-analyzer
              helm.sh/chart=cost-analyzer-1.101.3
Annotations:  meta.helm.sh/release-name: kubecost
              meta.helm.sh/release-namespace: kubecost

Data
====
CPU:
----
90
GPU:
----
5
RAM:
----
68
currencyCode:
----
SAR
customPricesEnabled:
----
true

BinaryData
====
```
4. Check /var/configs/default.json in kcm. You'll see values don't reflect:

`{"provider":"base","description":"Default prices based on GCP us-central1","CPU":"0.123288","spotCPU":"0.006655","RAM":"0.093151","spotRAM":"0.000892","GPU":"0.006849","spotGPU":"0.308","storage":"0.00005479452","zoneNetworkEgress":"0.01","regionNetworkEgress":"0.01","internetNetworkEgress":"0.12","firstFiveForwardingRulesCost":"","additionalForwardingRuleCost":"","LBIngressDataCost":"","athenaBucketName":"","athenaRegion":"","athenaDatabase":"","athenaTable":"","athenaWorkgroup":"","masterPayerARN":"","customPricesEnabled":"true","defaultIdle":"","azureSubscriptionID":"","azureClientID":"","azureClientSecret":"","azureTenantID":"","azureBillingRegion":"","azureOfferDurableID":"","azureStorageSubscriptionID":"","azureStorageAccount":"","azureStorageAccessKey":"","azureStorageContainer":"","azureContainerPath":"","azureCloud":"","currencyCode":"SAR","discount":"0%","negotiatedDiscount":"0%","sharedOverhead":"","clusterName":"","sharedNamespaces":"","sharedLabelNames":"","sharedLabelValues":"","shareTenancyCosts":"true","readOnly":"false","editorAccess":"false","kubecostToken":"not-applied","googleAnalyticsTag":"","excludeProviderID":"false"}
`
**Expected behavior**  
I expect the values to be updated in kcm. We also need this to be configurable via the UI under settings > customer pricing > monthly cpu/ram/storage/etc.

**Please share the support case, if any**  

https://kubecost.zendesk.com/agent/tickets/3599

**What impact will this have on your ability to get value out of Kubecost?**

User is not able to persistently apply custom pricing which impacts data integrity and shows incomplete data. We found customer had an unsupported value "NaN" present on the KCM pv for GPU and RAM. This cause the GPU column and total cost column to be blank/null in the allocation page to be null. It also threw a 500 response in the network console. Updating the values via helm/UI didn't remove the NaN values from the KCM pv.
