### ISSUE TITLE
Reconcile Fargate Nodes

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#2092]
**Describe the bug**  
If you have a cluster that is using Fargate pods/nodes, Kubecost will interpret the Kubernetes objects as normal EC2 nodes, leading to them being overpriced, and isn't able to properly reconcile with the CUR, leading to the node showing up in two locations total.

**To Reproduce**  
1. Deploy an EKS Fargate cluster
  ```
  apiVersion: eksctl.io/v1alpha5
  kind: ClusterConfig

  metadata:
    name: fargate-test
    region: us-west-1

  nodeGroups:
    - name: ng-1
      instanceType: t3.medium
      desiredCapacity: 1

  fargateProfiles:
    - name: fp-grafana
      selectors:
        # All workloads in the "kubecost" Kubernetes namespace matching the app=grafana
        # label selectors will be scheduled onto Fargate:
        - namespace: kubecost
          labels:
            app: grafana
  ```

2. See node assets appearing as incorrect prices immediately.
3. Wait for CUR to process and see the duplicated Fargate nodes under the "Amazon EKS" type

**Expected behavior**  
Once the CUR reads the Fargate nodes, the price should be reconciled with the original monitored costs to accurate values.

**Screenshots**  

`Node/fargate-ip-192-168-76-161.us-west-1.compute.internal | 68db9a93ad-0a39345687144469b3b3acb4e9ae0369`
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/43491549/228336369-72879515-53a1-42ac-8755-4060e8c6484b.png">

<img width="1131" alt="image" src="https://user-images.githubusercontent.com/43491549/228335397-97511d9a-a473-4dc2-8894-e69200f6abbd.png">

`Cloud/Management/arn:aws:eks:us-west-1:297945954695:pod/keith-fargate/kubecost/kubecost-grafana-86956dc7ff-kvwzq/4483b301-d4a8-4f24-86f6-9648827af518`
<img width="1122" alt="image" src="https://user-images.githubusercontent.com/43491549/228335923-385e2e9a-3f3a-43fb-b528-e2f70a983f01.png">
**Please share the support case, if any**  
[ZD 3527](https://kubecost.zendesk.com/agent/tickets/3527)

**What impact will this have on your ability to get value out of Kubecost?**
Inability to use clusters that operate using Fargate.
