### ISSUE TITLE
Advanced reports configured via YAML are duplicated on edit

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#2120]
**Describe the bug**  
When you create advanced reports via the [values.yaml](https://github.com/kubecost/cost-analyzer-helm-chart/blob/7c0a385b878829510eafaeff4ddf534196985040/cost-analyzer/values.yaml#L156-L166) and later edit the values, the old report never gets deleted, resulting in multiple reports. This seems to be because the Advanced reports aren't using the configmap as a source of truth like the other report types seem to. Instead, the Advanced reports seem to check for current reports and only add/edit when necessary ([reference](https://github.com/kubecost/kubecost-cost-model/blob/c61c62c258bfb316ef9ccb7990442062503cf9c6/pkg/reports/advanced.go#L175-L182)). 
 
**To Reproduce**  
1. Create an Advanced report using the values.yaml

```yaml
global:
  advancedReports:
    enabled: true
    reports:
    - title: "Example Advanced Report 0"
      window: "7d"
      aggregateBy: "namespace"
      filters:
        - property: "cluster"
          value: "cluster-one"
      cloudBreakdown: "service"
      cloudJoin: "label:kubernetes_namespace"
```

2. Deploy the application and see the first report in the UI:

<img width="1142" alt="image" src="https://user-images.githubusercontent.com/43491549/230157915-5c81b305-934c-4d0b-961c-d4439037a2f0.png">

3. Update the values.yaml to modify the details from the first report

```
global:
  advancedReports:
    enabled: true
    reports:
    - title: "Example Advanced Report 0"
      window: "7d"
      aggregateBy: "cluster"
      filters:
        - property: "cluster"
          value: "cluster-one"
      cloudBreakdown: "service"
      cloudJoin: "label:kubernetes_namespace"
```

4. See a duplicate from the previously configured report:

<img width="1172" alt="image" src="https://user-images.githubusercontent.com/43491549/230158280-05751679-51b4-4bb9-8553-853c592cc0af.png">

**Expected behavior**  
If the reports are configured in the values.yaml, those reports should reflect what is seen in the UI.
https://github.com/kubecost/cost-analyzer-helm-chart/blob/7c0a385b878829510eafaeff4ddf534196985040/cost-analyzer/values.yaml#L156-L157

**Please share the support case, if any**  
[ZD-3756](https://kubecost.zendesk.com/agent/tickets/3756)
