### ISSUE TITLE
Restrictions/RBAC for api users when oidc is enabled

### ISSUE THREAD

**Issue by mmurph3** [kubecost/cost-analyzer-helm-chart#2121]
**What problem are you trying to solve?**
The way teams have accomplished API access in the past from arbitrary endpoints would be to create a separate Ingress into Kubecost with its own authentication layer that bypasses SAML.
You could deploy an ingress object alongside the application, giving you the option to provide ingress to the service. That would look like the following using the host [kubecost-api.com](http://kubecost-api.com/) and an Nginx ingress class (the main thing to note here is we are targeting the apiserver port name). You should note that this would expose the API at the level of the ingress because it is bypassing the SAML authentication:
```
apiVersion: [networking.k8s.io/v1](http://networking.k8s.io/v1)
kind: Ingress
metadata:
  name: kubecost-cost-analyzer-api-access
  namespace: kubecost
spec:
  ingressClassName: nginx
  rules:
  - host: [kubecost-api.com](http://kubecost-api.com/)
    http:
      paths:
      - backend:
          service:
            name: kubecost-cost-analyzer
            port:
              name: apiserver
        path: /
        pathType: ImplementationSpecific
```

**Describe the solution you'd like**
rbac so api users within a group can only access specified api data (e.g. ns, cluster, etc) We don't want users to get any information about any resource through the api calls.

**Describe alternatives you've considered**
NA

**How would users interact with this feature?**
Users that're under a specific group will only have permissions to view data defined via the idp
