### ISSUE TITLE
Support TLS with external Prometheus

### ISSUE THREAD

**Issue by abdennour** [kubecost/cost-analyzer-helm-chart#2128]
**What problem are you trying to solve?**
Let kubecost communicate securely (encrypted traffic) with an external Prometheus 
**Describe the solution you'd like**
I would expect that `.Values.global.prometheus.tlsSecretName` is provided when `.Values.global.prometheus.enabled=false` && `.Values.global,prometheus.fqdn` is in format of `https://my-prometheus.my-namespace:*`

```yaml
global:
    prometheus:
      enabled: false
      ## CHANGED
      fqdn: https://prometheus-k8s.openshift-monitoring:9091/ # local prometheus endpoint
      queryServiceBearerTokenSecretName: ocp-prometheus-token
      # tlsSecretName: <---- FEATURE REQUEST
      # skipTLS <-- OR this ... but Not recommended but we can live with it temp.
```
**Describe alternatives you've considered**
I am gonna to deploy extra layer (envoy proxy) to offload TLS

**How would users interact with this feature?**

This is system feature.. no UI

**Comment by jessegoodier** [comment]
Can you clarify a bit?

If you want Kubecost to use TLS to communicate with your existing prometheus, all you need is to set https in the line you referenced. 

```
Values.global.prometheus.fqdn=https://prometheusendpoint.namespace:port
```

Though this assumes you have setup TLS on your existing prometheus.

**Comment by abdennour** [comment]
@jessegoodier it show this error:
```log
[90m2023-04-05T20:23:54.667652154Z[0m [1m[31mERR[0m[0m ComputeCostData: Request Error: query error: 'Post "https://prometheus-k8s.openshift-monitoring:9091/api/v1/query?query=sum%28increase%28kubecost_pod_network_egress_bytes_total%7Binternet%3D%22false%22%2C+sameZone%3D%22false%22%2C+sameRegion%3D%22true%22%7D%5B2m%5D+%29%29+by+%28namespace%2Cpod_name%2Ccluster_id%29+%2F+1024+%2F+1024+%2F+1024&time=1680726234": tls: failed to verify certificate: x509: certificate is valid for prometheus-k8s.openshift-monitoring.svc, prometheus-k8s.openshift-monitoring.svc.cluster.local, not prometheus-k8s.openshift-monitoring' fetching query 
```



Hint: prometheus service is annotate by:

`service.beta.openshift.io/serving-cert-secret-name=<secret_name>`

**Comment by jessegoodier** [comment]
Looks like the issue is the bearer token? 
To me, it looks like your TLS error is saying the token passed isn't valid. 

I think it should be able to pass in the `queryServiceBearerTokenSecretName`

skip verify is also supported today.

does this help?

```yaml
global:
  # zone: cluster.local (use only if your DNS server doesn't live in the same zone as kubecost)
  prometheus:
    enabled: true # If false, Prometheus will not be installed -- please read this before disabling: https://github.com/kubecost/docs/blob/main/custom-prom.md
    fqdn: http://cost-analyzer-prometheus-server.default.svc #example address of a prometheus to connect to. Include protocol (http:// or https://) Ignored if enabled: true
    # insecureSkipVerify : false # If true, kubecost will not check the TLS cert of prometheus
    # queryServiceBearerTokenSecretName: mcdbsecret  # kubectl create secret generic mcdbsecret -n kubecost --from-file=TOKEN
```
