### ISSUE TITLE
Federator not creating combined directory and not pushing combined etl data to s3 minIO

### ISSUE THREAD

**Issue by mmurph3** [kubecost/cost-analyzer-helm-chart#2130]
**Describe the bug**  
Federator is not creating combined directory and not pushing data to s3 minio bucket. However we do see directory for both primary and secondary and we do see hourly and daily etls in each directory respectively. 

**To Reproduce**  
1. Set up s3 minIO bucket and create user with full access.
2. Create secret and point to an internal S3 MinIO endpoint. Does not use the standard s3.amazon.com endpoint. Will get a copy of federated-store.yaml from customer (sensitive data will be redacted). 
3. Configure federated agent on secondary cluster with following values:
```
NAME: kubecost
kubecostProductConfigs:
  clusterName: mikes-cluster-federated
prometheus:
  server:
    global:
      external_labels:
        cluster_id: mikes-cluster-federated
kubecostModel:
  federatedStorageConfigSecret: kubecost-object-store
federatedETL:
  useExistingS3Config: false
  primaryCluster: false
  federatedCluster: true
```

3. Configure primary
```
prometheus:
  server:
    global:
      external_labels:
        cluster_id: mikes-cluster
kubecostModel:
  federatedStorageConfigSecret: kubecost-object-store
federatedETL:
  useExistingS3Config: false
  primaryCluster: true
  federatedCluster: true
  federator:
    enabled: true

```
**Expected behavior**  
Expect a combined directory to be in the s3 bucket with hourly and daily etls of combined data from both primary and secondary clusters.

**Collect logs (please complete the following information):**
Logs contain sensitive data. Shared with @kaelanspatel over slack.

**What impact will this have on your ability to get value out of Kubecost?**
This is a blocker because customer cannot use enterprise features and cannot see all clusters from the primary. This makes it difficult to manage and customer is not getting what they paid for.
