### ISSUE TITLE
Collect double kube-state-metrics even disabled that

### ISSUE THREAD

**Issue by flavono123** [kubecost/cost-analyzer-helm-chart#2154]
Thanks for your interest in Kubecost!  To ensure you get the help you need, please follow these guidelines:

- If you have questions about product functionality/usage or need assistance with product installation/configuration, please email support@kubecost.com, where our support engineering team will be happy to help!
- If you have a reproducible bug or a feature request, you're in the right place.  Please include the information requested below.

---
# For reproducible bugs, please provide the following

**Describe the bug**  

**To Reproduce**  
1. Deploy a release in the chart version 1.102.1 with following values:
```yaml
# following Bring you own Prometheus + Disable node-exporter and kube-state-metrics
# https://github.com/kubecost/docs/blob/main/custom-prom.md#disable-node-exporter-and-kube-state-metrics-recommended
global:
  prometheus:
    enabled: false
    fqdn: http://<my-own-prom-svc>
...(omitted)
prometheus:
  extraScrapeConfigs: |
    - job_name: kubecost
      honor_labels: true
      scrape_interval: 1m
      scrape_timeout: 60s
      metrics_path: /metrics
      scheme: http
      dns_sd_configs:
      - names:
        - {{ template "cost-analyzer.serviceName" . }}
        type: 'A'
        port: 9003
    - job_name: kubecost-networking
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
      # Scrape only the the targets matching the following metadata
        - source_labels: [__meta_kubernetes_pod_label_app]
          action: keep
          regex:  {{ template "cost-analyzer.networkCostsName" . }}
...
  nodeExporter:
    enabled: false
  kubeStateMetrics:
    enabled: false
  kube-state-metrics:
    disabled: true
...
```
2. Check the two kube-state-metrics collected in Grafana(datasource is my existing prometheus). 
- e.g. `kube_deployment_spec_replicas{deployment="some-deploy"}`
  - One is `{__name__="kube_deployment_spec_replicas", container="cost-model", deployment="some-deploy", endpoint="tcp-model", instance="...:9003", job="kubecost-cost-analyzer", namespace="ns", pod="kubecost-cost-analyzer-79c6dff69b-79hlv", service="kubecost-cost-analyzer"}`
  - Another is `{__name__="kube_deployment_spec_replicas", container="kube-state-metrics", deployment="some-deploy", endpoint="http", instance="...:8080", job="kube-state-metrics", namespace="ns", pod="prometheus-kube-state-metrics-d4b7f9f6d-bkj6f", service="prometheus-kube-state-metrics"}`

**Expected behavior**  
- `kube-state-metrics` should be collected once.

**Screenshots**  

**Collect logs (please complete the following information):**
- Run `helm ls` and paste the output here:
- If the pod is stuck in init, run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-analyzer-init` and paste output here:
- If a page is broken or not loading, open your javascript developer console and paste the ouput here:
- Run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-analyzer-server` and paste the output here:
- Run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-model` and paste the output here:
- Run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-analyzer-frontend` and paste the output here:

**Please share the support case, if any**  
This is most commonly a Zendesk ticket number or link.

**What impact will this have on your ability to get value out of Kubecost?**
