### ISSUE TITLE
Help implement Azure Rate Card

### ISSUE THREAD

**Issue by vptimmy** [kubecost/cost-analyzer-helm-chart#2183]
**Describe the bug**  
Azure Rate card not appearing in v1.102.2 after following instructions at https://docs.kubecost.com/install-and-configure/install/cloud-integration/azure-out-of-cluster/azure-config  

This is a custom cluster on prem using RKE.  We want to see  how much some services may cost if we move them to Azure Cloud.    

Any insight is much appreciated.  We do not have an Azure Kubernetes Cloud set up currently, thus no pricing is available perhaps?  It's the best I can think of.   We just assumed it would get some default rates?

**To Reproduce**  
1. Visit https://docs.kubecost.com/install-and-configure/install/cloud-integration/azure-out-of-cluster/azure-config
2. Create the Azure role
3. Create the service principle (KubecostAccess) in Azure and assign the above role
4. Visit portal.azure.com and go to the "App Registrations" and choose the KubecostAccess SP and create a client secret
5. Used the following information in a subchart values.yaml
```yaml
cost-analyzer:
  networkCosts:
    enabled: true

  kubecostProductConfigs: 
    azureSubscriptionID: "our subscription id"
    azureClientID: "KubeCostAccess client id"
    azureTenantID: "Our Tenant"
    azureClientPassword: "The assigned secret from step #4"
    azureBillingRegion: US
    azureOfferDurableID: MS-AZR-xxxx
    currencyCode: USD
    createServiceKeySecret: true

  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/whitelist-source-range: "allowed subnet ranges"  
```

**Expected behavior**  
To see Azure card rate or see data in the log files giving me a reason as to why I would not see the Azure card rate.

The secret **cloud-service-key** is created in the namespace and has the following data, reflecting the data above in values.yaml
```json
service-key.json
{
  "subscriptionId": "our subscription id",
  "serviceKey": {
    "appId": "KubeCostAccess client id",
    "displayName": "KubecostAccess",
    "password": "The assigned secret from step #4",
    "tenant": "Our Tenant"
  }
}
```

There are no errors in the log file or reference to Azure?  See attached files.  There are some "cloud" references but nothing to go on.
```log
Initialization: populating cloud provider map

Failed to load cloud-integration config: failed to locate cloud-integration config file: /var/cloud-integration/cloud-integration.json

CloudUsage[custom]: Build[Pwrhn]: QueryCloudUsage error: not implemented for Custom

CloudCost:DisabledPipeline: Status called on a disabled pipeline.

CloudCost:DisabledPipeline: Status called on a disabled pipeline. logged 1 times: suppressing future logs

ETL: failed to merge cloud usage: QueryCloudUsage: query failure: boundary error: requested [2023-04-18T13:55:08+0000, 2023-04-25T13:55:08+0000); supported [2023-04-22T00:00:00+0000, 2023-04-25T13:53:55+0000): Store[custom]: store does not have coverage to perform query

Returning only active clusters, CloudCost is enabled but Query cloud cost compute items for window [2023-04-18T13:55:08+0000, 2023-04-25T13:55:08+0000) failed with err : CloudCost Store is empty
```
[kubecost-cost-analyzer.log](https://github.com/kubecost/cost-analyzer-helm-chart/files/11333178/kubecost-cost-analyzer.log)
