### ISSUE TITLE
Prom and Thanos do not observe systemProxy settings

### ISSUE THREAD

**Issue by kc-creynold** [kubecost/cost-analyzer-helm-chart#2215]
For certain customers, their cluster can be behind a proxy to access the outside world. Either in the cloud or on prem.  For this example, let's assume the primary cluster is in GCP and the thanos bucket is in GCP, this cluster has no access restrictions.

For the secondary cluster, let's assume on prem. This cluster has no access to the outside world.  In order to reach the GCP based thanos bucket, the cluster needs to go through a proxy server.  

---
# For reproducible bugs, please provide the following

**Describe the bug**  
When using the systemProxy settings, Thanos/Prom do not get the env variables.

**To Reproduce**  
First, create a proxy to test:
1.  kubectl run proxy-svc --image hinata/nginx-forward-proxy:latest
2.  kubectl expose pod proxy-svc --port 3128
3. Set systemProxy under kubecostProductConfig:
```
systemProxy:
  enabled: true
  httpProxyUrl: http://proxy-svc:3128/
  httpsProxyUrl: http://proxy-svc:3128/
  noProxy: localhost,127.0.0.1,.svc,.kubecost,10.0.0.0/8,192.0.0.0/8
```
4. Deploy
5. Check env variables.  Thanos does not get the necessary env variables to route through a proxy server

**Expected behavior**  
Prom/Thanos would get the proxy settings just from systemProxy and not having to set them manually in prometheus.server.env

Here is a working config that @jessegoodier created to where Prom/Thanos will work behind a proxy:

```
systemProxy:
  enabled: true
  httpProxyUrl: http://proxy-svc:3128/
  httpsProxyUrl: http://proxy-svc:3128/
  noProxy: localhost,127.0.0.1,.svc,.kubecost,10.0.0.0/8,192.0.0.0/8
prometheus:
  server:
    env:
    - name: HTTP_PROXY
      value: http://proxy-svc:3128/
    - name: http_proxy
      value: http://proxy-svc:3128/
    - name: HTTPS_PROXY
      value: http://proxy-svc:3128/
    - name: https_proxy
      value: http://proxy-svc:3128/
    - name: NO_PROXY
      value: localhost,127.0.0.1,.svc,.kubecost,10.0.0.0/8,192.0.0.0/8
    - name: no_proxy
      value: localhost,127.0.0.1,.svc,.kubecost,10.0.0.0/8,192.0.0.0/8
    sidecarContainers:
    - name: thanos-sidecar
      image: thanosio/thanos:v0.29.0
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
      args:
      - sidecar
      - --log.level=debug
      - --tsdb.path=/data/
      - --prometheus.url=http://127.0.0.1:9090/
      - --objstore.config-file=/etc/config/object-store.yaml
      - --min-time=-3h
      env:
      - name: HTTP_PROXY
        value: http://proxy-svc:3128/
      - name: http_proxy
        value: http://proxy-svc:3128/
      - name: HTTPS_PROXY
        value: http://proxy-svc:3128/
      - name: https_proxy
        value: http://proxy-svc:3128/
      - name: NO_PROXY
        value: localhost,127.0.0.1,.svc,.kubecost,10.0.0.0/8,192.0.0.0/8
      - name: no_proxy
        value: localhost,127.0.0.1,.svc,.kubecost,10.0.0.0/8,192.0.0.0/8
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
```
