### ISSUE TITLE
kube-state-metrics dependency condition inconsistency

### ISSUE THREAD

**Issue by michaelsatish** [kubecost/cost-analyzer-helm-chart#2264]
**Describe the bug**  
kube-state-metrics is getting installed with values file `values-eks-cost-monitoring.yaml`

The dependency condition to install the kube-state-metrics `./charts/prometheus/Chart.yaml` uses the `disabled` key.

```yaml
dependencies:
  - condition: kube-state-metrics.disabled
    name: kube-state-metrics
    repository: file://./charts/kube-state-metrics
```

However, in the values.yaml file `./charts/prometheus/values.yaml` uses the `enabled` key.

```yaml
kube-state-metrics:
  ## If false, kube-state-metrics sub-chart will not be installed
  ## Please see https://github.com/helm/charts/tree/master/stable/kube-state-metrics for configurable values
  ##
  enabled: true
```

The values file `values-eks-cost-monitoring.yaml` uses the disabled key.

```yaml
kube-state-metrics:
    disabled: false
```

**Comment by kwombach12** [comment]
@thomasvn can you take a look at this?

**Comment by thomasvn** [comment]
@michaelsatish Great catch, thank you! I tested by running `helm template ./cost-analyzer -f ./cost-analyzer/values-eks-cost-monitoring.yaml` and in the result, I still saw the kube-state-metrics subchart's resources being created.

I agree that `values-eks-cost-monitoring.yaml` should instead have the following:

```yaml
kube-state-metrics:
  enabled: false
```

@michaelsatish Are you interested in submitting a PR for this?

**Comment by michaelsatish** [comment]
@thomasvn I am happy to submit a PR. On it....

**Comment by michaelsatish** [comment]
@thomasvn 

I noticed that even after standardizing `kube-state-metrics.enabled` in the following places, the "kube-state-metrics" sub chart was getting installed.

1. values-eks-cost-monitoring.yaml
```yaml
prometheus:
  kube-state-metrics:
    enabled: false
```

2. ./charts/prometheus/Chart.yaml
```yaml
dependencies:
  - condition: kube-state-metrics.enabled
    name: kube-state-metrics
    repository: file://./charts/kube-state-metrics
```

This is because, the prometheus subchart has a requirements.yaml file with the kube-state-metrics dependency.
```yaml
dependencies:
  - name: kube-state-metrics
    version: "2.7.*"
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: kubeStateMetrics.enabled
```

And the base values.yaml file has it enabled by default.
```yaml
prometheus:
  kubeStateMetrics:
    enabled: true
```
