### ISSUE TITLE
Add Extra Manifest

### ISSUE THREAD

**Issue by speedfl** [kubecost/cost-analyzer-helm-chart#2325]
**What problem are you trying to solve?**
Lot of charts propose to add extra manifests. This allows for example to dynamically create Secret management resources, networking resources, policies with the chart itself without having to create an umbrella chart.

**Describe the solution you'd like**
Add an `extraObjects` node which takes as input kube manifests

**Describe alternatives you've considered**
Create umbrella chart :/
Install the chart and then extra manifests :/

**How would users interact with this feature?**
NA

**Comment by kwombach12** [comment]
@speedfl Thanks for suggesting this and opening a PR! @AjayTripathy @teevans is this something you can review?

**Comment by jessegoodier** [comment]
Interesting suggestion!

Is this simply adding a template like below? If so, I can see how this could be useful.

Example:
`extra-manifests.yaml`
```yaml
{{- range .Values.extraManifests }}
---
{{ tpl (toYaml .) $ }}
{{- end }}
```

with a sample file of:
`configmap-networkcosts.yaml`
```yaml
extraManifests:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: network-costs-config
      namespace: staging-app
    data:
      config.yaml: |
        destinations:
          cross-region: []
          direct-classification: []
          in-region: []
          in-zone:
          - 127.0.0.0/8
          - 169.254.0.0/16
          - 10.0.0.0/8
          - 172.16.0.0/12
          - 192.168.0.0/16
          internet: []
        services:
          amazon-web-services: false
          azure-cloud-services: false
          google-cloud-services: false
```

test:
```sh
helm template kubecost ./cost-analyzer -f .idea/configmap-networkcosts.yaml.yaml
```
