### ISSUE TITLE
Azure AD OIDC login broken when rbac is enabled

### ISSUE THREAD

**Issue by vranyes** [kubecost/cost-analyzer-helm-chart#2368]
Thanks for your interest in Kubecost! To ensure you get the help you need, please follow these guidelines:

- If you have questions about product functionality/usage or need assistance with product installation/configuration, please email <support@kubecost.com>, where our support engineering team will be happy to help!
- If you have a reproducible bug, you're in the right place. Please include the information requested below.

---

**Describe the bug**  

When cost-model is configured to use AzureAD OIDC with rbac enabled and a user tries to log in, cost-model logs the following error:

```bash
WRN Cannot parse JWT id_token: failed to verify jws signature: failed to verify message: crypto/rsa: verification error
```

**To Reproduce**  

Configure the following in the cost-analyzer helm chart

```yaml
    oidc:
      authURL: >-
        https://login.windows.net/${kubecost_oidc_tenant_id}/oauth2/authorize?response_type=code&client_id=${kubecost_oidc_client_id}&redirect_uri=https%3A%2F%2Fkubecost.${cluster_external_domain}/model/oidc/authorize&scope=openid
      clientID: ${kubecost_oidc_client_id}
      discoveryURL: >-
        https://sts.windows.net/${kubecost_oidc_tenant_id}/v2.0/.well-known/openid-configuration
      enabled: true
      loginRedirectURL: https://kubecost.${cluster_external_domain}/model/oidc/authorize
      rbac:
        enabled: true
        groups:
        - claimName: roles
          claimValues:
          - kubecost.admin
          enabled: true
          name: admin
        - claimName: roles
          claimValues:
          - kubecost.viewer
          enabled: true
          name: readonly
```

**Expected behavior**  

cost-model should be able to parse the `id_token` successfully. Perhaps the jwks uri from the discovery URL isn't being used?

**Screenshots**  

n/a

**What impact will this have on your ability to get value out of Kubecost?**

Presently we are unable to enforce read-only and oidc authentication at the same time.

This means we have to choose between:

- granting all authentiacated users the ability to modify Kubecost 
- allow no modifications to Kubecost via the UI and have no visiblity into who is accessing Kubecost

**Bug report**

I am unable to generate a bug report with this configuration because login is broken :)

**Please share the support case, if any**  

n/a
