### ISSUE TITLE
Allocation Alerts with custom content

### ISSUE THREAD

**Issue by shauryaBlue** [kubecost/cost-analyzer-helm-chart#2376]
**What problem are you trying to solve?**
We would like to add more details with the alerts generated through Kubecost.
Eg. Attaching links to the kubecost dashboard / Reports attached to the emails / Details on what action is to be taken

**Describe the solution you'd like**
Feature for adding messages with dynamic content through HTLM / text on the alerts
Eg. 
i. https://plugins.jenkins.io/email-ext/#plugin-content-groovy-script-content-templates
ii. https://argocd-notifications.readthedocs.io/en/stable/services/email/#template

**Describe alternatives you've considered**
Currently, we generate custom alerts using a separate automation which uses Kubecost APIs & runs daily with a cron schedule

**How would users interact with this feature?**
Alert notification templates can be added to the helm charts

**Comment by thomasvn** [comment]
@shauryaBlue Thanks for the feature request! Could you share how you've currently configured your alerting?

@kwombach12 Could you provide some input here when you return?

**Comment by shauryaBlue** [comment]
Sure @thomasvn 

Alerts are currently added per namespace to the helm chart
```
     alertConfigs:
        globalAlertEmails:
        - <>
        alerts: 
        - type: efficiency
          efficiencyThreshold: 0.6
          spendThreshold: 10
          window: 7d
          aggregation: namespace
          ownerContact:
          - <>
```
However, the alert generated by this does not provide sufficient details as to what action a namespace owner should take.
We would like to attach custom data ( mainly kubecost container request recommendations ) along with the alert.

Current alert :

>  Efficiency for namespace `<>` (14%) dropped below the allowed threshold of 30%.
Total Spend during Efficiency Alert: 58

Required alert example :

> [Alert] Efficiency for namespace `<>` (14%) dropped below the allowed threshold of 30%.
Please review kubecost recommendations for setting requests here : <>

> Total Spend during Efficiency Alert: 58 
This has increased by <>% in the past 2 weeks

The customisation of these messages would be great, as we could point application teams to required resources they can use
