### ISSUE TITLE
Failed Prometheus Metric Test: Test failed for "Kubecost's CPU usage recording rule is set up"

### ISSUE THREAD

**Issue by andreyolv** [kubecost/cost-analyzer-helm-chart#2392]
This error in prometheus metrics dignonostic:

Kubecost's CPU usage recording rule is set up

Description: If the 'kubecost_container_cpu_usage_irate' recording rule is not set up, Allocation pipeline build may put pressure on your Prometheus due to the use of a subquery. [Learn More](https://docs.kubecost.com/install-and-configure/install/custom-prom)

Query:absent_over_time(kubecost_container_cpu_usage_irate{}[5m] )

Result: [{"metric":{},"values":[{"timestamp":1687867790,"value":1}]}]

**To Reproduce**  
I am using prometheus community helm chart and grafana sep
Install Kubecost Helm chart (version 1.104.1) with follow configs:
```
global:
      prometheus:
        enabled: false
        fqdn: http://prometheus-server.monitoring.svc:80
      grafana:
        enabled: false
        proxy: false
    prometheus:
      server:
        global:
          external_labels:
            cluster_id: MY_CLUSTER
      nodeExporter:
        enabled: false
      kubeStateMetrics:
        enabled: false
      kube-state-metrics:
        disabled: true
      serviceAccounts:
        nodeExporter:
          create: false
    networkCosts:
      enabled: true
      config:
        services:
          azure-cloud-services: true
    kubecostProductConfigs:
      cloudIntegrationSecret: cloud-integration

```

extraScrapeConfigs in my Prometheus:
```
extraScrapeConfigs: |
      - job_name: kubecost
        honor_labels: true
        scrape_interval: 1m
        scrape_timeout: 10s
        metrics_path: /metrics
        scheme: http
        dns_sd_configs:
        - names:
          - kubecost-cost-analyzer.kubecost
          type: 'A'
          port: 9003
      - job_name: kubecost-networking
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
        # Scrape only the the targets matching the following metadata
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: kubecost-network-costs
```

I tried to add this to my prometheus community helm chart too, but withou success:
```
serverFiles:
      recording_rules.yml:
        groups:
        - name: CPU
          rules:
          - expr: avg(irate(container_cpu_usage_seconds_total{container_name!="POD", container_name!=""}[5m]))
              by (container_name,pod_name,namespace)
            record: kubecost_container_cpu_usage_irate
```
Why do I have this error and how to solve it? Thanks

**Expected behavior**  
No error

**Screenshots**  
![image](https://github.com/kubecost/cost-analyzer-helm-chart/assets/49295662/896708ef-a6eb-4eb9-a1a5-e83c8b03aa0f)
![image](https://github.com/kubecost/cost-analyzer-helm-chart/assets/49295662/0185f326-a176-4f32-9d6a-7d2c3894b513)

**What impact will this have on your ability to get value out of Kubecost?**
I'm not confident in the accuracy of the values ​​shown by kubecost
