### ISSUE TITLE
 PersistentVolume source 'AWSElasticBlockStore' uses an in-tree storage plugin which is unsupported by Karpenter and is deprecated by Kubernetes. 

### ISSUE THREAD

**Issue by FernandoMiguel** [kubecost/cost-analyzer-helm-chart#2427]
**Describe the bug**  
```shell
2023-07-10T11:19:01.334Z    ERROR    controller.node_state    PersistentVolume source 'AWSElasticBlockStore' uses an in-tree storage plugin which is unsupported by Karpenter and is deprecated by Kubernetes. Scale-ups may fail because Karpenter will not discover driver limits. Use a PersistentVolume that references the 'CSI' volume source for Karpenter auto-scaling support.    {"commit": "d7e22b1-dirty", "node": "i-0f2610ea134dbea79.ec2.internal", "pod": "kubecost-prometheus
```

**To Reproduce**  
```yaml
  - name: cost-analyzer
    repository: oci://public.ecr.aws/kubecost
    version: ~1.104
```
```yaml
  prometheus:
    server:
      image:
        repository: public.ecr.aws/kubecost/prometheus
        tag: v2.35.0
      resources:
        limits:
          memory: 512Mi
        requests:
          cpu: 500m
          memory: 512Mi
      global:
        scrape_interval: 1m
        scrape_timeout: 10s
        evaluation_interval: 1m
        external_labels:
          cluster_id: cluster-one
      persistentVolume:
        enabled: true
        size: 32Gi
        storageClass: "gp3"
      extraArgs:
        query.max-concurrency: 1
        query.max-samples: 100000000
      tolerations: []
```

**Expected behavior**  
for EBS CSI to be used

**What impact will this have on your ability to get value out of Kubecost?**
may lose access to PVC in a future release
