### ISSUE TITLE
kube-state-metrics dependency not compatible with EKS Version 1.26

### ISSUE THREAD

**Issue by f-palma** [kubecost/cost-analyzer-helm-chart#2445]
**Describe the bug** 
The suggested images [https://github.com/kubernetes/kube-state-metrics/#compatibility-matrix](url) by kube-state-metrics for the k8s cluster version 1.26 are not compatible with the kube-state-metrics helm chart defined in the version `cost-analyzer-1.104.5`. 

The kms helm chart uses the `collectors` values to create the cluster role and also to pass the values in the deployment container args,  but the new suggested images use the `--resources` instead of  `--collectors`, so the ksm pod will go in crashloopbackoff.

**To Reproduce**  

1. Install kubecost in a k8s cluster version 1.26 using helm chart version `cost-analyzer-1.104.5` using the following values
```
# PodSecurityPolicy (PSP) is being deprecated in Kubernetes 1.21
# With the release of Kubernetes v1.25, PodSecurityPolicy has been removed.
podSecurityPolicy:
  enabled: false

grafana:
  rbac:
    pspEnabled: false

prometheus:
  server:
    image:
      repository: public.ecr.aws/kubecost/prometheus
      tag: v2.35.0
  configmapReload:
    prometheus:
      ## If false, the configmap-reload container will not be deployed
      ##
      enabled: true

      ## configmap-reload container name
      ##
      name: configmap-reload
      ## configmap-reload container image
      ##
      image:
        repository: public.ecr.aws/bitnami/configmap-reload
        tag: 0.7.1
        pullPolicy: IfNotPresent
      ## Additional configmap-reload container arguments
      ##
      extraArgs: {}
      ## Additional configmap-reload volume directories
      ##
      extraVolumeDirs: []
      ## Additional configmap-reload mounts
      ##
      extraConfigmapMounts: []
        # - name: prometheus-alerts
        #   mountPath: /etc/alerts.d
        #   subPath: ""
        #   configMap: prometheus-alerts
        #   readOnly: true
      ## configmap-reload resource requests and limits
      ## Ref: http://kubernetes.io/docs/user-guide/compute-resources/
      ##
      resources: {}
  #https://github.com/kubernetes/kube-state-metrics/#compatibility-matrix
  kube-state-metrics:
    disabled: false
    image:
      repository: public.ecr.aws/bitnami/kube-state-metrics
      tag: 2.9.2


# Enable this flag if you need to install with specfic image tags
# imageVersion: prod-1.97.0

kubecostFrontend:
  image: public.ecr.aws/kubecost/frontend
  imagePullPolicy: Always
  resources:
    requests:
      cpu: "10m"
      memory: "55Mi"
    #limits:
    #  cpu: "100m"
    #  memory: "256Mi"

kubecostModel:
  image: public.ecr.aws/kubecost/cost-model
  imagePullPolicy: Always
  warmCache: true
  warmSavingsCache: true
  resources:
    requests:
      cpu: "200m"
      memory: "55Mi"
    #limits:
    #  cpu: "800m"
    #  memory: "256Mi"
``` 
2. Watch the errors with `kubectl logs -n kubecost -l "app.kubernetes.io/name=kube-state-metrics"`:

`Error: unknown flag: --collectors`

---

Updating the dependency to a newer version should solve the problem, it would certainly be useful to have a compatibility matrix in the README.md.
