### ISSUE TITLE
GKE Cost recommendations unable to find bigquery dataset 

### ISSUE THREAD

**Issue by cheddarwhizzy** [kubecost/cost-analyzer-helm-chart#2447]
**Describe the bug**  
I'm attempting to get resource recommendations working

**To Reproduce**  

- Install helm chart version 1.104.1 with `clusterController.enabled=true`
- Enable `GKE usage metering` and set the correct dataset ID (e.g. `wk_qa_gke_usage`)
- Set `kubecostProductConfigs` and `clusterController`
  ```
  clusterController:
    enabled: true
    logLevel: debug
    secretName: kubecost-gcp-key

  kubecostProductConfigs:
    projectID: "my-gcp-project-id"
    clusterProfile: development
    bigQueryBillingDataDataset: "my-gcp-project-id.wk_qa_gke_usage"
    gcpSecretName: "kubecost-gcp-key"
    clusterName: <gke-cluster-name>
    clusterAccountID: "my-gcp-project-id"
  ```

**Expected behavior**  
The `kubecost-cost-analyzer` pod should be able to fetch recommendations but fails to find that dataset
```
{"level":"error","time":"2023-07-18T21:14:17.749249091Z","message":"ETL: CloudUsage[my-gcp-project-id/my-gcp-project-id.wk_qa_gke_usage]: Build[IYnAa]: QueryCloudUsage error: googleapi: Error 404: Not found: Dataset my-gcp-project-id:my-gcp-project-id was not found in location US, notFound"}
```

The following works with the GCP service account key activated
```
gcloud --project my-gcp-project-idalpha bq datasets describe wk_qa_gke_usage

access:
- role: WRITER
  specialGroup: projectWriters
- role: WRITER
  userByEmail: service-abcd123456@gcp-sa-bigquerydatatransfer.iam.gserviceaccount.com
- role: OWNER
  specialGroup: projectOwners
- role: OWNER
  userByEmail: abcd123456@cloudservices.gserviceaccount.com
- role: READER
  specialGroup: projectReaders
creationTime: '1610468552142'
datasetReference:
  datasetId: wk_qa_gke_usage
  projectId: my-gcp-project-id
etag: readacted
id: my-gcp-project-id:wk_qa_gke_usage
kind: bigquery#dataset
labels:
  goog-dm: k8s-cluster
lastModifiedTime: '1659987420412'
location: US
selfLink: https://bigquery.googleapis.com/bigquery/v2/projects/my-gcp-project-id/datasets/wk_qa_gke_usage
type: DEFAULT
```

K8s secret has both keys. The GCP SA has owner and bigquery admin roles. 
```
kgsec kubecost-gcp-key -o yaml

apiVersion: v1
data:
  compute-viewer-kubecost-key.json: <REDACTED>
  service-key.json: <REDACTED>
kind: Secret
metadata:
  name: kubecost-gcp-key
  namespace: kubecost
type: Opaque
```
