### ISSUE TITLE
[Question] grafana hostname

### ISSUE THREAD

**Issue by FernandoMiguel** [kubecost/cost-analyzer-helm-chart#2637]
### Problem Statement

we serve kubecost from  kubecost.clustername.company.tld
we serve kubecost grafana from  kubecost-grafana.clustername.company.tld
```
  grafana:
    ingress:
      enabled: true
      annotations:
        internal.lbc.kyverno/clusterDomain: "true"
        internal.lbc.kyverno/target: "true"
      className: nginx-internal
      hosts:
        - kubecost-grafana
    grafana.ini:
      server:
        serve_from_sub_path: false
        root_url: "%(protocol)s://%(domain)s:%(http_port)s"
```
accessing https://kubecost-grafana.clustername.company.tld/ works well
but if we go to 
https://kubecost.clustername.company.tld/request-sizing
click a container
click grafana, we get a blank page and the URL used is
https://kubecost.clustername.company.tld/grafana/d/at-cost-analysis-pod/pod-cost-and-utilization-metrics?from=now-7d&orgId=1&var-costStorageStandard=0.044&var-costStorageSSD=0.187&var-costDiscount=30&var-namespace=sre-ingress-nginx-system&var-pod=ingress-nginx-alpha-0n-public-controller-cb9879b69-p4476

notice the lack of `-grafana` in the url and the path `/grafana/` in there.

### Solution Description

looking for one

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a feature request only for the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.
