### ISSUE TITLE
add pod monitor for network analyzer daemonset

### ISSUE THREAD

**Issue by omerlh** [kubecost/cost-analyzer-helm-chart#265]
**What problem are you trying to solve?**
Although network costs is enabled, there are no network information on KubeCost. This is because the service monitor is for the api, but there is no pod monitor for scraping network pods.

**Describe the solution you'd like**
Adding pod monitor for the network analyzer to the chart.

**Describe alternatives you've considered**
Create pod monitor manually

**How would users interact with this feature?**

**Comment by omerlh** [comment]
Hey, any update on that?

**Comment by dwbrown2** [comment]
No updates yet. Is it a meaningful priority for you? Have a template that could help us get started?

**Comment by omerlh** [comment]
```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kubecost-network-costs
  labels:
    app: prometheus-operator
    release: skr
spec:
  selector:
    matchLabels:
      app: kubecost-network-costs
  podMetricsEndpoints:
  - port: http-server
```
:)
