### ISSUE TITLE
Helm tests for aggregator

### ISSUE THREAD

**Issue by chipzoller** [kubecost/cost-analyzer-helm-chart#2708]
We need to start building a matrix of tests for the Helm chart. Since the aggregator is a new component and an important configuration, we could start with below as suggested.

```yaml
kubecostAggregator:
  enabled: true
  cloudCost:
    enabled: true
kubecostModel:
  federatedStorageConfigSecret: federated-store
kubecostProductConfigs:
  cloudIntegrationSecret: cloud-integration
```

_Originally posted by @thomasvn in https://github.com/kubecost/cost-analyzer-helm-chart/issues/2699#issuecomment-1786201083_
