### ISSUE TITLE
[Bug] The kubecost-cost-analyzer is stuck in CrashLoopBackOff state in EKS

### ISSUE THREAD

**Issue by igoratencompass** [kubecost/cost-analyzer-helm-chart#2710]
### Kubecost Helm Chart Version

1.106.4

### Kubernetes Version

1.25

### Kubernetes Platform

EKS

### Description

The `kubecost-cost-analyzer` pod is stuck in `CrashLoopBackOff` state:

```
$ kc get pods -n kubecost
NAME                                                      READY   STATUS             RESTARTS        AGE
kubecost-cost-analyzer-59b55cbb4f-ltm6l       1/2     CrashLoopBackOff   9 (2m51s ago)   24m
kubecost-prometheus-server-6f8fdd9849-265vd   2/2     Running 
```
The errors seen in the `cost-model` container:

`$ kubectl logs -n kubecost kubecost-cost-analyzer-59b55cbb4f-ltm6l -c cost-model -f`

```
2023-10-31T01:05:05.947708688Z ERR savings: cluster sizing: failed to get monthly cluster rates: error getting valid asset set in MonthlyNodeClusterRates: could not obtain latest valid asset set (an AssetSet where all Assets (i.e. Nodes) have NodeType != "" and TotalCost > 0.0
2023-10-31T01:05:05.947733181Z WRN got error failed to get monthly cluster rates: error getting valid asset set in MonthlyNodeClusterRates: could not obtain latest valid asset set (an AssetSet where all Assets (i.e. Nodes) have NodeType != "" and TotalCost > 0.0 for metric clusterSizing%%High-Availability, not adding to cache
2023-10-31T01:05:08.872817217Z ERR error parsing window: no pricing data for key 'us-east-2,EBS:VolumeUsage.gp2'
2023-10-31T01:05:08.872859033Z WRN got error no pricing data for key 'us-east-2,EBS:VolumeUsage.gp2' for metric orphanedResources%%High-Availability, not adding to cache
2023-10-31T01:05:08.875186913Z INF ETL: Allocation: QueryAllocation([2023-10-30T01:05:08+0000, 2023-10-31T01:05:08+0000), [cluster node namespace pod container]) from StoreDriver[1d] 818.435µs [query 349.327µs] [idle/tenancy 310ns] [external 118ns] [aggregate 468.359µs] [accumulate 184ns] [stop 137ns]
2023-10-31T01:05:08.875225604Z ERR error creating spot-ready workload distributions: error creating spot-ready workload distributions: failed to create any WorkloadDistributions for AllocationSetRange
2023-10-31T01:05:08.875239374Z WRN got error error creating spot-ready workload distributions: failed to create any WorkloadDistributions for AllocationSetRange for metric spotResources%%High-Availability, not adding to cache
```
The describe on the pod shows `cost-analyzer-frontend` exiting with error:
```
Containers:
  cost-model:
    Container ID:   containerd://dff412f854d4ebec1cf0b0384938b90d413d8d8e913fe24b31947a70b92af147
    Image:          gcr.io/kubecost1/cost-model:prod-1.106.4
    Image ID:       gcr.io/kubecost1/cost-model@sha256:237c4d881ae654d2100ef4bafa0cd54d2b935686eac46b944e71c9962b2b7bef
    Ports:          9003/TCP, 9090/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Running
      Started:      Tue, 31 Oct 2023 11:58:35 +1100
    Ready:          True
    Restart Count:  0
    Requests:
      cpu:      200m
      memory:   55Mi
    Liveness:   http-get http://:9003/healthz delay=30s timeout=1s period=10s #success=1 #failure=200
    Readiness:  http-get http://:9003/healthz delay=30s timeout=1s period=10s #success=1 #failure=200
[snip]
  cost-analyzer-frontend:
    Container ID:   containerd://9bb377feeb5322797de0315f2ecc3de1345e49c37a15bc2cf8380a66a2fd1df7
    Image:          gcr.io/kubecost1/frontend:prod-1.106.4
    Image ID:       gcr.io/kubecost1/frontend@sha256:6f17016118469efa9462bc2b773a35ee9fa19c3f15ccc41fd125a65134a3706e
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 31 Oct 2023 12:25:00 +1100
      Finished:     Tue, 31 Oct 2023 12:25:01 +1100
    Ready:          False
    Restart Count:  10
    Requests:
      cpu:      10m
      memory:   55Mi
    Liveness:   http-get http://:9003/healthz delay=30s timeout=1s period=10s #success=1 #failure=200
    Readiness:  http-get http://:9003/healthz delay=30s timeout=1s period=10s #success=1 #failure=200
    Environment:
      GET_HOSTS_FROM:  dns
    Mounts:
      /etc/nginx/conf.d/ from nginx-conf (rw)
      /tmp from tmp (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-xrn54 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True
[snip]
```
The `cost-analyzer-frontend` pod logs indicate a possible issue with `nginx` failing to resolve `cost-analyzer-grafana` service in the `default` namespace (why is it looking for one though, I have grafana disabled??):
```
$ kc logs -n kubecost kubecost-cost-analyzer-59b55cbb4f-ltm6l -c cost-analyzer-frontend --previous
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: can not modify /etc/nginx/conf.d/default.conf (read-only file system?)
/docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2023/10/31 01:30:03 [emerg] 1#1: host not found in upstream "cost-analyzer-grafana.default.svc" in /etc/nginx/conf.d/default.conf:45
nginx: [emerg] host not found in upstream "cost-analyzer-grafana.default.svc" in /etc/nginx/conf.d/default.conf:45
```

### Steps to reproduce

Helm values used:

```
global:
  prometheus:
    enabled: true
  grafana:
    enabled: false
    proxy: false

prometheus:
  nodeExporter:
    enabled: false
  serviceAccounts:
    nodeExporter:
      create: false
  kube-state-metrics:
    disabled: true

grafana:
  sidecar:
    dashboards:
      enabled: false
    datasources:
      enabled: false
```

### Expected behavior

Expect successful deployment.

### Logs

```Shell
Provided in the description.
```

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a bug impacting only the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by igoratencompass** [comment]
Fixed now, it was an issue with `global.grafana.proxy: false` not parsing properly.

```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: can not modify /etc/nginx/conf.d/default.conf (read-only file system?)
/docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2023/10/31 01:56:38 [notice] 1#1: using the "epoll" event method
2023/10/31 01:56:38 [notice] 1#1: nginx/1.25.2
2023/10/31 01:56:38 [notice] 1#1: built by gcc 12.2.1 20220924 (Alpine 12.2.1_git20220924-r10) 
2023/10/31 01:56:38 [notice] 1#1: OS: Linux 5.10.192-183.736.amzn2.x86_64
2023/10/31 01:56:38 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2023/10/31 01:56:38 [notice] 1#1: start worker processes
2023/10/31 01:56:38 [notice] 1#1: start worker process 21
2023/10/31 01:56:38 [notice] 1#1: start worker process 22
2023/10/31 01:56:38 [notice] 1#1: start worker process 23
2023/10/31 01:56:38 [notice] 1#1: start worker process 24
```

**Comment by sunnykrGupta** [comment]
Faced the same issue with `v1.107.0` as well.

**Comment by dwbrown2** [comment]
@sunnykrGupta can you share more about your configuration + any relevant logs?

**Comment by sunnykrGupta** [comment]
> @sunnykrGupta can you share more about your configuration + any relevant logs?

**Made an upgrade from Helm chart to version from 1.106.2 to 1.107.0.**

--- 

**Pod status**
```
cost-analyzer-85b677cf6b-qqltb           2/3     CrashLoopBackOff   3 (19s ago)   100s
```

**Pod container logs**
```
$ klogs -f $1 -c cost-analyzer-frontend
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: can not modify /etc/nginx/conf.d/default.conf (read-only file system?)
/docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2023/11/03 13:23:12 [emerg] 1#1: chown("/tmp/proxy_temp", 101) failed (1: Operation not permitted)
nginx: [emerg] chown("/tmp/proxy_temp", 101) failed (1: Operation not permitted)
```

**Below are my default values overrides:**

```

# Common 
eksIdentifier: &eksIdentifier "prod-xxx-02"
roleArn: &roleArn "arn:aws:iam::xxxxxx:role/kubecost-service-account"

# AMP configs
prometheusServerEndpoint: &prometheusServerEndpoint "http://localhost:8005/workspaces/ws-xxxxxx-eb00-xxxx-bee0-xxxxxxx"
remoteWriteService: &remoteWriteService "https://aps-workspaces.eu-west-1.amazonaws.com/workspaces/ws-xxxxxx-eb00-xxxx-bee0-xxxxxxx/api/v1/remote_write" 


global:
  amp:
    enabled: true
    prometheusServerEndpoint: *prometheusServerEndpoint
    remoteWriteService: *remoteWriteService
    sigv4:
      region: eu-west-1
  prometheus:
    enabled: false

sigV4Proxy:
  region: eu-west-1
  host: aps-workspaces.eu-west-1.amazonaws.com

kubecostProductConfigs:
  clusterName: *eksIdentifier
  negotiatedDiscount: "8"
  sharedNamespaces: "linkerd,newrelic"
  labelMappingConfigs:
    enabled: true
    owner_label: "owner"
    team_label: "squad"
    department_label: "tribe"
    product_label: "product"
    environment_label: "env"
  athenaProjectID: "xxxxxxxxx"
  athenaBucketName: "aws-athena-query-results-xxxxx-xxxxxx"
  athenaRegion: "eu-west-1"
  athenaDatabase: "of-xxxxxx-db"
  athenaTable: "xxxxxx"
  athenaWorkgroup: "xxxxxx"
  projectID: "xxxxxx"
  createServiceKeySecret: false
  spotLabel: "karpenter.sh/capacity-type"
  spotLabelValue: spot
  awsSpotDataBucket: kubecost-spot-xxxx-xxxxxx
  awsSpotDataPrefix: data
  awsSpotDataRegion: eu-west-1
  injectEmptyAWSConfig: true 
  # https://docs.kubecost.com/architecture/ksm-metrics
  # Disable few metrics from KSM (part of kubecost)
  # include `kube_*`, `node_*`, `kubecost_*`
  #
  metricsConfigs:
    disabledMetrics:
      - container_cpu_allocation gauge
      - container_gpu_allocation gauge
      - container_memory_allocation_bytes gauge
      - deployment_match_labels gauge
      - go_gc_duration_seconds summary
      - ....
      - ....
      - service_selector_labels gauge
      - statefulSet_match_labels gauge

prometheus:
  kube-state-metrics:
    disabled: false
  server:
    retention: 30d
    global:
      external_labels:
        cluster_id: *eksIdentifier
  # already enabled as core-components.
  nodeExporter:
    enabled: false
  kubeStateMetrics:
    enabled: false

networkCosts:
  enabled: false
  prometheusScrape: false
  config:
    services:
      amazon-web-services: true

serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: *roleArn

service:
  host: kubecost
  port: 80

kubecostDeployment:
  replicas: 1

# https://docs.kubecost.com/install-and-configure/install/cloud-integration#cloud-integration-configurations
kubecostModel:
  cloudCost:
    enabled: true
  # need to disable explicitly before v1.106.x
  kubecostModel:
    etlCloudUsage: false
  extraEnv:
   - name: LOG_LEVEL
     value: "error"
   - name: LOG_FORMAT
     value: "json"

# Kubecost will create a Persistent Volume Claim
# cost-analyzer's flat file database, (default 32Gi)
persistentVolume:
  enabled: true

```

**Comment by jessegoodier** [comment]
> > @sunnykrGupta can you share more about your configuration + any relevant logs?
> 
> **Made an upgrade from Helm chart to version from 1.106.2 to 1.107.0.**
> 
> **Pod status**
> 
> ```
> cost-analyzer-85b677cf6b-qqltb           2/3     CrashLoopBackOff   3 (19s ago)   100s
> ```
> 
> **Pod container logs**
> 
> ```
> $ klogs -f $1 -c cost-analyzer-frontend
> /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
> /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
> /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
> 10-listen-on-ipv6-by-default.sh: info: can not modify /etc/nginx/conf.d/default.conf (read-only file system?)
> /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
> /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
> /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
> /docker-entrypoint.sh: Configuration complete; ready for start up
> 2023/11/03 13:23:12 [emerg] 1#1: chown("/tmp/proxy_temp", 101) failed (1: Operation not permitted)
> nginx: [emerg] chown("/tmp/proxy_temp", 101) failed (1: Operation not permitted)
> ```
> 
> **Below are my default values overrides:**
> 
> ```
> 
> # Common 
> eksIdentifier: &eksIdentifier "prod-xxx-02"
> roleArn: &roleArn "arn:aws:iam::xxxxxx:role/kubecost-service-account"
> 
> # AMP configs
> prometheusServerEndpoint: &prometheusServerEndpoint "http://localhost:8005/workspaces/ws-xxxxxx-eb00-xxxx-bee0-xxxxxxx"
> remoteWriteService: &remoteWriteService "https://aps-workspaces.eu-west-1.amazonaws.com/workspaces/ws-xxxxxx-eb00-xxxx-bee0-xxxxxxx/api/v1/remote_write" 
> 
> 
> global:
>   amp:
>     enabled: true
>     prometheusServerEndpoint: *prometheusServerEndpoint
>     remoteWriteService: *remoteWriteService
>     sigv4:
>       region: eu-west-1
>   prometheus:
>     enabled: false
> 
> sigV4Proxy:
>   region: eu-west-1
>   host: aps-workspaces.eu-west-1.amazonaws.com
> 
> kubecostProductConfigs:
>   clusterName: *eksIdentifier
>   negotiatedDiscount: "8"
>   sharedNamespaces: "linkerd,newrelic"
>   labelMappingConfigs:
>     enabled: true
>     owner_label: "owner"
>     team_label: "squad"
>     department_label: "tribe"
>     product_label: "product"
>     environment_label: "env"
>   athenaProjectID: "xxxxxxxxx"
>   athenaBucketName: "aws-athena-query-results-xxxxx-xxxxxx"
>   athenaRegion: "eu-west-1"
>   athenaDatabase: "of-xxxxxx-db"
>   athenaTable: "xxxxxx"
>   athenaWorkgroup: "xxxxxx"
>   projectID: "xxxxxx"
>   createServiceKeySecret: false
>   spotLabel: "karpenter.sh/capacity-type"
>   spotLabelValue: spot
>   awsSpotDataBucket: kubecost-spot-xxxx-xxxxxx
>   awsSpotDataPrefix: data
>   awsSpotDataRegion: eu-west-1
>   injectEmptyAWSConfig: true 
>   # https://docs.kubecost.com/architecture/ksm-metrics
>   # Disable few metrics from KSM (part of kubecost)
>   # include `kube_*`, `node_*`, `kubecost_*`
>   #
>   metricsConfigs:
>     disabledMetrics:
>       - container_cpu_allocation gauge
>       - container_gpu_allocation gauge
>       - container_memory_allocation_bytes gauge
>       - deployment_match_labels gauge
>       - go_gc_duration_seconds summary
>       - ....
>       - ....
>       - service_selector_labels gauge
>       - statefulSet_match_labels gauge
> 
> prometheus:
>   kube-state-metrics:
>     disabled: false
>   server:
>     retention: 30d
>     global:
>       external_labels:
>         cluster_id: *eksIdentifier
>   # already enabled as core-components.
>   nodeExporter:
>     enabled: false
>   kubeStateMetrics:
>     enabled: false
> 
> networkCosts:
>   enabled: false
>   prometheusScrape: false
>   config:
>     services:
>       amazon-web-services: true
> 
> serviceAccount:
>   create: true
>   annotations:
>     eks.amazonaws.com/role-arn: *roleArn
> 
> service:
>   host: kubecost
>   port: 80
> 
> kubecostDeployment:
>   replicas: 1
> 
> # https://docs.kubecost.com/install-and-configure/install/cloud-integration#cloud-integration-configurations
> kubecostModel:
>   cloudCost:
>     enabled: true
>   # need to disable explicitly before v1.106.x
>   kubecostModel:
>     etlCloudUsage: false
>   extraEnv:
>    - name: LOG_LEVEL
>      value: "error"
>    - name: LOG_FORMAT
>      value: "json"
> 
> # Kubecost will create a Persistent Volume Claim
> # cost-analyzer's flat file database, (default 32Gi)
> persistentVolume:
>   enabled: true
> ```

Thanks for the information. 

Can you send the output of:
```sh
kubectl get pods kubecost-cost-analyzer-5dd5fb478c-p88zb -oyaml|grep securityContext -A8
```
And can you add this to your helm config?
```
global:
  securityContext:
    fsGroupChangePolicy: OnRootMismatch
```

We are trying to identify the combination of factors that cause this.

**Comment by sunnykrGupta** [comment]
```
$ kget po cost-analyzer-67b4bd696b-zqmw4 -o yaml | grep securityContext -A8
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
--
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
--
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
--
  securityContext:
    runAsUser: 0
  serviceAccount: cost-analyzer
  serviceAccountName: cost-analyzer
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
```

After making changes to helm values, I dont see changes being considered. I believe we are trying to modify these right? https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/templates/cost-analyzer-deployment-template.yaml#L72

**Comment by chipzoller** [comment]
I just did a fresh installation of 1.106.2 using the default values and performed an upgrade to 1.107.0 (also using default values) and I don't see this error.

Can you show the full manifest of the `cost-analyzer` Deployment after the upgrade to 1.107.0, please?

```sh
kubectl -n kubecost get deploy kubecost-cost-analyzer -o yaml
```

**Comment by jessegoodier** [comment]
I see the issue. 

The pod is running as root because:
```yaml
service:
  host: kubecost
  port: 80
```

We need to make the SCC change backwards compatible with this so this doesn't break other configs using that.

Stay tuned.

**Comment by jessegoodier** [comment]
@sunnykrGupta, my appologies for the issue.

We have a fix to this issue. We will add it to 1.107.1, but I do not have timing in that.

In the short term, you can use this tgz, which is 1.107.0 plus the fix for the root user.

```sh
helm upgrade kubecost \
  https://github.com/kubecost/cost-analyzer-helm-chart/raw/1.107-frontend-root-scc/cost-analyzer-1.107.0.tgz 
  -n kubecost
```

We are interested in your use case for using port 80, if you could share?

**Comment by sunnykrGupta** [comment]
> @sunnykrGupta, my appologies for the issue.
> 
> We have a fix to this issue. We will add it to 1.107.1, but I do not have timing in that.
> 
> In the short term, you can use this tgz, which is 1.107.0 plus the fix for the root user.
> 
> ```shell
> helm upgrade kubecost \
>   https://github.com/kubecost/cost-analyzer-helm-chart/raw/1.107-frontend-root-scc/cost-analyzer-1.107.0.tgz 
>   -n kubecost
> ```
> 
> We are interested in your use case for using port 80, if you could share?

Sorry for delayed response. I was Out of office. 

Yes, we are using same specs:
```
service:
  host: kubecost
  port: 80
```

**Comment by jessegoodier** [comment]
We have fixed in 1.107.1- which will be out late today or Monday based on final testing.

**Comment by chipzoller** [comment]
@sunnykrGupta, can you please explain to us why you're using port 80 for the front end? What is your use case here?

**Comment by sunnykrGupta** [comment]
No special reason to stick to `80`. We use ambassador for [routing management](https://www.getambassador.io/docs/emissary/latest/topics/using/intro-mappings#quick-example), we use default mapping template which expect service to listen to port `80`

```
---
kind:  Mapping
metadata:
  name:  kubecost-mapping
spec:
  host: ...
  ambassador_id: ...
  prefix: /
  service: {{ template "cost-analyzer.serviceName" . }}.{{ .Release.Namespace }}
```

Ofcourse, we can change it to `9090` if needed.
