### ISSUE TITLE
[Bug] Leader Follower doesn't work with SAML enabled

### ISSUE THREAD

**Issue by passionInfinite** [kubecost/cost-analyzer-helm-chart#2802]
### Kubecost Helm Chart Version

v1.107.1

### Kubernetes Version

v1.27

### Kubernetes Platform

AKS

### Description

We have SAML working previously without leader follower. We tried enabling the leader follower with StatedulSet option but that still doesn't work. The login keeps redirecting with infinite loop.

### Steps to reproduce

1. Enable leader-follower with replica count of 2.
2. Have SAML with correct settings and with RBAC enabled.
3. Visit the kubecost url to access dashboard.
4. It redirects to login with SAML once logged in it keeps redirecting. 

### Expected behavior

Dashboard must be visible correctly in addition to SAML working.

### Impact

Kubecost dashboard not visible.

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a bug impacting only the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
Can you show the values overrides you used?

**Comment by passionInfinite** [comment]
Sure @chipzoller 

```
   kubecostDeployment:
      statefulSet:
        enabled: true
      replicas: 2
      leaderFollower:
        enabled: true
 ```
 
 ```
 saml:
      enabled: true
      secretName: "kubecost-sso"
      idpMetadataURL: "FEDERATION_METADATA_URL?appid=APP_ID"
      appRootURL: "https://kubecost.test.com"
      authTimeout: 1440
      nameIDFormat: "urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified"
      audienceURI: "https://kubecost.test.com"
      rbac:
        enabled: true
        groups:
          - name: admin
            enabled: true # if admin is disabled, all SAML users will be able to make configuration changes to the kubecost frontend
            assertionName: "http://schemas.microsoft.com/ws/2008/06/identity/claims/role" # a SAML Assertion, one of whose elements has a value that matches on of the values in assertionValues
            assertionValues:
              - "admin"

          - name: readonly
            enabled: false # if readonly is disabled, all users authorized on SAML will default to readonly
            assertionName: "http://schemas.microsoft.com/ws/2008/06/identity/claims/role"
      customGroups:
        - assertionName: "http://schemas.microsoft.com/ws/2008/06/identity/claims/role"
 ```
