### ISSUE TITLE
[Bug] prom crashes with statefulset

### ISSUE THREAD

**Issue by FernandoMiguel** [kubecost/cost-analyzer-helm-chart#2919]
### Kubecost Helm Chart Version

1.108.1

### Kubernetes Version

1.27

### Kubernetes Platform

EKS

### Description

enabling statefulset generates a crash in prom

### Steps to reproduce

```yaml
apiVersion: v2
name: kubecost
description: A Helm chart that sets up Kubecost, Prometheus, and Grafana to monitor cloud costs.
annotations:
  "artifacthub.io/links": |
    - name: Homepage
      url: https://www.kubecost.com

# Application charts are a collection of templates that can be packaged into versioned archives to be deployed.
type: application

# The chart version. This version number should be incremented each time you make changes to the chart and its templates, including the app version.
version: 0.1.0

sources:
  - https://github.com/kubecost/cost-analyzer-helm-chart/releases
  - https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/Chart.yaml

dependencies:
  - name: cost-analyzer
    # repository: oci://public.ecr.aws/kubecost
    repository: https://kubecost.github.io/cost-analyzer
    version: 1.108.1
```

```yaml
cost-analyzer:
  global:
    grafana:
      enabled: true
      proxy: false
    prometheus:
      enabled: true

  # imageVersion: prod-1.105.0-rc.10
  kubecostToken: "xxxx"
  readonly: true

  ingress:
    enabled: true
    className: nginx-internal
    hosts:
      - kubecost

  serviceAccount:
    create: true # Set this to false if you're bringing your own service account.
    name: cur-athena

  kubecostProductConfigs:
    # these should be the same for every cluster
    athenaProjectID: "xxxxx" # The AWS AccountID where the Athena CUR is. Generally your masterpayer account
    masterPayerARN: "arn:aws:iam::xxxxx:role/Kubecost"
    spotLabel: karpenter.sh/capacity-type
    spotLabelValue: spot
    athenaBucketName: "s3://xxxxx"
    athenaRegion: us-east-1
    athenaDatabase: xxxx
    athenaTable: "xxxx"
    athenaWorkgroup: "primary" # The default workgroup in AWS is 'primary'

  kubecostDeployment:
    statefulSet:
      enabled: true
    deploymentStrategy:
      type: Recreate

  kubecostAggregator:
    # deployMethod determines how Aggregator is deployed. Current options are
    # "singlepod" (within cost-analyzer Pod) "statefulset" (separate
    # StatefulSet), and "disabled". Only use "disabled" if this is a secondary
    # Federated ETL cluster which does not need to answer queries.
    deployMethod: statefulset

  kubecostFrontend:
    image: public.ecr.aws/kubecost/frontend
    # fullImageName overrides the default image construction logic. The exact
    # image provided (registry, image, tag) will be used for the frontend.
    # fullImageName:
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "10m"
        memory: "1Gi"
      limits:
        memory: "1Gi"
    ipv6:
      enabled: false # disable if the cluster does not support ipv6

  kubecostModel:
    image: public.ecr.aws/kubecost/cost-model
    # fullImageName overrides the default image construction logic. The exact
    # image provided (registry, image, tag) will be used for cost-model.
    # fullImageName:
    imagePullPolicy: IfNotPresent
    warmCache: true
    warmSavingsCache: true
    etl: true
    # The total number of days the ETL storage will build
    etlStoreDurationDays: 120
    maxQueryConcurrency: 5
    # utcOffset represents a timezone in hours and minutes east (+) or west (-)
    # of UTC, itself, which is defined as +00:00.
    # See the tz database of timezones to look up your local UTC offset:
    # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
    utcOffset: "+00:00"
    resources:
      requests:
        cpu: 1
        memory: "2Gi"
      limits:
        memory: "2Gi"
    # CURs settings
    containerStatsEnabled: true
    cloudCost:
      enabled: true # Set to true to enable CloudCost view that gives you visibility of your Cloud provider resources cost
    etlCloudAsset: false # Set etlCloudAsset to false when cloudCost.enabled is true to reduce cluster resources consumption. Set to true to enable kubecost to include out-of-cluster cloud resources  (uses more memory)

  persistentVolume:
    enabled: true # Defaults True. Note that setting this to false means configurations will be wiped out on pod restart.
    size: 32Gi
    dbSize: 32.0Gi
    storageClass: "gp3"
    annotations:
      argocd.argoproj.io/sync-options: Replace=false

  service:
    type: ClusterIP
    port: 80
    targetPort: 9090
    labels: {}
    annotations: {}

  kubecostMetrics:
    emitPodAnnotations: true
    emitNamespaceAnnotations: true
    emitKsmV1Metrics: true # emit all KSM metrics in KSM v1. https://github.com/kubecost/docs/blob/main/ksm-metrics.md
    # emitKsmV1MetricsOnly: false # emit only the KSM metrics missing from KSM v2. Advanced users only. https://github.com/kubecost/docs/blob/main/ksm-metrics.md

    exporter:
      enabled: true
      # Adds the default Prometheus scrape annotations to the metrics exporter service.
      # Set to false and use service.annotations (below) to set custom scrape annotations.
      prometheusScrape: true
      resources:
        requests:
          cpu: "200m"
          memory: "100Mi"
        limits:
          memory: "100Mi"
      service:
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: ["tcp-metrics", "tcp-model"]
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - cost-analyzer
              topologyKey: "kubernetes.io/hostname"

  prometheus:
    server:
      image:
        repository: public.ecr.aws/kubecost/prometheus
        # tag: v2.35.0
      resources:
        limits:
          memory: 2Gi
        requests:
          cpu: 500m
          memory: 1Gi
      statefulSet:
        ## If true, use a statefulset instead of a deployment for pod management.
        ## This allows to scale replicas to more than 1 pod
        ##
        enabled: true
      global:
        scrape_interval: 1m
      persistentVolume:
        enabled: true
        size: 32Gi
        storageClass: "gp3"
        annotations:
          argocd.argoproj.io/sync-options: Replace=false

    configmapReload:
      prometheus:
        enabled: true
        image:
          repository: public.ecr.aws/kubecost/prometheus-config-reloader
        resources:
          limits:
            memory: 64Mi
          requests:
            cpu: 100m
            memory: 64Mi
        nodeSelector:
          kubernetes.io/arch: amd64

    ## this was removed in https://github.com/kubecost/cost-analyzer-helm-chart/pull/2912/files
    kube-state-metrics:
      disabled: false
      resources:
        limits:
          memory: 30Mi
        requests:
          cpu: 100m
          memory: 30Mi

    nodeExporter:
      enabled: false

    serviceAccounts:
      # nodeExporter:
      #   create: false
      server:
        create: true
        # name: kubecost-serviceaccount-thanos

  networkCosts:
    enabled: true
    resources:
      limits: # remove the limits by setting limits: {}
        # cpu: 500m  # can be less, will depend on cluster size
        # memory: it is not recommended to set a memory limit
        memory: 40Mi
      requests:
        cpu: 50m
        memory: 35Mi
    tolerations:
      - operator: "Exists"
    config:
      services:
        amazon-web-services: true
        # google-cloud-services: true
        # azure-cloud-services: true

  grafana:
    ingress:
      enabled: true
      className: nginx-internal
      hosts:
        - kubecost-grafana
    # grafana.ini:
    #   server:
    #     serve_from_sub_path: false
    image:
      pullSecrets:
        - dockerhub.io
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    sidecar:
      image:
        repository: ghcr.io/kiwigrid/k8s-sidecar
      resources:
        limits:
          memory: 128Mi
        requests:
          cpu: 50m
          memory: 90Mi
```

### Expected behavior

for correct creation of service

### Impact

prom goes into a crashloop

### Screenshots

![image](https://github.com/kubecost/cost-analyzer-helm-chart/assets/168366/62a90661-038c-453f-8720-13664249b680)

### Logs

```Shell
ts=2024-01-09T13:56:55.379Z caller=main.go:583 level=info msg="Starting Prometheus Server" mode=server version="(version=2.48.1, branch=HEAD, revision=63894216648f0d6be310c9d16fb48293c45c9310"
ts=2024-01-09T13:56:55.379Z caller=main.go:588 level=info build_context="(go=go1.21.5, platform=linux/amd64, user=root@71f108ff5632, date=20231208-23:33:22, tags=netgo,builtinassets,stringlabels)"
ts=2024-01-09T13:56:55.379Z caller=main.go:589 level=info host_details="(Linux 6.1.61 #1 SMP PREEMPT_DYNAMIC Wed Dec 13 02:53:59 UTC 2023 x86_64 kubecost-canary-fe-prometheus-server-0 (none))"
ts=2024-01-09T13:56:55.379Z caller=main.go:590 level=info fd_limits="(soft=1048576, hard=1048576)"
ts=2024-01-09T13:56:55.379Z caller=main.go:591 level=info vm_limits="(soft=unlimited, hard=unlimited)"
ts=2024-01-09T13:56:55.379Z caller=query_logger.go:93 level=error component=activeQueryTracker msg="Error opening query log file" file=/data/queries.active err="open /data/queries.active: permission denied"
panic: Unable to create mmap-ed active query log
goroutine 1 [running]:
github.com/prometheus/prometheus/promql.NewActiveQueryTracker({0x7ffe896c3530, 0x5}, 0x1, {0x3e94bc0, 0xc0009744b0})
    /app/promql/query_logger.go:123 +0x411
main.main()
    /app/cmd/prometheus/main.go:645 +0x7812
Stream closed EOF for sre-kubecost-system/kubecost-canary-fe-prometheus-server-0 (prometheus-server)
```

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a bug impacting only the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by dwbrown2** [comment]
This looks to be related to the Prometheus deployment. Potentially a disk permissions issue?

@AjayTripathy can you help triage?

**Comment by chipzoller** [comment]
I tested this using your values file with the only modifications being eliminating the subchart aspect and removing the storage class and I cannot reproduce the issue. The PVC is bound and all Prometheus Pods start. There are no errors observed in any of the Prometheus container logs.

```sh
$ k -n kubecost get po
NAME                                      READY   STATUS    RESTARTS   AGE
kubecost-network-costs-7wrs2              1/1     Running   0          5m33s
kubecost-network-costs-t88qh              1/1     Running   0          5m33s
kubecost-grafana-77d5b6bc8f-tzj8v         2/2     Running   0          5m33s
kubecost-metrics-7fb79944dd-nx2gc         1/1     Running   0          5m33s
kubecost-cost-analyzer-78fd9cf87b-2zqtd   2/2     Running   0          5m33s
kubecost-prometheus-server-0              2/2     Running   0          5m33s
```

```log
$ stern -n kubecost kubecost-prome
+ kubecost-prometheus-server-0 › prometheus-server-configmap-reload
+ kubecost-prometheus-server-0 › prometheus-server
kubecost-prometheus-server-0 prometheus-server-configmap-reload level=info ts=2024-01-14T16:22:08.670003127Z caller=main.go:127 msg="Starting prometheus-config-reloader" version="(version=0.69.1, branch=refs/tags/v0.69.1, revision=941b9e98d4ae5faa952af250e23c31c56cc1190c)"
kubecost-prometheus-server-0 prometheus-server-configmap-reload level=info ts=2024-01-14T16:22:08.670038728Z caller=main.go:128 build_context="(go=go1.21.4, platform=linux/amd64, user=Action-Run-ID-6812497076, date=20231109-15:19:57, tags=unknown)"
kubecost-prometheus-server-0 prometheus-server-configmap-reload level=info ts=2024-01-14T16:22:08.670292311Z caller=reloader.go:237 msg="started watching config file and directories for changes" cfg= out= dirs=/etc/config
kubecost-prometheus-server-0 prometheus-server-configmap-reload level=info ts=2024-01-14T16:25:08.673402345Z caller=reloader.go:376 msg="Reload triggered" cfg_in= cfg_out= watched_dirs=/etc/config
kubecost-prometheus-server-0 prometheus-server ts=2024-01-14T16:22:14.709Z caller=main.go:583 level=info msg="Starting Prometheus Server" mode=server version="(version=2.48.1, branch=HEAD, revision=63894216648f0d6be310c9d16fb48293c45c9310)"
kubecost-prometheus-server-0 prometheus-server ts=2024-01-14T16:22:14.709Z caller=main.go:588 level=info build_context="(go=go1.21.5, platform=linux/amd64, user=root@71f108ff5632, date=20231208-23:33:22, tags=netgo,builtinassets,stringlabels)"
kubecost-prometheus-server-0 prometheus-server ts=2024-01-14T16:22:14.710Z caller=main.go:589 level=info host_details="(Linux 5.15.133.1-microsoft-standard-WSL2 #1 SMP Thu Oct 5 21:02:42 UTC 2023 x86_64 kubecost-prometheus-server-0 )"
kubecost-prometheus-server-0 prometheus-server ts=2024-01-14T16:22:14.710Z caller=main.go:590 level=info fd_limits="(soft=1048576, hard=1048576)"
kubecost-prometheus-server-0 prometheus-server ts=2024-01-14T16:22:14.710Z caller=main.go:591 level=info vm_limits="(soft=unlimited, hard=unlimited)"
kubecost-prometheus-server-0 prometheus-server ts=2024-01-14T16:22:14.710Z caller=web.go:566 level=info component=web msg="Start listening for connections" address=0.0.0.0:9090
kubecost-prometheus-server-0 prometheus-server ts=2024-01-14T16:22:14.711Z caller=main.go:1024 level=info msg="Starting TSDB ..."
kubecost-prometheus-server-0 prometheus-server ts=2024-01-14T16:22:14.711Z caller=tls_config.go:274 level=info component=web msg="Listening on" address=[::]:9090
kubecost-prometheus-server-0 prometheus-server ts=2024-01-14T16:22:14.711Z caller=tls_config.go:277 level=info component=web msg="TLS is disabled." http2=false address=[::]:9090
kubecost-prometheus-server-0 prometheus-server ts=2024-01-14T16:22:14.713Z caller=head.go:601 level=info component=tsdb msg="Replaying on-disk memory mappable chunks if any"
kubecost-prometheus-server-0 prometheus-server ts=2024-01-14T16:22:14.713Z caller=head.go:682 level=info component=tsdb msg="On-disk memory mappable chunks replay completed" duration=1.23µs
kubecost-prometheus-server-0 prometheus-server ts=2024-01-14T16:22:14.713Z caller=head.go:690 level=info component=tsdb msg="Replaying WAL, this may take a while"
kubecost-prometheus-server-0 prometheus-server ts=2024-01-14T16:22:14.713Z caller=head.go:761 level=info component=tsdb msg="WAL segment loaded" segment=0 maxSegment=0
kubecost-prometheus-server-0 prometheus-server ts=2024-01-14T16:22:14.713Z caller=head.go:798 level=info component=tsdb msg="WAL replay completed" checkpoint_replay_duration=12.15µs wal_replay_duration=133.573µs wbl_replay_duration=110ns total_replay_duration=156.353µs
kubecost-prometheus-server-0 prometheus-server ts=2024-01-14T16:22:14.714Z caller=main.go:1045 level=info fs_type=EXT4_SUPER_MAGIC
kubecost-prometheus-server-0 prometheus-server ts=2024-01-14T16:22:14.714Z caller=main.go:1048 level=info msg="TSDB started"
kubecost-prometheus-server-0 prometheus-server ts=2024-01-14T16:22:14.714Z caller=main.go:1230 level=info msg="Loading configuration file" filename=/etc/config/prometheus.yml
kubecost-prometheus-server-0 prometheus-server ts=2024-01-14T16:22:14.715Z caller=kubernetes.go:329 level=info component="discovery manager scrape" discovery=kubernetes config=kubernetes-nodes-cadvisor msg="Using pod service account via in-cluster config"
kubecost-prometheus-server-0 prometheus-server ts=2024-01-14T16:22:14.715Z caller=kubernetes.go:329 level=info component="discovery manager scrape" discovery=kubernetes config=kubernetes-service-endpoints msg="Using pod service account via in-cluster config"
kubecost-prometheus-server-0 prometheus-server ts=2024-01-14T16:22:14.715Z caller=kubernetes.go:329 level=info component="discovery manager scrape" discovery=kubernetes config=kubecost-networking msg="Using pod service account via in-cluster config"
kubecost-prometheus-server-0 prometheus-server ts=2024-01-14T16:22:14.715Z caller=main.go:1267 level=info msg="Completed loading of configuration file" filename=/etc/config/prometheus.yml totalDuration=1.46257ms db_storage=490ns remote_storage=780ns web_handler=550ns query_engine=720ns scrape=117.873µs scrape_sd=386.518µs notify=780ns notify_sd=1.01µs rules=301.386µs tracing=4.22µs
kubecost-prometheus-server-0 prometheus-server ts=2024-01-14T16:22:14.715Z caller=main.go:1009 level=info msg="Server is ready to receive web requests."
kubecost-prometheus-server-0 prometheus-server ts=2024-01-14T16:22:14.715Z caller=manager.go:1012 level=info component="rule manager" msg="Starting rule manager..."
kubecost-prometheus-server-0 prometheus-server ts=2024-01-14T16:25:08.670Z caller=main.go:1230 level=info msg="Loading configuration file" filename=/etc/config/prometheus.yml
kubecost-prometheus-server-0 prometheus-server ts=2024-01-14T16:25:08.672Z caller=kubernetes.go:329 level=info component="discovery manager scrape" discovery=kubernetes config=kubecost-networking msg="Using pod service account via in-cluster config"
kubecost-prometheus-server-0 prometheus-server ts=2024-01-14T16:25:08.672Z caller=kubernetes.go:329 level=info component="discovery manager scrape" discovery=kubernetes config=kubernetes-nodes-cadvisor msg="Using pod service account via in-cluster config"
kubecost-prometheus-server-0 prometheus-server ts=2024-01-14T16:25:08.672Z caller=kubernetes.go:329 level=info component="discovery manager scrape" discovery=kubernetes config=kubernetes-service-endpoints msg="Using pod service account via in-cluster config"
kubecost-prometheus-server-0 prometheus-server ts=2024-01-14T16:25:08.673Z caller=main.go:1267 level=info msg="Completed loading of configuration file" filename=/etc/config/prometheus.yml totalDuration=2.399479ms db_storage=1.79µs remote_storage=1.211µs web_handler=660ns query_engine=940ns scrape=491.37µs scrape_sd=426.938µs notify=720ns notify_sd=790ns rules=562.272µs tracing=2.62µs
```

<details><summary>Values file for confirmation</summary>
<p>

```yaml
global:
  grafana:
    enabled: true
    proxy: false
  prometheus:
    enabled: true

# imageVersion: prod-1.105.0-rc.10
kubecostToken: "xxxx"
readonly: true

ingress:
  enabled: true
  className: nginx-internal
  hosts:
    - kubecost

serviceAccount:
  create: true # Set this to false if you're bringing your own service account.
  name: cur-athena

kubecostProductConfigs:
  # these should be the same for every cluster
  athenaProjectID: "xxxxx" # The AWS AccountID where the Athena CUR is. Generally your masterpayer account
  masterPayerARN: "arn:aws:iam::xxxxx:role/Kubecost"
  spotLabel: karpenter.sh/capacity-type
  spotLabelValue: spot
  athenaBucketName: "s3://xxxxx"
  athenaRegion: us-east-1
  athenaDatabase: xxxx
  athenaTable: "xxxx"
  athenaWorkgroup: "primary" # The default workgroup in AWS is 'primary'

kubecostDeployment:
  statefulSet:
    enabled: true
  deploymentStrategy:
    type: Recreate

kubecostAggregator:
  # deployMethod determines how Aggregator is deployed. Current options are
  # "singlepod" (within cost-analyzer Pod) "statefulset" (separate
  # StatefulSet), and "disabled". Only use "disabled" if this is a secondary
  # Federated ETL cluster which does not need to answer queries.
  deployMethod: statefulset

kubecostFrontend:
  image: public.ecr.aws/kubecost/frontend
  # fullImageName overrides the default image construction logic. The exact
  # image provided (registry, image, tag) will be used for the frontend.
  # fullImageName:
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "10m"
      memory: "1Gi"
    limits:
      memory: "1Gi"
  ipv6:
    enabled: false # disable if the cluster does not support ipv6

kubecostModel:
  image: public.ecr.aws/kubecost/cost-model
  # fullImageName overrides the default image construction logic. The exact
  # image provided (registry, image, tag) will be used for cost-model.
  # fullImageName:
  imagePullPolicy: IfNotPresent
  warmCache: true
  warmSavingsCache: true
  etl: true
  # The total number of days the ETL storage will build
  etlStoreDurationDays: 120
  maxQueryConcurrency: 5
  # utcOffset represents a timezone in hours and minutes east (+) or west (-)
  # of UTC, itself, which is defined as +00:00.
  # See the tz database of timezones to look up your local UTC offset:
  # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  utcOffset: "+00:00"
  resources:
    requests:
      cpu: 1
      memory: "2Gi"
    limits:
      memory: "2Gi"
  # CURs settings
  containerStatsEnabled: true
  cloudCost:
    enabled: true # Set to true to enable CloudCost view that gives you visibility of your Cloud provider resources cost
  etlCloudAsset: false # Set etlCloudAsset to false when cloudCost.enabled is true to reduce cluster resources consumption. Set to true to enable kubecost to include out-of-cluster cloud resources  (uses more memory)

persistentVolume:
  enabled: true # Defaults True. Note that setting this to false means configurations will be wiped out on pod restart.
  size: 32Gi
  dbSize: 32.0Gi
  annotations:
    argocd.argoproj.io/sync-options: Replace=false

service:
  type: ClusterIP
  port: 80
  targetPort: 9090
  labels: {}
  annotations: {}

kubecostMetrics:
  emitPodAnnotations: true
  emitNamespaceAnnotations: true
  emitKsmV1Metrics: true # emit all KSM metrics in KSM v1. https://github.com/kubecost/docs/blob/main/ksm-metrics.md
  # emitKsmV1MetricsOnly: false # emit only the KSM metrics missing from KSM v2. Advanced users only. https://github.com/kubecost/docs/blob/main/ksm-metrics.md

  exporter:
    enabled: true
    # Adds the default Prometheus scrape annotations to the metrics exporter service.
    # Set to false and use service.annotations (below) to set custom scrape annotations.
    prometheusScrape: true
    resources:
      requests:
        cpu: "200m"
        memory: "100Mi"
      limits:
        memory: "100Mi"
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: ["tcp-metrics", "tcp-model"]
    affinity:
      podAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - cost-analyzer
            topologyKey: "kubernetes.io/hostname"

prometheus:
  server:
    image:
      repository: public.ecr.aws/kubecost/prometheus
      # tag: v2.35.0
    resources:
      limits:
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi
    statefulSet:
      ## If true, use a statefulset instead of a deployment for pod management.
      ## This allows to scale replicas to more than 1 pod
      ##
      enabled: true
    global:
      scrape_interval: 1m
    persistentVolume:
      enabled: true
      size: 32Gi
      annotations:
        argocd.argoproj.io/sync-options: Replace=false

  configmapReload:
    prometheus:
      enabled: true
      image:
        repository: public.ecr.aws/kubecost/prometheus-config-reloader
      resources:
        limits:
          memory: 64Mi
        requests:
          cpu: 100m
          memory: 64Mi
      nodeSelector:
        kubernetes.io/arch: amd64

  ## this was removed in https://github.com/kubecost/cost-analyzer-helm-chart/pull/2912/files
  kube-state-metrics:
    disabled: false
    resources:
      limits:
        memory: 30Mi
      requests:
        cpu: 100m
        memory: 30Mi

  nodeExporter:
    enabled: false

  serviceAccounts:
    # nodeExporter:
    #   create: false
    server:
      create: true
      # name: kubecost-serviceaccount-thanos

networkCosts:
  enabled: true
  resources:
    limits: # remove the limits by setting limits: {}
      # cpu: 500m  # can be less, will depend on cluster size
      # memory: it is not recommended to set a memory limit
      memory: 40Mi
    requests:
      cpu: 50m
      memory: 35Mi
  tolerations:
    - operator: "Exists"
  config:
    services:
      amazon-web-services: true
      # google-cloud-services: true
      # azure-cloud-services: true

grafana:
  ingress:
    enabled: true
    className: nginx-internal
    hosts:
      - kubecost-grafana
  # grafana.ini:
  #   server:
  #     serve_from_sub_path: false
  image:
    pullSecrets:
      - dockerhub.io
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  sidecar:
    image:
      repository: ghcr.io/kiwigrid/k8s-sidecar
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 90Mi
```

</p>
</details>
