### ISSUE TITLE
Kubecost doesn`t forward to the external grafana instance.

### ISSUE THREAD

**Issue by ShinHiragy** [kubecost/cost-analyzer-helm-chart#2952]
Good morning everybody. 

I need to implement Kubecost on our Cluster. Now, it is not a must-have, but i would see it as an big advantage, if you can reach the grafana dashboard without any problems threw kubecost. 

Now, it comes to the problem!

At this point, where i want to open the dashboard threw kubecost, it shows only a white page without any type of content. Exists a workaround for this problem?

I am followed the documentation and both ways doesn`t work. :( 

If you need additional informations:

As IaC i am using Pulumi in the current version
Kubernetes is running on the Version 1.24
I plan to use the 1.106.5 Version of Kubecost

I wish all of you a beautiful day and a perfect year :)

**Comment by chipzoller** [comment]
Please provide details on how you installed Kubecost. If it was Helm, please provide the complete values you used and how you tested this behavior out.

**Comment by ShinHiragy** [comment]
Thank you very much for this fast response. 

Yes, i use the helm-chart to install kubecost to our Kubernetes. 

In the first way, i tried to use the first option to implement the external grafana with the following values:



```yaml
kubecostProductConfigs: {
grafanaURL: "grafana.beispielerus.beispiel.de" 
},
```

The result of this was, that this method doesn`t work in this case. 

And yes, i tried the implementation of grafana with the second option, but the result was the same

The used values for the second way to grafana :)

```yaml
grafana: {
    enabled: false,
    domainName:  "grafana.beispielerus.beispiel.de",
    proxy: false
},
```

```yaml
grafana:{
    sidecar:{
        dashboards:{
            enabled: true,
            searchNamespace: ["ALL"]
        },
        datasources: {
            enabled: false
         }
    }
},  
```
