### ISSUE TITLE
Addition of shared labels and shared label values

### ISSUE THREAD

**Issue by ShinHiragy** [kubecost/cost-analyzer-helm-chart#2999]
Good morning, everybody.

I have a small question, and I hope that you can give me a helpful answer.

Is it possible to add the values through the use of the values.yaml-file:

- shared Labels
- shared label values

It is part of the shared cost section in the settings-area

**Comment by chipzoller** [comment]
There is a `global` section allowing you to add both labels and annotations if that's what you mean.

**Comment by thomasvn** [comment]
Correct I think we would need a feature request for this.

The UI supports setting "Shared Labels" and "Shared Label Values", however it's not configurable via Helm chart. Only the following are currently configurable:

```yaml
kubecostProductConfigs:
  sharedNamespaces: ""
  sharedOverhead: ""
  shareTenancyCosts: true
```
