### ISSUE TITLE
[Bug] When setting cloudIntegrationSecret, if it is not exactly `cloud-integration` some containers fail to start

### ISSUE THREAD

**Issue by jcmuller** [kubecost/cost-analyzer-helm-chart#3046]
### Kubecost Helm Chart Version

2.0.0

### Kubernetes Version

1.24

### Kubernetes Platform

Bare metal

### Description

I was testing some changes and set `kubecostProductConfigs.cloudIntegrationSecret` to a value other than `cloud-integration`, the cost analyzer pod failed to start.

### Steps to reproduce

1. set `kubecostProductConfigs.cloudIntegrationSecret` to a value other than `cloud-integration`,
2. fail

### Expected behavior

Not fail.

### Impact

Nothing at the moment, since I renamed the secret `cloud-integration`

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a bug impacting only the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by jessegoodier** [comment]
thanks for the detail @jcmuller, we will get this cleaned up.

**Comment by chipzoller** [comment]
The issue here is not the name of the Secret but that the Secret has a key named precisely `cloud-integration.json`.

**Comment by jcmuller** [comment]
Right. The alternately named secret did have the right key, `cloud-integration.json`.

So, you can run 
```
❯ helm template kubecost cost-analyzer --repo https://kubecost.github.io/cost-analyzer --version 2.0.0 --set kubecostProductConfigs.cloudIntegrationSecret=foobar
```

The trimmed output with the interesting fields:
```yaml
---
# Source: cost-analyzer/templates/cost-analyzer-deployment-template.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubecost-cost-analyzer
spec:
  template:
    spec:
      volumes:
        - name: cloud-integration
          secret:
            secretName: foobar
            items:
              - key: cloud-integration.json
                path: cloud-integration.json
      containers:
        - name: cost-model
          volumeMounts:
            - name: cloud-integration
              mountPath: /var/configs/cloud-integration
        - name: cloud-cost
          volumeMounts:
            - name: foobar
              mountPath: /var/configs/cloud-integration
```

As we can see, the problem is that the name of the secret is used incorrectly in the `cloud-cost` container in the `kubecost-cost-analyzer` deployment.
