### ISSUE TITLE
[Feature] Allow embedded file configs in values

### ISSUE THREAD

**Issue by jessegoodier** [kubecost/cost-analyzer-helm-chart#3047]
### Problem Statement

It is possible to pass a configuration via helm values without using "extraObjects" or creating out-of-band secrets/configmaps.
Kubecost helm chart does not support this for many of the configuration items we require for integrating with cloud billing/object-storage/etc.

Benefits for embedding the configs:
1. Simplicity
2. Less mistakes (foot guns)
3. Easier to support for future users that take over the role
4. single file "advanced" configs

### Solution Description

Example:
https://github.com/bitnami/charts/blob/main/bitnami/thanos/templates/objstore-secret.yaml#L14
values file is simply:
```yaml
objstoreConfig: |-
  type: S3
  config:
    bucket: my-bucket
    region: eu-central-1
    endpoint: s3.amazonaws.com
```

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a feature request only for the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.
