### ISSUE TITLE
[Bug] Deploying 2.0.2 with a cloud-integration secret

### ISSUE THREAD

**Issue by jcmuller** [kubecost/cost-analyzer-helm-chart#3106]
### Kubecost Helm Chart Version

2.0.2

### Kubernetes Version

1.24

### Kubernetes Platform

Other (specify in description)

### Description

Kubernetes running on self managed EC2 instances.

The cloud-integrations secret exists, with the correct data, but the deployment fails with:
```
rror: execution error at (cost-analyzer/templates/NOTES.txt:5:4): The cloud integration secret 'cloud-integration' does not exist or does not contain the expected key 'cloud-integration.json' Use --debug flag to render out invalid YAML
```

```
❯ k get secret cloud-integration -o yaml                                                                                                                                                          
apiVersion: v1
data:
  cloud-integration.json: ewogICJhd3Mi......
kind: Secret
metadata:
  name: cloud-integration
  namespace: kubecost
type: Opaque
....
```

### Steps to reproduce

1. Do a helm release including the cloud-integration secret
2. Deployment fails.

### Expected behavior

1. Deployment succeeds

### Impact

I can't get kubecost deployed at the momment. I was trying to upgrade to see if an issue with the aggregator container would go away and I could show kubecost to my superiors, so that we can make a decision whether to buy the product.

### Screenshots

![image](https://github.com/kubecost/cost-analyzer-helm-chart/assets/208500/161ffb49-174a-41f3-9379-60e105848cc8)

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a bug impacting only the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.
