### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by mpostument** [kubecost/cost-analyzer-helm-chart#3114]
### Kubecost Helm Chart Version

cost-analyzer-1.108.1

### Kubernetes Version

1.25

### Kubernetes Platform

EKS

### Description

I have deployed kube-state-metrics to cluster. And i want to disable ksm emision on kubecost side.
Here is my helm chart config

```yaml
  prometheus:
    nodeExporter:
      enabled: false
    kubeStateMetrics:
      enabled: false
    kube-state-metrics:
      disabled: true

    kubecostMetrics:
      emitKsmV1Metrics: false
      emitKsmV1MetricsOnly: true
```

When kubeconfig is deployed i see that config i set

```json
        "kubecostMetrics": {
            "emitKsmV1Metrics": false,
            "emitKsmV1MetricsOnly": true
        },
```

When i open kubecost metrics endpoint i see metrics like

```
kube_job_status_failed
```

But per [this](https://docs.kubecost.com/architecture/ksm-metrics#external-ksm-deployments-resulting-in-duplicated-metrics) doc, those metrics should be disabled 

### Steps to reproduce

1. Disable KSM emission 
2. Deploy kubecost and verify that kube state metrics is not present on kubecost

### Expected behavior

1. No kms v2 metrics is present generated by kubecost

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a bug impacting only the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.
