### ISSUE TITLE
[Bug] fullnameOverride is not working with service name

### ISSUE THREAD

**Issue by mpostument** [kubecost/cost-analyzer-helm-chart#3119]
### Kubecost Helm Chart Version

1.106.4

### Kubernetes Version

1.25

### Kubernetes Platform

EKS

### Description

In helm chart i have defined `fullnameOverride: "observability-v2-cost-analyzer"`. But when i deploy chart service name is using Release.Name and not fullnameOverride

```shell
release-acab958dd6befd88f11121130f243665a1f0b8a3-cost-analyzer
```

### Steps to reproduce

1. Set fullnameOverride and deploy

### Expected behavior

Service name have name the same as value of fullnameOverride

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a bug impacting only the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
Please show the full values you used.

**Comment by mpostument** [comment]
@chipzoller here is my config
```yaml
  fullnameOverride: "observability-v2-cost-analyzer"
  enabled: true
  global:
    # zone: cluster.local (use only if your DNS server doesn't live in the same zone as kubecost)
    # Amazon Managed Service for Prometheus
    amp:
      enabled: true  # If true, kubecost will be configured to remote_write and query from Amazon Managed Service for Prometheus.
      prometheusServerEndpoint: http://localhost:8005/workspaces/ID/  # The prometheus service endpoint used by kubecost. The calls are forwarded through the SigV4Proxy side car to the AMP workspace.
      remoteWriteService: *prometheus_endpoint
      sigv4:
        region: *region
    grafana:
      domainName: DNS
      enabled: false
    prometheus:
      enabled: false


  serviceAccount:
    name: observability-v2-cost-analyzer
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::ROLE

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      kubernetes.io/ingress.class: nginx
    hosts:
      - DNS
    tls:
      - secretName: kubecost-ingress-tls
        hosts:
          - DNS
  prometheus:
    nodeExporter:
      enabled: false
    kubeStateMetrics:
      enabled: false
    kube-state-metrics:
      disabled: true

  kubecostMetrics:
    emitKsmV1Metrics: false
    emitKsmV1MetricsOnly: true

  kubecostFrontend:
    model:
      fqdn: 0.0.0.0:9003

  sigV4Proxy:
    region: *region
    host: *aps_endpoint

  kubecostModel:
    resources:
      requests:
        cpu: 1024m
        memory: 2Gi
      limits:
        cpu: 2048m
        memory: 4Gi
```
