### ISSUE TITLE
[Bug] Kubecost-based KSM deployment can no longer be deployed

### ISSUE THREAD

**Issue by therealdwright** [kubecost/cost-analyzer-helm-chart#3246]
### Kubecost Helm Chart Version

v2.1.1

### Kubernetes Version

1.25.16

### Kubernetes Platform

EKS

### Description

Since the introduction of #2912 you can no longer ship a kube-state-metrics with kubecost as described in [the documentation](https://docs.kubecost.com/architecture/ksm-metrics#enabling-kubecost-based-ksm-deployment).

This has been raised previously in #3114 which was closed as completed.

### Steps to reproduce

1. Check out v2.1.1 and change to charts directory
2. Add the values as described in the documentation (`prometheus.kubeStateMetrics.enabled: true` and `prometheus.kube-state-metrics.disabled: false`
3. Render the template with `helm template`
4. Note that there is no `kubecost-kube-state-metrics` deployment rendered

### Expected behavior

When following the docs "Enabling Kubecost-based KSM deployment", kubecost has its dedicated kube-state-metrics deployment rendered.

### Impact

Prevents upgrades to v2.x for users who wish to use a dedicated KSM for kubecost.

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a bug impacting only the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by teevans** [comment]
@jessegoodier - I think you probably have the latest understanding here

**Comment by jessegoodier** [comment]
We will need to update our docs. KSM was removed from the chart because kubecost emits all KSM metrics it requires, and we are constantly patching utilities that are not required.

@therealdwright- Can you confirm you are using the kubecost bundled prometheus server?

And -would a solution of installing the kube-state-metrics helm chart and having kubecost-bundled prometheus scrape this work for you?

basic config would be:

```sh
helm install kube-state-metrics \
 --repo https://prometheus-community.github.io/helm-charts kube-state-metrics \
 --namespace kube-state-metrics --create-namespace
```

and add to kubecost helm values:

```yaml
prometheus:
  extraScrapeConfigs: |
    - job_name: kubecost
      honor_labels: true
      scrape_interval: 1m
      scrape_timeout: 60s
      metrics_path: /metrics
      scheme: http
      dns_sd_configs:
      - names:
        - {{ template "cost-analyzer.serviceName" . }}
        type: 'A'
        port: 9003
    - job_name: kubecost-networking
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
      # Scrape only the the targets matching the following metadata
        - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_instance]
          action: keep
          regex:  kubecost
        - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
          action: keep
          regex:  network-costs
    - job_name: kube-state-metrics
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
      # Scrape only the the targets matching the following metadata
        - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_instance]
          action: keep
          regex:  kube-state-metrics
        - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
          action: keep
          regex:  kube-state-metrics
```
