### ISSUE TITLE
[Bug] Label mapping configs do not work out of the box

### ISSUE THREAD

**Issue by dgaffuri** [kubecost/cost-analyzer-helm-chart#3264]
### Kubecost Helm Chart Version

2.1.1

### Kubernetes Version

1.29.1

### Kubernetes Platform

EKS

### Description

Defining and enabling kubecostProductConfigs.labelMappingConfigs creates the config map named by default "app-configs", but the config map is mounted and passed as APP_CONFIGMAP_NAME environment variable to cost-model only if the undocumented appConfigmapName value is defined too

### Steps to reproduce

1. set kubecostProductConfigs.labelMappingConfigs to `cluster_external_label: "cluster-name"`
2. set kubecostProductConfigs.labelMappingConfigs.enabled to `true`
3. deploy the chart
4. open Monitor, Cloud Costs Explorer in the frontend

### Expected behavior

external costs of resources tagged with "cluster-name: prod" would be allocated to the "prod" cluster

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a bug impacting only the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by jessegoodier** [comment]
Looks like a bug to me, thanks for the detail here!
Will get this fixed in our 2.2 or 2.2.1 release.

**Comment by Hronom** [comment]
stops working in 2.2.0

**Comment by Hronom** [comment]
I try to set `appConfigmapName: app-configs` and it not helps. @dgaffuri what else you did to fix this?

**Comment by dgaffuri** [comment]
@Hronom I only notice that defining the value the config map name was passed to deployment as an environment variable, I've not yet checked if the mappings work

**Comment by AjayTripathy** [comment]
@jessegoodier were we able to reproduce this?

**Comment by jessegoodier** [comment]
I was mistaken- label mapping never was intended to change the cloud cost display. 

In Kubecost 1.x, there was a tool called advanced reports. This is where those mappings were used.

In 2.x, `Advanced reports` has been replaced with collections, which has a much simpler interface and the ability to find labels easily with autocomplete.
https://blog.kubecost.com/blog/introducing-kubecost-collections/

Can you take a look at this and let us know if this works?

**Comment by Hronom** [comment]
Seems like it was general issue after upgrade from `2.1.0` to `2.2.0`. I wipe all data and switched to usage of `cloudIntegrationJSON` and everything is ok now

**Comment by jessegoodier** [comment]
> Seems like it was general issue after upgrade from `2.1.0` to `2.2.0`. I wipe all data and switched to usage of `cloudIntegrationJSON` and everything is ok now

Oh, I'm very interested in your findings on that.

It sounds like the helm values in kubecostProductConfigs for cloud integration broke and only started to work when you configured `cloudIntegrationJSON`?
FWIW, I tested that today and both worked, so there is some combination of settings which are conflicting.

Please let me know if you have ideas on that. Can you share your previous settings that didn't work?

**Comment by pandvan** [comment]
We're facing a similar issue: cannot get external labels to work.
Tags has been set on AWS side and exported on the CUR but costs are never associated with the cluster monitored by kubecost. In Cloud Cost pane we see that 100% of k8s utilization is on AWS EKS, even if we tag RDS, EFS, EC2 and other resources. Is there any way to debug such issue? How to understand where/how kubecost try to read this tags and tied them with k8s resources?

**Comment by jessegoodier** [comment]
@pandvan could you share your helm values and what version you are using?

**Comment by pandvan** [comment]
We're using version 2.3.2
Here below Helm chart values
```yaml
cost-analyzer:
  kubecostFrontend:
    image: public.ecr.aws/kubecost/frontend
  kubecostModel:
    image: public.ecr.aws/kubecost/cost-model
  forecasting:
    fullImageName: public.ecr.aws/kubecost/kubecost-modeling:v0.1.12
  networkCosts:
    image:
      repository: public.ecr.aws/kubecost/kubecost-network-costs
  clusterController:
    image:
      repository: public.ecr.aws/kubecost/cluster-controller
  prometheus:
    server:
      image:
        repository: public.ecr.aws/kubecost/prometheus
    configmapReload:
      prometheus:
        image:
          repository: public.ecr.aws/kubecost/prometheus-config-reloader
  reporting:
    productAnalytics: false
  diagnostics:
    enabled: false

  appConfigmapName: app-configs

  kubecostProductConfigs:
    # Cloud integration
    projectID: "<REDACTED>"
    createServiceKeySecret: true
    awsServiceKeyName: <REDACTED>
    awsServiceKeyPassword: <REDACTED>
    # Cost and Usage Reports (now Data Exports)
    athenaProjectID: "<REDACTED>"
    athenaBucketName: s3://<REDACTED>
    athenaRegion: eu-central-1
    athenaDatabase: athenacurcfn_kubecost
    athenaTable: kubecost
    athenaWorkgroup: primary
    # Spot instances feed
    awsSpotDataRegion: eu-central-1
    awsSpotDataBucket: <REDACTED>
    awsSpotDataPrefix: feed
    spotLabel: eks.amazonaws.com/capacityType
    spotLabelValue: SPOT
    # AWS tag - Kubecost asset mapping
    labelMappingConfigs:
      enabled: true
      namespace_external_label: "kubecost/kubernetes_namespace"
      cluster_external_label: "kubecost/kubernetes_cluster"
      controller_external_label: "kubecost/kubernetes_controller"
      product_external_label: "kubecost/kubernetes_label_app"
      service_external_label: "kubecost/kubernetes_service"
      deployment_external_label: "kubecost/kubernetes_deployment"
      team_external_label: "kubecost/kubernetes_label_team"
      environment_external_label: "kubecost/kubernetes_label_env"
      department_external_label: "kubecost/kubernetes_label_department"
      statefulset_external_label: "kubecost/kubernetes_statefulset"
      daemonset_external_label: "kubecost/kubernetes_daemonset"
      pod_external_label: "kubecost/kubernetes_pod"
    cloudAccountMapping:
      "<REDACTED>": kubernetes-prod
```

Then we tag some external AWS resources such as RDS, EC2, Elasticache ecc... with `kubecost/kubernetes_cluster: <our_cluster_name_as_seen_by_kubecost>` but we cannot understand how to see if their costs (they are present on cloud costs) have been associated with the kubernetes cluster (or other components like namespace).
