### ISSUE TITLE
[Bug] - OKTA OIDC Integration - Authorization token is invalid or has expired 

### ISSUE THREAD

**Issue by asdutoit** [kubecost/cost-analyzer-helm-chart#3344]
### Kubecost Helm Chart Version

cost-analyzer-2.2.0

### Kubernetes Version

1.29

### Kubernetes Platform

EKS

### Description

Let me preface this by saying, I am not sure whether it is a bug or just my inability to correctly configure the Helm values.  

OIDC authentication fails:

```yaml
oidc:
  enabled: true
  clientID: "012xxxxxxxxxxxx" # application/client client_id parameter obtained from provider, used to make requests to server
  # clientSecret: "{clientSecret}" # application/client client_secret parameter obtained from provider, used to make requests to server
  # secretName: "kubecost-oidc-secret" # k8s secret where clientsecret will be stored
  # For use to provide a custom OIDC Secret. Overrides the usage of oidc.clientSecret and oidc.secretName.
  # Should contain the field directly.
  # Can be created using raw k8s secrets, external secrets, sealed secrets, or any other method.
  existingCustomSecret:
    enabled: true
    name: kubecost-okta-oidc-secret # name of the secret containing the client secret

  authURL: "https://trial-1234567.okta.com/oauth2/v1/authorize?client_id=012xxxxxxxxxxxx&response_type=code&state=none&scope=openid&redirect_uri=https://kubecost.dev.example.io/model/oidc/authorize" # endpoint for login to auth server
  loginRedirectURL: "https://kubecost.dev.example.io/model/oidc/authorize" # Kubecost url configured in provider for redirect after authentication
  discoveryURL: "https://trial-1234567.okta.com/.well-known/openid-configuration" # url for OIDC endpoint discovery
  skipOnlineTokenValidation: false # if true, will skip accessing OIDC introspection endpoint for online token verification, and instead try to locally validate JWT claims
  # hostedDomain: "example.com" # optional, blocks access to the auth domain specified in the hd claim of the provider ID token
  rbac:
    enabled: false
    ```

### Steps to reproduce

1. Create OIDC App in OKTA Dashboard
2. Save `clientSecret` as k8s secret
3. Update the `oidc` section with **authURL**, **loginRedirectURL** and **discoveryURL**
4. Deploy helm chart and test

### Expected behavior

Successful login

### Impact

Users are unable to log in to Kubecost UI. 

### Screenshots

<img width="1527" alt="Screenshot 2024-04-15 at 16 25 31" src="https://github.com/kubecost/cost-analyzer-helm-chart/assets/20240370/0ac579f4-2ed1-4ae7-b07e-43687c933811">

### Logs

```Shell
2024-04-15T14:00:44.077102156Z INF handling open-id connect...
2024-04-15T14:00:44.077338555Z INF REDIRECT URI: https://kubecost.dev.example.io/model/oidc/authorize
2024-04-15T14:00:44.136750179Z INF Token Response: {"error":"invalid_grant","error_description":"The authorization code is invalid or has expired."}
2024-04-15T14:00:44.13697816Z INF Error in OIDC token request: empty token
10.42.8.171 - - [15/Apr/2024:14:00:44 +0000] "GET /model/oidc/authorize?code=kDF1xxxxxxxxxxxxxxxxx&state=none ... 
```
```


### Slack discussion

https://kubecost.slack.com/archives/CLFV60Y90/p1712923370967759

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a bug impacting only the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.
