### ISSUE TITLE
[Bug] Auth0 oidc with id token causes infinite redirect loop

### ISSUE THREAD

**Issue by Legion2** [kubecost/cost-analyzer-helm-chart#3353]
### Kubecost Helm Chart Version

2.2.2

### Kubernetes Version

1.27

### Kubernetes Platform

EKS

### Description

I have configured oidc with Auth0 provider as follows:
```yaml
oidc:
  enabled: true
  useIDToken: true
  clientID: "***"
  clientSecret: "***"
  secretName: "kubecost-oidc-secret"
  authURL: "https://***/authorize?response_type=code&client_id=***&redirect_uri=http%3A%2F%2Flocalhost%3A9090%2Fmodel%2Foidc%2Fauthorize&scope=openid%20profile%20email"
  loginRedirectURL: "http://localhost:9090/model/oidc/authorize"
  discoveryURL: "https://***/.well-known/openid-configuration"
  skipOnlineTokenValidation: true # validate jwt token offline, because introspection endpoint is not available with Auth0
  rbac:
    enabled: false
```

when I open kubecost in browser it successfully redirects to auth0 and back with auth code, which is successfully exchanged for assess and id token, which I can see in the logs. The access token and id token are set as cookies and on inspection look as expected. However kubecost then again redirects to auth0 and the whole process repeats in a loop.

### Steps to reproduce

see Description

### Expected behavior

After one redirect I'm logged in and can use kubecost.

### Impact

I cannot use kubecost in production, because I can not setup the user authentication.

### Logs

```Shell
Attempting to authenticate oidc...
Validating OIDC token...
Attempting to fetch token from cookie...
Manually validating OIDC token...
Authentication failed, writing 401...
Login called
Validating OIDC token...
Attempting to fetch token from cookie...
Manually validating OIDC token...
Redirecting to 'https://***/authorize?...'
"GET /test HTTP/1.1" 303 234 "-" 
handling open-id connect...
REDIRECT URI: http://localhost:9090/model/oidc/authorize
Token Response: ***
"GET /model/oidc/authorize?code=*** HTTP/1.1" 303 33 "-" 
Login called
Validating OIDC token...
Attempting to fetch token from cookie...
Manually validating OIDC token...
Redirecting to 'https://***/authorize?...'
"GET /login HTTP/1.1" 303 234 "-"
handling open-id connect...
```

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a bug impacting only the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.
