### ISSUE TITLE
Possibility to set Grafana Address in Settings via values.yaml

### ISSUE THREAD

**Issue by Zenmodai** [kubecost/cost-analyzer-helm-chart#347]
**What problem are you trying to solve?**
At the moment after the installation the Grafana Address in the settings (web frontend) is always empty, you have to set it manually. 

**Describe the solution you'd like**
I don't want to set this manually after each installation. When Kubecost is deployed, you should have a variable in the values.yaml, that will automatically set this setting.

**Describe alternatives you've considered**
No alternatives. Either current behavior, which means to set this manually or the described solution to have this done via the values.yaml at the installation.

**How would users interact with this feature?**
Interaction via the values.yaml.

**Comment by dwbrown2** [comment]
Hi, thanks for the detailed request! I just wanted to confirm that you are using a custom Grafana (i.e. not our bundled Grafana), because setting this should not be required otherwise. 

Also, we have an existing option to deploy at install time with the Grafana sidecar:
https://github.com/kubecost/docs/blob/master/custom-prom.md#custom-grafana

Does that option help you? If not, let me know and we can explore different options!

**Comment by Zenmodai** [comment]
No, I am using currently the bundled Grafana, not a custom one. But the address is not set in the web frontend after the installation.

**Comment by dwbrown2** [comment]
You should not need to update this value when using our bundled Grafana. We will update language here to make it more clear that this is optional. 

Is there another reason why you would need to update this value?

**Comment by Zenmodai** [comment]
Sorry, I think I wasn't clear enough. The problem is that after the installation the 'Grafana Address' field under General Settings in the web frontend is empty. That's why the redirects from the links under the metrics to the Grafana dashboard do not work immediately. Only when I set this empty field manually will the links work.

![Screenshot from 2020-03-23 07-44-25](https://user-images.githubusercontent.com/47887818/77289638-a1b6bf00-6cda-11ea-856f-f7a263d4cb5b.png)

**Comment by dwbrown2** [comment]
This field should be empty in our default install. That's because our pod handles routing to bundled Grafana. 

Can you share more about why the links to Grafana dashboards were not working for you? What address were they routing to and what address did you expect them to route to?

**Comment by Zenmodai** [comment]
I am using an ingress for both Kubecost and the bundled Grafana. Both can be accessed after the installation and work.

The problem is that when I click in the 'Overview' page under 'Monthly cluster costs' on the 'CLUSTER METRICS' button the redirection to Grafana doesn't work.

The request URL: https://kubecost.testurl123.io/model/getApiConfig?req=129012
And this is the response:
`{"grafanaURL":"","disableFE":"","owner_label":"Company","team_label":"IT","department_label":"DevOPs","product_label":"app","environment_label":"Dev"}`

The URL I am redirected to is the Kubecost Ingress URL + '/login', which of course doesn't exist.
So I am guessing because the grafanaURL is empty in the response, it will just redirect to the Kubecost URL back with the login suffix, which is intended for Grafana. 
Only when I manually set the Grafana URL in the settings page (screenshot from before), then the redirection works.

**Comment by dwbrown2** [comment]
Can you share your ingress definition? Here's a working [example](https://github.com/kubecost/docs/blob/master/getting-started.md#basic-auth). 

Here's the way this should work... let's say Kubecost is exposed at  http://kubecost.testurl.io. Requests are handled by our nginx server exposed at this endpoint. 

All requests to http://kubecost.testurl.io/model ==> nginx routes to our cost-model container
All requests to http://kubecost.testurl.io/grafana ==> nginx routes to our bundled Grafana

It sounds like this routing is not working correctly.

**Comment by Zenmodai** [comment]
I am using 2 ingress. One for Kubecost and another one for Grafana. I am specifying the Grafana ingress with the values.yaml grafana/ingress section. 

```
ingress:
    enabled: true
    path: /
    annotations:
      kubernetes.io/ingress.class: nginx-external
    hosts:
      - kubecost-grafana.dev.testurl123.io
    tls: 
      - hosts:
        - kubecost-grafana.dev.testurl123.io
```

The kubecost ingress is as follows:

```
ingress:
  enabled: true
  paths: ["/"] 
  annotations:
    kubernetes.io/ingress.class: nginx-external
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
  hosts:
    - kubecost.dev.testurl123.io
  tls: 
    - hosts:
      - kubecost.dev.testurl123.io
```

**Comment by dwbrown2** [comment]
Thanks, this is helpful. You do not actually need to create a separate ingress for Grafana when using the bundled deployment.

**Comment by dwbrown2** [comment]
@Zenmodai all good here, or still need assistance?

**Comment by Zenmodai** [comment]
@dwbrown2 Well, I think the basic issue could still be worth it. 
I tried the kubecost installation with a separate prometheus/grafana environment as a comparison and with this you also have to manually add the url of the grafana via the dashboard settings page. Since you cannot set this url otherwise. I know this only matters, if you use separate ingress settings with the bundled version, but with the separate prometheus/grafana environment, this would always be helpful.
So it would be great to be able to set the Grafana address (Custom location of Grafana dashboard home) via the actual helm deployment, no matter if you use the bundled or an external prometheus/grafana.
Currently there is no option to set the external Grafana address in the values.yaml file, e.g. a Grafana is used, that is deployed on another cluster.

**Comment by jseiser** [comment]
We need a way to set the grafana URL.  We use our own prom/grafana setup, and the dashboards work.  if we enter the URL into the UI, the dashboards work as well.

**Comment by dwbrown2** [comment]
@jseiser, meaning you want to set at install-time? If so, that makes total sense to me. This can already be supported with option 2 here: https://github.com/kubecost/docs/blob/master/custom-prom.md#custom-grafana

But it sounds like it would also be useful to expose this grafana url under our productConfigs block in [values.yaml](https://github.com/kubecost/cost-analyzer-helm-chart/blob/master/cost-analyzer/values.yaml#L290). Would that be useful for you?

**Comment by jseiser** [comment]
@dwbrown2 

We are running our own grafana deployment, and we do not use the sidecar.  We add dashboards, using the 

dashboards.default configuration.  so the kubecost dashboards get loaded like so.

```
    dashboards:
      default:
        node-utilization:
          url: "https://raw.githubusercontent.com/kubecost/cost-analyzer-helm-chart/master/cost-analyzer/node-utilization.json"
        pod-utilization:
          url: "https://raw.githubusercontent.com/kubecost/cost-analyzer-helm-chart/master/cost-analyzer/pod-utilization.json"
        cluster-metrics:
          url: "https://raw.githubusercontent.com/kubecost/cost-analyzer-helm-chart/master/cost-analyzer/cluster-metrics.json"
```

then in the kubecost values.yml we define

```
      grafana:
        enabled: false
        domainName: https://grafana.domain.com/
        scheme: "http"
        proxy: true
```


But, none of the dashboard links work, until we actually enter this in the UI

```
Grafana Address
Custom location of Grafana dashboard home. Not required.
```
