### ISSUE TITLE
sigv4proxy NoCredentialProviders

### ISSUE THREAD

**Issue by eahangari-8x8** [kubecost/cost-analyzer-helm-chart#3520]
Hello everyone I have installed the kubecost using helm chart and argocd but I get the following error in the sigv4proxy container. 
here is the log: 

```
 time="2024-06-27T20:31:22Z" level=error msg="unable to proxy request" error="NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"
```

here is my values.yaml 

```
global:
  grafana:
    enabled: false
    proxy: false

  prometheus:
    enabled: true

  amp:
    enabled: true
    prometheusServerEndpoint: http://localhost:8005/workspaces/<redacted>
    remoteWriteService: https://aps-workspaces.us-east-1.amazonaws.com/workspaces/<redacted>/api/v1/remote_write
    sigv4:
      region: us-east-1

  platforms:
    cicd:
      enabled: true
      skipSanityChecks: true

sigV4Proxy:
  region: us-east-1
  host: aps-workspaces.us-east-1.amazonaws.com

```

I really appreciate it if you can give me any help or advice on how to resolve it.
Thanks
