### ISSUE TITLE
[Bug] `Department` not filling up correctly

### ISSUE THREAD

**Issue by KulykDmytro** [kubecost/cost-analyzer-helm-chart#3577]
### Kubecost Helm Chart Version

2.3.4

### Kubernetes Version

1.30

### Kubernetes Platform

EKS

### Description

Have `kubecostProductConfigs.labelMappingConfigs` set
```yaml
      labelMappingConfigs:
        enabled: true
        owner_label: owner
        team_label: team
        department_label: stream
        product_label: product
        environment_label: env
```
As result have `Deparment` not split at all in `Allocations`

### Expected behavior

costs need to honor label config and be split by Department

### Screenshots

![image](https://github.com/user-attachments/assets/3a2591b5-401a-4a2b-bb2f-fd9a6c304ede)
![image](https://github.com/user-attachments/assets/d392fe20-6abf-4ff1-8211-c0589abaf18a)

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a bug impacting only the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.
