### ISSUE TITLE
[Bug] `Product` filled with weird values

### ISSUE THREAD

**Issue by KulykDmytro** [kubecost/cost-analyzer-helm-chart#3578]
### Kubecost Helm Chart Version

2.3.4

### Kubernetes Version

1.30

### Kubernetes Platform

EKS

### Description

Have `kubecostProductConfigs.labelMappingConfigs` set
```yaml
      labelMappingConfigs:
        enabled: true
        owner_label: owner
        team_label: team
        department_label: stream
        product_label: product
        environment_label: env
```
As result have `Product` in `Allocations` split by weird values (presumably with `controller`)

### Steps to reproduce

1. 

### Expected behavior

costs need to honor label config and be split by Product correctly

### Screenshots

![image](https://github.com/user-attachments/assets/98b7ee71-635c-4a3d-9956-ab0acc2a3d38)
![image](https://github.com/user-attachments/assets/1c99817d-1ebc-4be4-95f0-c91e56d1c984)

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a bug impacting only the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by AjayTripathy** [comment]
@LastJedionEarth @jessegoodier do we have a test that can repro this? If not can we get one set up?

**Comment by jessegoodier** [comment]
@KulykDmytro 
I was not able to reproduce this issue. All of our results match exactly. Can you confirm your yaml is formatted like this?
If you look at the bug report, you will see:

```yaml
kubecostProductConfigs:
      labelMappingConfigs:
        enabled: true
        owner_label: owner
        team_label: team
        department_label: stream
        product_label: product
        environment_label: env
```
you can verify the setting is picked up in helmValues:
/model/helmValues
```json
   "kubecostProductConfigs": {
        "carbonEstimates": true,
        "cloudIntegrationSecret": "cloud-integration",
        "clusterName": "kubecost-xxx",
        "labelMappingConfigs": {
            "department_external_label": "cost_info_business_category",
            "department_label": "cost_info_business_category",
            "enabled": true,
            "environment_label": "env",
            "owner_external_label": "cost_info_owner",
            "owner_label": "cost_info_owner",
            "product_external_label": "cost_info_product",
            "product_label": "cost_ask_info_product",
            "team_external_label": "cost_info_department",
            "team_label": "cost_info_department"
        },
...
```
