### ISSUE TITLE
[Bug] Argo CD ComparisonError (SSO with RBAC is enabled)

### ISSUE THREAD

**Issue by aashishshrestha09** [kubecost/cost-analyzer-helm-chart#3624]
### Kubecost Helm Chart Version

v2.3.4

### Kubernetes Version

1.26

### Kubernetes Platform

OpenShift

### Description

I'm encountering a ComparisonError when trying to enable RBAC in Kubecost 2.3.4. The error message is:

`Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = `helm template . --name-template kubecost --namespace kubecost --kube-version 1.28 --values <path to cached source>/infrastructure/lk3-poc-use1-a/kubecost/cost-analyzer/values.yaml <api versions removed> --include-crds` failed exit status 1: Error: execution error at (cost-analyzer/templates/NOTES.txt:2:4): SSO with RBAC is enabled. Note that Kubecost 2.x has significant architectural changes that may impact RBAC. This should be tested before giving end-users access to the UI. Kubecost has tested various configurations and believe that 2.x will be 100% compatible with existing configurations. Refer to the following documentation for more information: https://docs.kubecost.com/install-and-configure/install/kubecostv2 When ready to upgrade, add `--set upgrade.toV2=true`. Use --debug flag to render out invalid YAML
`

**Note:** I have enabled [these values](https://github.com/kubecost/cost-analyzer-helm-chart/blob/v2.3/cost-analyzer/values.yaml#L249-L252) in the chart.

![image](https://github.com/user-attachments/assets/c769f83e-ca53-4bfb-b2d7-beafeafbeac4)

### Steps to reproduce

1. Enable RBAC in the Kubecost values.yaml file with the following configuration:

```
oidc:
  enabled: true
  # THIS IS REQUIRED FOR AZURE. Azure communicates roles via the id_token instead of the access_token.
  useIDToken: true
  rbac:
    enabled: true
    groups:
      - name: admin
        # If admin is disabled, all authenticated users will be able to make configuration changes to the kubecost frontend
        enabled: true
        # SET THIS EXACT VALUE FOR ENTRA ID. This is the string Entra ID uses in its OIDC tokens.
        claimName: "roles"
        # These strings need to exactly match with the app roles created in Entra ID
        claimValues:
          - "admins"
          - "superusers"
      - name: readonly
        # If readonly is disabled, all authenticated users will default to readonly
        enabled: true
        claimName: "roles"
        claimValues:
          - "readonly"
```

### Expected behavior

RBAC should be enabled without causing an error.

### Impact

This issue prevents us from properly enabling RBAC in Kubecost, which is critical for managing user access and roles. Without RBAC, all authenticated users might have unintended access levels, impacting security and compliance. This prevents us from leveraging Kubecost's full capabilities in a secure and controlled manner.

### Screenshots

![image](https://github.com/user-attachments/assets/7224af47-8c29-4f20-b256-45d274a5ed22)

### Logs

```Shell
Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = `helm template . --name-template kubecost --namespace kubecost --kube-version 1.28 --values <path to cached source>/infrastructure/lk3-poc-use1-a/kubecost/cost-analyzer/values.yaml <api versions removed> --include-crds` failed exit status 1: Error: execution error at (cost-analyzer/templates/NOTES.txt:2:4): SSO with RBAC is enabled. Note that Kubecost 2.x has significant architectural changes that may impact RBAC. This should be tested before giving end-users access to the UI. Kubecost has tested various configurations and believe that 2.x will be 100% compatible with existing configurations. Refer to the following documentation for more information: https://docs.kubecost.com/install-and-configure/install/kubecostv2 When ready to upgrade, add `--set upgrade.toV2=true`. Use --debug flag to render out invalid YAML
```

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a bug impacting only the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.
