### ISSUE TITLE
Values from kubecostProductConfigs are not matching those in Settings => Pricing?

### ISSUE THREAD

**Issue by kastl-ars** [kubecost/cost-analyzer-helm-chart#3695]
Hi all,

not sure if this is related to the chart or to kubecost itself (but I found no other repository that seems fitting, maybe this needs to go to OpenCost?).

I am starting with a simple cost model, so I set the `kubecostProductConfigs` in my `values.yaml`:

```
kubecostProductConfigs:
  customPricesEnabled: true
  defaultModelPricing:
    enabled: true
    CPU: "100"
    spotCPU: "0"
    RAM: "0"
    spotRAM: "0"
    GPU: "0"
    spotGPU: "0"
    storage: "0"
    zoneNetworkEgress: "0"
    regionNetworkEgress: "0"
    internetNetworkEgress: "0"
```

The resulting configmap `pricing-configs` contains the same values:

```
apiVersion: v1
data:
  CPU: "100"
  GPU: "0"
  RAM: "0"
  customPricesEnabled: "true"
  internetNetworkEgress: "0"
  regionNetworkEgress: "0"
  spotCPU: "0"
  spotGPU: "0"
  spotRAM: "0"
  storage: "0"
  zoneNetworkEgress: "0"
kind: ConfigMap
```

For some reason, the CPU cost is shown as `100.01073888`.

I noticed the same odd numbers in the [documentation](https://docs.kubecost.com/architecture/pricing-sources-matrix#custom-pricing) so I guess this is normal. But I would like to understand why?

Kind Regards,
Johannes
