### ISSUE TITLE
[Bug] Cross AZ traffic not being marked automatically

### ISSUE THREAD

**Issue by angelbarrera92** [kubecost/cost-analyzer-helm-chart#3819]
### Kubecost Helm Chart Version

v2.5.3

### Kubernetes Version

v1.25

### Kubernetes Platform

Other (specify in description)

### Description

- kubeadm setup on top of AWS EC2 + cilium

I'm running a Kubernetes cluster across three different availability zones (AZs). I'd like to collect metrics exposed by this exporter.

After researching, it appears that I might be experiencing the same issue as [#820](https://github.com/kubecost/cost-analyzer-helm-chart/issues/820) in the Kubecost Cost Analyzer Helm chart. The symptoms suggest that having a client pod (debug-connectivity) in one AZ connecting directly to a pod in another AZ, no cross-AZ traffic is reflected in the exporter metrics."

 ```bash
$ kubectl get pods -o wide -n kubecost
NAME                           READY   STATUS    RESTARTS   AGE     IP              NODE                                          NOMINATED NODE   READINESS GATES
debug-connectivity             1/1     Running   0          3m33s   100.94.3.107    ip-10-150-52-194.eu-west-1.compute.internal   <none>           <none>
kubecost-network-costs-4hhx4   1/1     Running   0          4m16s   10.150.61.60    ip-10-150-61-60.eu-west-1.compute.internal    <none>           <none>
kubecost-network-costs-8l2lt   1/1     Running   0          4m16s   10.150.49.118   ip-10-150-49-118.eu-west-1.compute.internal   <none>           <none>
kubecost-network-costs-fsh9r   1/1     Running   0          4m16s   10.150.52.194   ip-10-150-52-194.eu-west-1.compute.internal   <none>           <none>
prometheus-kubecost-0          2/2     Running   0          4m21s   100.94.2.165    ip-10-150-49-118.eu-west-1.compute.internal   <none>           <none>
$ kubectl get node -o jsonpath='{range .items[*]}{.metadata.name}{"\t"}{.metadata.labels.failure-domain\.beta\.kubernetes\.io/zone}{"\n"}{end}'
ip-10-150-49-118.eu-west-1.compute.internal     eu-west-1a
ip-10-150-52-194.eu-west-1.compute.internal     eu-west-1b
ip-10-150-61-60.eu-west-1.compute.internal      eu-west-1c
```

executing:
```bash
$ kubectl exec -it -n kubecost debug-connectivity -- bash
s# while true; do curl 10.150.49.118:3001/metrics; sleep 1; done
```

This is traffic that flows from eu-west-1b (debug-connectivity pod at ip-10-150-52-194.eu-west-1.compute.internal) to eu-west-1a (kubecost-network-costs-8l2lt pod at ip-10-150-49-118.eu-west-1.compute.internal).

Metrics:

```
kubecost_pod_network_egress_bytes_total{container="kubecost-network-costs", endpoint="metrics", instance="10.150.52.194:3001", internet="false", job="kubecost-network-costs", namespace="kubecost", pod="kubecost-network-costs-fsh9r", pod_name="debug-connectivity", same_region="true", same_zone="true"}	35844
kubecost_pod_network_egress_bytes_total{container="kubecost-network-costs", endpoint="metrics", instance="10.150.52.194:3001", internet="true", job="kubecost-network-costs", namespace="kubecost", pod="kubecost-network-costs-fsh9r", pod_name="debug-connectivity", same_region="false", same_zone="false"}	394
kubecost_pod_network_egress_bytes_total{container="kubecost-network-costs", endpoint="metrics", instance="10.150.49.118:3001", internet="false", job="kubecost-network-costs", namespace="kubecost", pod="kubecost-network-costs-8l2lt", pod_name="kubecost-network-costs-8l2lt", same_region="true", same_zone="true"}	5674715
kubecost_pod_network_egress_bytes_total{container="kubecost-network-costs", endpoint="metrics", instance="10.150.49.118:3001", internet="true", job="kubecost-network-costs", namespace="kubecost", pod="kubecost-network-costs-8l2lt", pod_name="kubecost-network-costs-8l2lt", same_region="false", same_zone="false"}	92858
kubecost_pod_network_ingress_bytes_total{container="kubecost-network-costs", endpoint="metrics", instance="10.150.49.118:3001", internet="false", job="kubecost-network-costs", namespace="kubecost", pod="kubecost-network-costs-8l2lt", pod_name="kubecost-network-costs-8l2lt", same_region="true", same_zone="true"}	54948135
kubecost_pod_network_ingress_bytes_total{container="kubecost-network-costs", endpoint="metrics", instance="10.150.49.118:3001", internet="true", job="kubecost-network-costs", namespace="kubecost", pod="kubecost-network-costs-8l2lt", pod_name="kubecost-network-costs-8l2lt", same_region="false", same_zone="false"}	2571210
kubecost_pod_network_ingress_bytes_total{container="kubecost-network-costs", endpoint="metrics", instance="10.150.49.118:3001", internet="true", job="kubecost-network-costs", namespace="kubecost", pod="kubecost-network-costs-8l2lt", pod_name="kubecost-network-costs-8l2lt", same_region="false", same_zone="false", service="aws-ec2"}	124041
```

None of them match:
    - internet: false
    - same_region: true
    - same_zone: false

(This is incorrect.)

I've also tested requesting the Prometheus metrics endpoint from the debug container, but got the same result.

Here's my setup configuration file.

```yaml
    destinations:
      cross-region: []
      direct-classification: []
      in-region: []
      in-zone:
      - 127.0.0.1/32
      internet: []
    services:
      amazon-web-services: true
      azure-cloud-services: true
      google-cloud-services: true
```

Moving to:
```yaml
    destinations:
      cross-region: []
      direct-classification: []
      in-region:
        - 10.150.49.0/25
        - 10.150.60.32/27
        - 10.150.60.0/27
        - 10.150.52.128/25
        - 10.150.60.96/27
        - 10.150.60.64/27
        - 10.150.61.0/25
        - 10.150.60.160/27
        - 10.150.60.128/27

      in-zone:
        - 127.0.0.1/32
      internet: []
    services:
      amazon-web-services: true
      azure-cloud-services: true
      google-cloud-services: true
```

the exporter correctly detects traffic crossing AZ boundaries.

```
kubecost_pod_network_egress_bytes_total{container="kubecost-network-costs", endpoint="metrics", instance="10.150.52.194:3001", internet="false", job="kubecost-network-costs", namespace="kubecost", pod="kubecost-network-costs-snvrd", pod_name="debug-connectivity", same_region="true", same_zone="false"}	39905
kubecost_pod_network_egress_bytes_total{container="kubecost-network-costs", endpoint="metrics", instance="10.150.61.60:3001", internet="false", job="kubecost-network-costs", namespace="kubecost", pod="kubecost-network-costs-nvq97", pod_name="kubecost-network-costs-nvq97", same_region="true", same_zone="false"}	11107470
kubecost_pod_network_ingress_bytes_total{container="kubecost-network-costs", endpoint="metrics", instance="10.150.61.60:3001", internet="false", job="kubecost-network-costs", namespace="kubecost", pod="kubecost-network-costs-nvq97", pod_name="kubecost-network-costs-nvq97", same_region="true", same_zone="false"}	48769529
```

Based on my understanding (AFAIK), I would expect this detection to occur automatically.

### Steps to reproduce

1. **Prerequisites:** A Kubernetes cluster running across multiple availability zones (AZs) with Cilium and Prometheus Operator installed.
2. Extract the provided tar.gz archive.

[network-cost.tar.gz](https://github.com/user-attachments/files/18520444/network-cost.tar.gz)

Then, follow these steps:
- Apply the `network-cost-requirements.yml` manifests to create the namespace and Prometheus instance.
- Deploy the network exporter by applying the `network-cost.yml` manifest.

This manifest was generated using the values from `values.yaml`:
```yaml
networkCosts:
  enabled: true
  logLevel: debug
  config:
    destinations:
      in-zone:
        - 127.0.0.1/32
serviceMonitor:  # the kubecost included prometheus uses scrapeConfigs and does not support service monitors. The following options assume an existing prometheus that supports serviceMonitors.
  enabled: true
  networkCosts:
    enabled: true
    additionalLabels:
      prometheus: kubecost    
prometheusRule:
  enabled: true
```

Next, simply apply the network-cost-specific manifest from `network-cost.yml`, without deploying the full Kubecost setup.

### Expected behavior

The detection of cross-availability zone traffic should occur automatically, without requiring manual configuration to specify subnets for each availability zone in `config.yml`.

### Impact

Not having this feature makes the tool unusable, as it fails to report relevant metrics on one of the most expensive items in the AWS bill.

### Logs

```Shell

```

### Troubleshooting

- [x] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a bug impacting only the Helm chart.
- [x] I have searched other issues in this repository and mine is not recorded.
