### ISSUE TITLE
after upgrading to 2.7.0 cost-analyzer-frontend container crashing with readiness failure

### ISSUE THREAD

**Issue by Viswajith96** [kubecost/cost-analyzer-helm-chart#3996]
After upgrading helm chart from 2.6.2 to 2.7.0, cost-analyzer-frontend container in kubecost-cost-analyzer deployment, after 6-7 mins its coming back to normal and starts running.

![Image](https://github.com/user-attachments/assets/bc07a181-bcb0-4fc5-b109-e912ceacfe43)

values.yaml
```
kubecostFrontend:
        enabled: true
        deployMethod: singlepod
        readinessProbe:
          enabled: true
          initialDelaySeconds: 30
          periodSeconds: 15
          failureThreshold: 6
          timeoutSeconds: 5
        livenessProbe:
          enabled: true
          initialDelaySeconds: 30
          periodSeconds: 15
          failureThreshold: 6
          timeoutSeconds: 5
        resources:
          requests:
            cpu: "10m"
            memory: "55Mi"
        ipv6:
          enabled: true
```
