### ISSUE TITLE
[prometheus] Create ServiceMonitor and PrometheusRule resources

### ISSUE THREAD

**Issue by Nuru** [kubecost/cost-analyzer-helm-chart#48]
Because multiple applications installed in a single cluster all want to have visibility via Prometheus, Grafana, and Alertmanager, CoreOS has developed the [Prometheus-Operator chart](https://github.com/helm/charts/tree/master/stable/prometheus-operator) which installs a single instance of these tools that can be shared by all the applications in the cluster. Following the principle of Kubernetes that each application should specify its own resource needs, Prometheus Operator includes [new Custom Resources](https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md) that allow applications to add configuration items to Prometheus, Grafana, and Alertmanager. 

I am grateful that [you did this work](https://github.com/kubecost/cost-analyzer-helm-chart/pull/32) for the Grafana dashboards and ask that you now do it for [ServiceMonitors]() (which replace [`scrape_configs`](https://github.com/kubecost/cost-analyzer-helm-chart/blob/6ea6d201da050627249af23999501209f2df8430/cost-analyzer/charts/prometheus/values.yaml#L1107-L1118)) and [PrometheusRules](https://github.com/kubecost/cost-analyzer-helm-chart/blob/6ea6d201da050627249af23999501209f2df8430/cost-analyzer/charts/prometheus/values.yaml#L838-L845).

One tricky thing is that `ServiceMonoitors` are meant to monitor `Services`, although technically they monitor `Endpoints` that are typically automatically created by Kubernenets for `Services`. The important point is that `ServiceMonitors` target endpoints to scrape via [`LabelSelectors`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#labelselector-v1-meta), which means your `Services` need to have stable and unique labels. Currently, your `kubecost-cost-analyzer` `Service`, which is what you target with your custom `scrape_config` and I now want you to target with a `ServiceMonitor`, only has 1 label: `chart: cost-analyzer-1.26.0`. This is not robust enough for this purpose. I suggest you add the `app: cost-analyzer` label to it as well. With that, the following `ServiceMonitor` should work:
```
kind: ServiceMonitor
metadata:
  labels:
    app: prometheus-operator
    release: prometheus-operator
  name: cost-analyzer-model
spec:
  endpoints:
  - honorLabels: true
    interval: 1m
    metrics_path: /metrics
    port: cost-analyzer-model
    scheme: http
    scrapeTimeout: 10s
  selector:
    matchLabels:
      app: cost-analyzer
```

I don't know if you have `PrometheusRules` meant for publishing. If the ones you have are just examples so your Prometheus installation is not empty, then they do not need to be converted to `PrometheusRule` resources. However, if you have some you want everyone to use, then please install them as `PrometheusRule` resources rather than as configuration files.
