### ISSUE TITLE
Add recommended labels

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/cost-analyzer-helm-chart#5]
https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/

**Comment by dwbrown2** [comment]
@luisdavim I have #24 right now. Anything else you would want to see there?

**Comment by sebastien-prudhomme** [comment]
@dwbrown2 the recommended labels fro Helm charts are there: https://helm.sh/docs/chart_best_practices/#labels-and-annotations

In practice for an application with only one component (without taken into account subcharts)
```
  labels:
    app.kubernetes.io/name: {{ include "cost-analyzer.name" . }}
    helm.sh/chart: {{ include "cost-analyzer.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }
```

This must be added in every resource managed by the chart (cronjob, service, service account, ...)

The easiest way to do that is to add a ```define``` in the helper YAML file with all this labels and use that ```define``` in every resource
