### ISSUE TITLE
Support for ARM64

### ISSUE THREAD

**Issue by airmonitor** [kubecost/cost-analyzer-helm-chart#652]
Hello.

As the ARM CPU architecture is getting more traction, for example AWS EKS based on ARM CPU was released can you please provide helm chart with updated container images which were compiled for various cpu architectures, arm64, x86_64?

Here is an example code how to build for multiple architectures in gitlab.

https://stackoverflow.com/questions/61430005/gitlab-ci-cd-building-multiarch-docker-images

**Comment by dwbrown2** [comment]
Hi Tomasz! Thanks for the request. Have you seen any helm chart examples that you feel have done this well? If so, we'll investigate and follow up.

**Comment by airmonitor** [comment]
Hello.

Sure :)

For example, influxdata/influxdb works out of the box.


```
helm show chart influxdata/influxdb                                                                                   
apiVersion: v1
appVersion: 1.8.0
description: Scalable datastore for metrics, events, and real-time analytics.
home: https://www.influxdata.com/time-series-platform/influxdb/
keywords:
- influxdb
- database
- timeseries
- influxdata
maintainers:
- email: rawkode@influxdata.com
  name: rawkode
- email: giacomo@influxdata.com
  name: gitirabassi
- email: urakiny@gmail.com
  name: aisuko
- email: naseem@transit.app
  name: naseemkullah
name: influxdb
sources:
- https://github.com/influxdata/influxdb
version: 4.8.9


```
