### ISSUE TITLE
Network policy chart value has an unexpected behaviour

### ISSUE THREAD

**Issue by pierluigilenoci** [kubecost/cost-analyzer-helm-chart#743]
**Describe the bug**
Enabling the option in the chart creates a deny-egress policy that effectively blocks outgoing traffic from the pods. 

Ref: 
* https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/values.yaml#L235-L236
* https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/templates/cost-analyzer-network-policy.yaml

**To Reproduce**
Deploy the package with NP enabled

**Expected behavior**
By enabling the network policy option, I expect all the policies necessary to run the software in a cluster with the policies enabled are created. As does, for example, the Prometheus chart:

https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/templates/server/netpol.yaml

**Comment by pierluigilenoci** [comment]
Allow me to suggest a policy that works and is necessary in the case of "closed traffic" inside the namespace where Kubecost is installed.

```
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: policynameofyourtaste
  namespace: namespaceyoulike
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: cost-analyzer
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: cost-analyzer
        - namespaceSelector:
            matchLabels:
              name: k8s-kubecost
  policyTypes:
    - Ingress
```

and this in case Prometheus and Kubecost run in the same namespace:


```
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: anotherpolicyname
  namespace: namespacewhereprometheusisrunningwithkubecost
spec:
  podSelector:
    matchLabels:
      app: prometheus
      component: server
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: cost-analyzer
        - namespaceSelector:
            matchLabels:
              name: k8s-kubecost
  policyTypes:
    - Ingress
```

**Comment by AjayTripathy** [comment]
I think this makes sense, we'll just want to migrate the policy that does deny-egress to a different flag.

**Comment by pierluigilenoci** [comment]
@AjayTripathy any update?

**Comment by dwbrown2** [comment]
@pierluigilenoci any feedback on https://github.com/kubecost/cost-analyzer-helm-chart/pull/797?

**Comment by pierluigilenoci** [comment]
This is fixed with v1.76.0 👍🏻

**Comment by pierluigilenoci** [comment]
@dwbrown2 the instructions on how to configure this thing are missing in the chart readme.

However, it is an alternative approach to the normal way of managing network policies through Helm Charts.

**Comment by dwbrown2** [comment]
@pierluigilenoci I do not follow your last point. Can you please explain.

**Comment by pierluigilenoci** [comment]
@dwbrown2 Helm charts usually have a unique and simple way to deploy network policies. 
```
networkPolicy:
  enabled: true
```
That's all, no other options.

4 options must be defined with your chart. 
```
networkPolicy:
  enabled: true
  denyEgress: false # Really uncommon network policy, default true?
  sameNamespace: false # I think a multi-namespaced setup is more common than single-namespaced one 
  namespace: <prometheus-namespace>
```
