### ISSUE TITLE
Missing labels on kubecostChecks

### ISSUE THREAD

**Issue by pierluigilenoci** [kubecost/cost-analyzer-helm-chart#761]
**Describe the bug**
The pods of the kubecostCheck cronjob don't have unique labels that allow them to be identified.
It is therefore difficult to create NetworkPolicy with the pods. 

Ref: https://github.com/kubecost/cost-analyzer-helm-chart/issues/743

**To Reproduce**
Deploy the package with NP enabled with a policy like this:
```
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: deny-all-ingress-traffic
  namespace: <yournamespace>
spec:
  podSelector: {}
  policyTypes:
    - Ingress
```
Try to create a Network Policy to allow kubecostCheck to reach other Kubecost pods.

Example:
```
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-kubecostcheck-to-cost-analyzer
  namespace: <yournamespace>
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: cost-analyzer
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: kubecostcheck # or any other label you like more
        - namespaceSelector:
            matchLabels:
              name: <yournamespace>
  policyTypes:
    - Ingress
```

**Expected behavior**
The pod is launched with proper labels.

Example:
```
  labels:
    app: cost-analyzer
    app.kubernetes.io/instance: cost-analyzer
    app.kubernetes.io/name: kubecostcheck # or any other label you like more
```
