### ISSUE TITLE
kind in cost-analyzer-ingress-template is deprecated

### ISSUE THREAD

**Issue by dschunack** [kubecost/cost-analyzer-helm-chart#836]
**Describe the bug**
Hi,

the Kind "extensions/v1beta1" for Ingress API is deprecated and will be removed in the next k8s releases.
The terraform helm provider doesn't support deprecated APIs/kind.
Please, use the new Kind "networking.k8s.io/v1beta1" instead of "extensions/v1beta1" or add a possibility to overwrite the kind in the template.
We use EKS with Kubernetes 1.19 and with the normal nginx Ingress and also the AWS Load Balancer Controller to use ALBs.

```
Error: malformed chart or values: 
	templates/cost-analyzer-ingress-template.yaml: the kind "extensions/v1beta1 Ingress" is deprecated in favor of "networking.k8s.io/v1beta1 Ingress"
```

**To Reproduce**
Use terraform and helm provider to rollout the chart

```yaml
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - "kubecost.domain.com"
  tls: []
```

```hcl
resource "helm_release" "kubecost" {
  name                        = "kubecost"
  namespace                   = "kubecost"
  lint                        = true
  chart                       = "cost-analyzer"
  version                     = "1.76.0"
  repository                  = "https://kubecost.github.io/cost-analyzer/"
  values = [
    "${file("values.yaml")}"
  ]
}
```

**Expected behavior**
Creation of a Ingress object in the namespace to Access the WebUI.

**Screenshots**
```
Error: malformed chart or values: 
	templates/cost-analyzer-ingress-template.yaml: the kind "extensions/v1beta1 Ingress" is deprecated in favor of "networking.k8s.io/v1beta1 Ingress"
```

**Collect logs (please complete the following information):**
No logs, rollout not possible due to this issue
