### ISSUE TITLE
Cost-analyzer deployment env variable CLUSTER_ID is not properly "filled"

### ISSUE THREAD

**Issue by pierluigilenoci** [kubecost/cost-analyzer-helm-chart#869]
**Describe the bug**
Inside the chart you have:

```yaml
            {{- if and (.Values.prometheus.server.global.external_labels.cluster_id) (not .Values.prometheus.server.clusterIDConfigmap) }}
            - name: CLUSTER_ID
              value: {{ .Values.prometheus.server.global.external_labels.cluster_id }}
            {{- end }}
            {{- if .Values.prometheus.server.clusterIDConfigmap }}
            - name: CLUSTER_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.prometheus.server.clusterIDConfigmap }}
                  key: CLUSTER_ID
            {{- end }}
```

Ref: https://github.com/kubecost/cost-analyzer-helm-chart/blob/master/cost-analyzer/templates/cost-analyzer-deployment-template.yaml#L531-L541

In this way, the CLUSTER_ID value is set correctly only if you install Prometheus with your chart.
For those with a separate installation, it doesn't work.

This bug causes this: https://github.com/kubecost/cost-model/issues/764

**To Reproduce**

1. Install the chart without Prometheus

**Expected behavior**

I expect this value to be set correctly, for example by taking the value from `kubecostProductConfigs.cluster_name` or even better with the value from `kubecostProductConfigs.labelMappingConfigs.cluster_external_label`. 

**Screenshots**
Not relevant

**Collect logs (please complete the following information):**
Not relevant

**Comment by mhulscher** [comment]
As a user, this is not my experience. We install kubecost with our own prometheus and configure kubecost's values.yaml like so (partially):

```yaml
    global:
      prometheus:
        enabled: false
        fqdn: http://prometheus.somewhere:9090

    prometheus:
      server:
        global:
          external_labels:
            cluster_id: $cluster_name
```

Of course, we have to configure our own prometheus to add externalLabels to each timeseries. We use the kube-prometheus-stack: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L1918. 

This seems to work for us.

**Comment by pierluigilenoci** [comment]
@mhulscher these parameters are part of the Prometheus sub chart.
They should not be used by CostAnalyzer as well. 

```yaml
    prometheus:
      server:
        global:
          external_labels:
            cluster_id: $cluster_name
```
