### ISSUE TITLE
Create a static sort order in UI for multiple clusters

### ISSUE THREAD

**Issue by ammills01** [kubecost/cost-analyzer-helm-chart#916]
Under _Available Clusters_ and _Select a cluster_ the sort order of the clusters changes with each refresh. Ideally, the order of those clusters would be static. You could default to an alphabetical sort order then allow users to define a custom sort order in the yaml. If the same sort order is defined for multiple clusters, you could still have the alphabetical sort in place so you would get some consistency.

```
clusters:
 - name: "Cluster A"
   address: http://cluster-a.kubecost.com:9090
   sort: 1
 - name: "Cluster B"
   address: http://cluster-b.kubecost.com:9090
   sort: 2
```

gz#302
