### ISSUE TITLE
SavedReports: Invalid argument to `aggregate`: product

### ISSUE THREAD

**Issue by iusergii** [kubecost/cost-analyzer-helm-chart#945]
**Describe the bug**
According to [doc](http://docs.kubecost.com/saved-reports.html) we can configure reports via helm `values.yaml`.

Config example:
```yaml
savedReports:
  enabled: true
  reports:
    - title: Product Allocation for Last Week
      window: lastweek
      aggregateBy: product
      idle: separate
      accumulate: false
...
kubecostProductConfigs:
    labelMappingConfigs:
      enabled: true
      product_label: Product
      team_label: Team
      environment_label: Environment
      department_label: Deparment
```

Opening current report via UI fails with an error message
```
Failed to load report data
Invalid argument to `aggregate`: product
```

Version: 1.82.0

gz#440
