### ISSUE TITLE
Alternative Chart - NFS Volumes

### ISSUE THREAD

**Issue by StevenPG** [kubecost/cost-analyzer-helm-chart#95]
**What problem are you trying to solve?**
Looking to run kubecost on-premise (referencing cloud costs) as training for teams to see cloud costs representation, and test out kube-cost capabilities for an enterprise offering that will run partially internally.

**Describe the solution you'd like**
Separate kube-cost yaml/chart for with common NFS storage-provider resources added.

Ex.
```yaml
spec:
  # Add the server as an NFS volume for the pod
  volumes:
    - name: {{volume-name}}
      nfs: 
        # URL for the NFS server
        server: {{ server_host_variable}} # Change this!
        path: {{path_variable}}
```

**Describe alternatives you've considered**
Forking repository and updating existing kube-cost.yaml file to use nfs configuration. 

**How would users interact with this feature?**
This would just allow developers the ability to deploy to on-premise and local clusters without a storage driver. It is relatively simple to create a set of NFS servers for a small cluster and stand up apps to utilize it. Using no complicated storage providers, cloud or cluster filesystems like gluster/ceph.
