### ISSUE TITLE
unused PVC postgres

### ISSUE THREAD

**Issue by fragolinux** [kubecost/cost-analyzer-helm-chart#951]
**Describe the bug**
deployed helm chart, disabling integrated prometheus because already had one, enabled persistance, using a storageclass, i see the pv bound, but pvc named postgres is in state pending

**To Reproduce**
excerpt from helmrelease file:

```
  values:
    global:
      prometheus:
        enabled: false
        fqdn: http://prometheus-ext.kubecost.svc.cluster.local
    persistentVolume:
      storageClass: "ebs-kubecost"
    networkCosts:
      enabled: true
    prometheus:
      extraScrapeConfigs: |
        - job_name: kubecost
          honor_labels: true
          scrape_interval: 1m
          scrape_timeout: 10s
          metrics_path: /metrics
          scheme: http
          dns_sd_configs:
          - names:
            - kubecost-cost-analyzer.kubecost
            type: 'A'
            port: 9003
        - job_name: kubecost-networking
          kubernetes_sd_configs:
            - role: pod
  valuesFrom:
    - kind: Secret
      name: kubecost
      valuesKey: token
      targetPath: kubecostToken
      optional: false
```

```
kubectl get pvc
NAME                     STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
kubecost-cost-analyzer   Bound     pvc-a0589568-ec1b-4113-9ac2-d916cc9418f2   32Gi       RWO            ebs-kubecost   19h
postgres                 Pending                                                                        ebs-kubecost   20h
```

gz#456
