### ISSUE TITLE
v1.83.0+ unable to disable subcharts  - kube-state-metrics, prometheus

### ISSUE THREAD

**Issue by avivgold098** [kubecost/cost-analyzer-helm-chart#983]
**Describe the bug**
Since `v1.83.0` I'm unable to disable the Prometheus & kube-state-metrics sub-charts installation.
Root cause:
Release v1.83.0 changed the chart `apiVersion` from v1 to v2. The new v2 API version required dependencies within the Chart.yaml instead of the requirements.yaml that was used before, for disabling a dependency there is a condition field.
For example:
```yaml
apiVersion: v2
appVersion: "1.83.0"
description: A Helm chart that sets up Kubecost, Prometheus, and Grafana to monitor
  cloud costs.
name: cost-analyzer
version: 1.83.0
dependencies:
- name: prometheus
  version: 11.0.2
  repository: //./charts/
  condition: prometheus.enabled
annotations:
  "artifacthub.io/links": |
    - name: Homepage
      url: https://www.kubecost.com
}
```
